### ISSUE TITLE
I logged in but my auth token is not working

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#10]
We've noticed that it is too easy to attempt a log in your first time using the app without registering, which can cause confusion, as you get an auth code to attempt (which will not work, as you haven't registered yet).

We are going to roll out a solution to this.

In the meantime, if you run into this, make sure you go back and register first.

**Comment by privateducky** [comment]
@khyberspache confirming: this is now solved through a new email directing a user to register, correct?

**Comment by khyberspache** [comment]
Confirming that if you attempt to sign-in before registering, you will not get an auth token
