### ISSUE TITLE
Feature: Ability to rename an agent after it connect to Operator

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#102]
Having meaningful names for agents makes it easier to execute the right TTPs in the right places. For example "Bob's machine" is more clear that "jjRoKlxpGSFi". I understand that the agent name can be specified on the command line when the agent is deployed but being able to change the name after it connects is valuable as you often don't know what you want to call it until you see what it is or the purpose of the agent may change, prompting a rename.

**Comment by bfuzzy1** [comment]
I second this!
