### ISSUE TITLE
Changelog of TTPs

### ISSUE THREAD

**Issue by w0rk3r** [preludeorg/operator-support#105]
Include a changelog of which new TTPs are available after an update

**Comment by privateducky** [comment]
Re-labeling this as a new feature request.  Not something we'll aim to add before the 1.0 release - but it's certainly a good idea to get in shortly after.

**Comment by privateducky** [comment]
@khyberspache can you track this as part of the ticket you're working on? @w0rk3r this will get out in the 1.0 version of Operator.

**Comment by w0rk3r** [comment]
Nice! You guys rock!
