### ISSUE TITLE
Failed Input parameters when creating Cloud Redirector in Win10 

### ISSUE THREAD

**Issue by kalimax69** [preludeorg/operator-support#106]
![image](https://user-images.githubusercontent.com/76034874/107726012-7f37e680-6c9c-11eb-80b4-c5a68dea1ac5.png)

**Comment by kalimax69** [comment]
In Windows, user must manually convert file path syntax to Linux/mac format in order for input to be accepted. Many copy and paste Windows users won't catch this as they carry over the Windows file path and remain unable to continue.

**Comment by khyberspache** [comment]
Thought we had got this one, but it's still not resolving properly.
