### ISSUE TITLE
Support for proxy aware agents

### ISSUE THREAD

**Issue by bfuzzy1** [preludeorg/operator-support#109]
**Problem:**

Currently pneuma agents do not respect system proxy settings, which could cause the agent to fail to connect back to a redirector. This becomes more of an issue in corporate environments, which commonly use proxies and web gateways. 

**Potential solution:**

Agents should attempt to auto-detect system proxy settings and make connections using those proxy settings before attempting a direct connection.

We can use this to increase connection reliability in a corporate environment with an overall agent design goal to get a connection out of the network, regardless of the environmental configurations.

Rapid7 has an open source go library [go-get-proxied](https://github.com/rapid7/go-get-proxied) that facilitates the retrieval of system proxy configurations, which I think would be a big help if this is to be added.

I'm definitely open to any thoughts you guys might have around this and we should sync via slack/discord or something to discuss in more detail.

**Comment by privateducky** [comment]
@khyberspache let's aim to get this in for the 1.0 release.

**Comment by privateducky** [comment]
We will be rolling this into the PneumaEX agent (professional version of Pneuma).
