### ISSUE TITLE
Typo in 1-min sleep

### ISSUE THREAD

**Issue by bfuzzy1** [preludeorg/operator-support#11]
Should be "noise" instead of nose.

<img width="1065" alt="Screen Shot 2020-11-06 at 10 15 52 AM" src="https://user-images.githubusercontent.com/54591490/98382550-5a86ff80-2019-11eb-94f7-e08e74f995c3.png">

**Comment by privateducky** [comment]
Good eye - thanks!

Just updated the TTP here: https://github.com/preludeorg/community/commit/50675daa51716e2bd1766779eeabda34657aef5b

It will propagate automatically today, so you should see the change soon.

**Comment by privateducky** [comment]
OK I see it in place.. @bfuzzy1 a quick way to get a copy of the new TTP is to:

1. change any of the commands, and click out of the input box
2. you'll see a 'reset' button pop up, which shows you that you changed the TTP. click this button and it'll pull in the new version (which includes the spelling fix)

**Comment by bfuzzy1** [comment]
Thanks @privateducky I'll get it sorted this weekend. I appreciate it!

**Comment by privateducky** [comment]
We've verified on this side, so closing off. 

This was fixed in this PR: https://github.com/preludeorg/community/commit/50675daa51716e2bd1766779eeabda34657aef5b
