### ISSUE TITLE
Initial login screen appears unresponsive for a few seconds

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#110]
When launching Operator inside a VM, the first time it launches, an exception/alert box is thrown (max recursion issue) from loading analytic.js twice. 

This appears do to a VM being slower to do the start up tasking in Operator and a user clicking the log in button twice.

You can reproduce this in the new Vagrant tool: https://github.com/preludeorg/operator-support/tree/master/tools/vagrant

**Comment by lzimm** [comment]
this should actually be solved here, which prevents the double load event from happening: https://github.com/preludeorg/operator/commit/71bfff7bf0adf9ce5f189506c0a06c67a1833715
