### ISSUE TITLE
psh STAGE COLLECTED FILES doesn't quote spaces in filename

### ISSUE THREAD

**Issue by limpidweb** [preludeorg/operator-support#112]
When using psh to copy files to a stage directory with the "STAGE COLLECTED FILES", if the list of files includes spaces in the names it doesn't appear that the variable passed from #{file.T1005} is quoted, causing files with a space in the name to generate errors and the command to fail.

Version: 0.9.15
Target OS: Windows Server 2019, 1809
Agent: Pneuma
$PSVersionTable from EMULATE-shell: 5.1.17763.1490
Steps to reproduce:
1. Create a file with a space in the name on a target system
PS>"This is a test file" | Out-File $env:userprofile\Documents\\"new file space.txt"
2. In Operator, go to Emulate - Deploy an adversary, ADD AN ADVERSARY
3. Add the following TTPs:
FIND RECENT FILES (T1005)
CREATE NEW DIRECTORY (T1074)
STAGE COLLECTED FILES (T1074)
4. DEPLOY
![error_noquote](https://user-images.githubusercontent.com/30066349/108275196-3ae09680-7133-11eb-842a-29f05d0bf637.PNG)
![success_nospace](https://user-images.githubusercontent.com/30066349/108275427-927f0200-7133-11eb-99ff-668091f7a762.PNG)

**Comment by limpidweb** [comment]
Here is the error reproduced in PS and an example of a fix.
![ps_reproduce](https://user-images.githubusercontent.com/30066349/108275985-5d26e400-7134-11eb-9dcc-eb11e735d5f6.PNG)

**Comment by khyberspache** [comment]
Thanks for the report @limpidweb, I just fixed it: https://github.com/preludeorg/community/pull/86

**Comment by khyberspache** [comment]
This will be available when we push our next server-side update

**Comment by limpidweb** [comment]
Doh, should have looked at the closed issues. :-)
