### ISSUE TITLE
Allow for bulk removal of TTPs within Operator

### ISSUE THREAD

**Issue by bfuzzy1** [preludeorg/operator-support#113]
I ran into an issue where I needed to bulk remove around 50+ TTPs from a single source and there is currently no way to do that in bulk from within Operator. 

I'm good with grep and sed, but others might not be so this might be something helpful to have. :)

**Comment by privateducky** [comment]
Agreed. We need to add some Editor options for additional filtering/removing of TTPs. 

I think this work should be coupled with the ability to either tab TTPs or view a filter option for "recently touched" or "mine"

**Comment by privateducky** [comment]
This will mostly get tackled in version 1.3, where we will be adding more options for TTP syncing in general. 

Our goal for TTPs is you will be connected to a set of TTP repositories and Operator will keep you in sync with any adds/deletes on those repos. For example, by default everyone is sync'd to our community and professional (if licensed) repository. Enterprises can now add their own repos, which we'll sync for all their people. So the idea is, you'll want to work against a shared repo with your team to add/delete TTPs, which will propagate to your team automatically. 

This leaves the gap of, if you're individually writing TTPs in Operator that you don't want to sync with a repo (either ours, or your team repo). We'll kick around cases for this.
