### ISSUE TITLE
Beacon target is null

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#119]
Beacon.Target property is null when attempting to deploy an adversary. 

<img width="447" alt="Screen Shot 2021-02-25 at 7 20 51 AM" src="https://user-images.githubusercontent.com/49954156/109152835-058f0680-773a-11eb-8255-5abc15934e31.png">

**Comment by masterugwee** [comment]
The TTP's I used when I got this issue, 

Parse SSH config ID T1005 
Weak Executable Files  ID T1574.010 
Print kernel diagnostic information ID T1082
View Process ID T1057
Display authorized ssh keys ID T1082
Get contents bash history ID T1552.003
Linux Enumeration and Privilege escalation discovery script ID T1082 
Hostname discovery ID T1082
Create saging directory for exfil staging T1074.001
Find Procedure in files ID T1552
List opened files by user ID T1087.001
List group password hashes ID T1082
System network connections discovery Linux and MacOS ID T1049
Dump shell path ID T1082
Enumerate users and groups ID T1087.001
Password Policy ID T1201

**Comment by lzimm** [comment]
thanks @masterugwee, how were you connected to the actual agent in question? was this running on pneuma directly connected to your operator instance? over a tunnel? or was it with the built-in thirdeye agent? anything else you can share would be really helpful trying to hunt down what went wrong.

**Comment by privateducky** [comment]
LIST OS INFORMATION T1082
 
is the new reported error TTP.

**Comment by masterugwee** [comment]
I am running Debian Linux ( Pop Os ) . Using Pneuma agent. I was connecting it through a tunnel, used ngrok.

**Comment by lzimm** [comment]
hmmm, thanks @masterugwee , one more question: what protocol were you using when connecting the agent? tcp/udp/http/grpc?

**Comment by masterugwee** [comment]
I was using tcp.

**Comment by privateducky** [comment]
@lzimm @masterugwee is this still an issue?

**Comment by privateducky** [comment]
@lzimm whatcha think on this one? Given the clear exception msg, I don't want to close this issue. Can we address the "split" error and handle it gracefully?

**Comment by masterugwee** [comment]
I haven't checked this with the updated version. I will check it out and get back to you.

**Comment by masterugwee** [comment]
I guess this is fixed. I edited the TTP and ran it again. No error was shown and I also go the desired result. 
The only change that I made was on top of the code I added a line to create a new file. 
![FixError](https://user-images.githubusercontent.com/10448437/112428986-0d09f580-8d62-11eb-89a8-27e7cc8e4bd2.png)

**Comment by privateducky** [comment]
Great, thanks! We've been making stability updates around this area in general, so very likely we fixed it incidentally.
