### ISSUE TITLE
TTP import fails on Linux build v0.9.2

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#12]
- Importing a new TTP fails on linux (DEB) build v0.9.2

**Comment by webhead404** [comment]
It also fails on Windows and macOS

**Comment by privateducky** [comment]
We're checking now. Will try to resolve by tomorrow, when we're planning the next beta version 0.9.3.

**Comment by privateducky** [comment]
In the meantime, we just disabled the training flag for this feature, so it shouldn't show up in the app (next time you start it). We'll re-enable the flag once we get the fix in.

**Comment by khyberspache** [comment]
Fix PR is up

**Comment by khyberspache** [comment]
v0.9.3 released patches this bug.
