### ISSUE TITLE
Error on macOS Big Sur after authenticating 

### ISSUE THREAD

**Issue by jamesspi** [preludeorg/operator-support#122]
Hi,

Just performed a fresh install of Operator on `macOS 11.2.1` and I get this error immediately after authenticating to operator:

<img width="257" alt="image" src="https://user-images.githubusercontent.com/20421688/110457255-bb5b3d00-80ca-11eb-8571-64a9c0e29b5e.png">

Running version `0.9.15.61`, installed via the dmg.

Thanks!

**Comment by privateducky** [comment]
Thanks for reporting! We've noticed this being common when starting Operator on MacOS in version 0.9.15. 

Solution: simply to close and reopen the app.

Reason: It occurs when clicking the login button twice, which is natural as the startup takes 2-3 seconds.

Our next release will have a permanent fix.
