### ISSUE TITLE
Operator 09.17: Unable to Login error Win10

### ISSUE THREAD

**Issue by kalimax69** [preludeorg/operator-support#128]
Perhaps a one off here but happened immediately after upgrade from 09.15.  

![image](https://user-images.githubusercontent.com/76034874/111082661-c812d300-84c6-11eb-88e1-7e478105a99d.png)

**Comment by khyberspache** [comment]
@kalimax69 I'm looking into this right now. I think it's a bug that we will need to push a new version for, but I have a work around in mind that I'm testing right now.

**Comment by kalimax69** [comment]
Sounds good- glad we uncovered this earlier than later.  But please, no rush on my account;)

**Comment by khyberspache** [comment]
![CleanShot 2021-03-14 at 17 55 26](https://user-images.githubusercontent.com/43142871/111085624-7ed67980-84ee-11eb-8fd9-b88cc04efc5c.png)

Validated this is an issue on Windows 0.9.17.

**Comment by khyberspache** [comment]
@kalimax69 Try this script out in powershell, it should migrate your data and allow you to login.

https://github.com/preludeorg/operator-support/blob/master/upgrade-patch-0.9.17.ps1

**Comment by kalimax69** [comment]
I can confirm this patch worked.  Thanks for the quick response!

**Comment by khyberspache** [comment]
We've pushed 0.9.18 which should patch this for windows users.  Leaving this open until we validate.
