### ISSUE TITLE
Tunnel needs to be reopened after deploying first agent

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#13]
We noticed, when you create and open a new tunnel, then deploy an agent connecting to it, the agent won't show up until you close/open the tunnel. 

The agent is connecting fine to the tunnel but the desktop app isn't populating the connection through to itself.

**Comment by khyberspache** [comment]
Might be as simple as enabling ControlMaster on the tunnel, but I'll dig

**Comment by privateducky** [comment]
bumping this one. @khyberspache @lzimm if either of you want to take a run at this, we should solve before we confuse too many folks!

**Comment by khyberspache** [comment]
I completely forgot about this. I'll tackle it tomorrow, sorry!

**Comment by khyberspache** [comment]
During testing for this and bug fix above, this issue is apparently resolved.  Could not replicate

**Comment by privateducky** [comment]
Not reproducing after a test today.
