### ISSUE TITLE
login error on fresh install 0.9.18 on Mac air M1 running Catalina

### ISSUE THREAD

**Issue by kalimax69** [preludeorg/operator-support#130]
<img width="1440" alt="Screen Shot 2021-03-15 at 1 41 14 AM" src="https://user-images.githubusercontent.com/76034874/111126721-4192db80-8530-11eb-8ccd-b26963c47dcd.png">

I am able to input email address and it successfully generates and send me an auth code.  Upon inputing code, it accepts it and goes nowhere.

**Comment by privateducky** [comment]
@kalimax69 this looks like a case of logging into too many machines at once... i can't see the full console but i would imagine you have a 409 response code at the bottom of the log there... 

The reason: you can only use your Operator account on 1 computer per 12 hours (part of how we handle licenses). We should show a better message though... so I'll keep this bug open for @lzimm to take a look at messaging options.

If this is not the case for you, let me know and I'll look at other reasons.

**Comment by kalimax69** [comment]
Closing this as I repeated the same steps this morning and this time I was able to log in.

**Comment by kalimax69** [comment]
Interesting.  I looked for the 409 code in the logs this morning but it looks like last nites logs were cleared.  I am only showing this morning.  It is possible I triggered the 1 machine per 12hr limit but I used 3 computers with Operator installed during the training program, sometimes all in the same day without issue.

**Comment by privateducky** [comment]
Yep, that makes sense. We pushed a change last weekend around the 1 computer limit to be more consistent. 

We'll likely loosen it up a bit but we want to come up with a way to support sharing of data between a persons computers (right now, the data is isolated to each computer, which can be confusing).
