### ISSUE TITLE
Feature request: Option to automatically save JSON logs per assessment session.

### ISSUE THREAD

**Issue by diskurse** [preludeorg/operator-support#131]
Would be great to be able to easily configure a permanent logging directory and automatic assessment session logging in JSON for ingestion into SIEM or for exporting elsewhere.

**Comment by privateducky** [comment]
Hi @diskurse thanks for the feature request!

There are two options right now for what you're looking for:

1. In the Reports section, you'll see a download button (top right) which will download the raw JSON logs for whatever time range you select
2. If you have a Professional license, you can install the Publisher plugin (Plugin section), which allows you to automatically forward your attack data into Splunk, ElasticSearch, VECTR, Slack or a custom API endpoint.

We're getting ready to release a #3 option for Professional license holders, which will hook into their Splunk instance and display what analytics caught what attacks.

Let me know if these help!

**Comment by diskurse** [comment]
That's an excellent response, thanks. I'm currently only playing with the community edition but knowing that these features are present in the professional version is great, thanks for the prompt reply!
