### ISSUE TITLE
Feature Request: Custom Ranges

### ISSUE THREAD

**Issue by phage-nz** [preludeorg/operator-support#136]
Hi,

To provide some separation between business units, it would be nice to be able to define custom ranges that agents are onboarded to or moved to once onboarded, e.g. "dev range", "test range", "prod range". That way, we can also export the report JSON for a specific set of agents rather than all of them.

Thanks,
Chris

**Comment by khyberspache** [comment]
Chris,

Thanks for reaching out! So this is actually support (both use cases) using our default free agent with community operator.

Using the `pneuma` command line flags, you can specify a range such as: `./pneuma -range dev-range` or `./pneuma -range prod-range`.

You also have the option of changing an agent's range after it has been deployed using the live configuration update modal:

Select an agent and click on the gear icon in the top right corner:
<img width="1512" alt="CleanShot 2021-03-22 at 22 25 28@2x" src="https://user-images.githubusercontent.com/43142871/112083505-8d133e00-8b5d-11eb-9ffa-35bc41fe9521.png">

Then update the range name and click submit:
<img width="1512" alt="CleanShot 2021-03-22 at 22 25 59@2x" src="https://user-images.githubusercontent.com/43142871/112083536-9ac8c380-8b5d-11eb-9c68-204ed91c7f71.png">

**Comment by phage-nz** [comment]
Awesome, thank you very much!!!

**Comment by stephanwampouille** [comment]
Hi Chris,

Thank you for opening up this feature request and I am glad Alex was able to help! I wanted to follow up with you to see if you are satisfied with Operator in its current state? Are there any other suggestions or features that you wish to see? Please do not hesitate to let us know!

Best,
Stephan

@phage-nz

**Comment by phage-nz** [comment]
@stephanwampouille all is good, thank you. Am really enjoying using Operator and at present don't have any specific feature requests apart from maybe the ability to run the server as a daemon and use the client remotely. Looking forward to v1.2.0.

Thanks,
Chris

**Comment by privateducky** [comment]
thanks @phage-nz! fun enough, a "headless" (server/daemon) option will be coming in 1.3 (~6 weeks from now).
