### ISSUE TITLE
Unable to Install on Kali 2021.1 vmware version

### ISSUE THREAD

**Issue by jacobhargrave** [preludeorg/operator-support#140]
Attempts to follow the download and install instructions for Linux result in the following issue:

┌──(kali㉿kali)-[~/Desktop/prelude]
└─$ sudo apt-get install libappindicator3-1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libappindicator3-1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libappindicator3-1' has no installation candidate

Attempts to manually download and install libappindicator3-1 fail as well:
<img width="471" alt="Kali Install Failure 03" src="https://user-images.githubusercontent.com/16504576/112692016-790c5c80-8e3b-11eb-8d48-ba4fc080129f.png">
<img width="567" alt="Kali Install Failure 01" src="https://user-images.githubusercontent.com/16504576/112692020-79a4f300-8e3b-11eb-84bd-c7f6f1d7371b.png">
<img width="370" alt="Kali Install Failure 02" src="https://user-images.githubusercontent.com/16504576/112692021-7a3d8980-8e3b-11eb-86bd-68daebf8fa7f.png">

┌──(kali㉿kali)-[~/Desktop/prelude]
└─$ sudo dpkg -i libappindicator3-1_0.4.92-8_amd64.deb
Selecting previously unselected package libappindicator3-1:amd64.
(Reading database ... 267424 files and directories currently installed.)
Preparing to unpack libappindicator3-1_0.4.92-8_amd64.deb ...
Unpacking libappindicator3-1:amd64 (0.4.92-8) ...
dpkg: dependency problems prevent configuration of libappindicator3-1:amd64:
 libappindicator3-1:amd64 depends on libindicator3-7; however:
  Package libindicator3-7 is not installed.

dpkg: error processing package libappindicator3-1:amd64 (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.31-9) ...
Errors were encountered while processing:
 libappindicator3-1:amd64

**Comment by khyberspache** [comment]
What output do you get when you run `sudo apt --fix-broken install`?  Are you on our Discord also? I can DM you and we can T/S this.

What is the output of your `uname -a`?

**Comment by khyberspache** [comment]
Accidentally clicked close when trying to post the above, reopened

**Comment by jacobhargrave** [comment]
Hey there. I'm not on Discord yet, but I'll get around to signing up eventually. Multi-tasking at the moment.

Output from sudo apt --fix-broken install:

┌──(kali㉿kali)-[~/Desktop/prelude]
└─$ sudo apt --fix-broken install                     
[sudo] password for kali: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  libappindicator3-1
0 upgraded, 0 newly installed, 1 to remove and 407 not upgraded.
1 not fully installed or removed.
After this operation, 109 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 267432 files and directories currently installed.)
Removing libappindicator3-1:amd64 (0.4.92-8) ...
Processing triggers for libc-bin (2.31-9) ...

output from uname -a:
Linux kali 5.10.0-kali3-amd64 #1 SMP Debian 5.10.13-1kali1 (2021-02-08) x86_64 GNU/Linux

Also, sudo apt-get update results in:

└─$ sudo apt-get update                                                                                                                                                                                                                                 100 ⨯
Hit:1 http://mirrors.ocf.berkeley.edu/kali kali-rolling InRelease
Reading package lists... Done

**Comment by khyberspache** [comment]
Thanks, I'm downloading the latest Kali live to see if I can replicate. After the fix broken install can you install the `deb`?

**Comment by jacobhargrave** [comment]
Unfortunately, it would seem not:

──(kali㉿kali)-[~/Desktop/prelude]
└─$ sudo dpkg -i prelude-operator-0.9.19.deb          
Selecting previously unselected package operator.
(Reading database ... 267424 files and directories currently installed.)
Preparing to unpack prelude-operator-0.9.19.deb ...
Unpacking operator (0.9.19) ...
dpkg: dependency problems prevent configuration of operator:
 operator depends on libappindicator3-1; however:
  Package libappindicator3-1 is not installed.

dpkg: error processing package operator (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.68) ...
Errors were encountered while processing:
 operator

**Comment by khyberspache** [comment]
I was able to replicate this on the latest Kali Live 2020.1 - I'll loop back once I have a fix! Thanks for the report

**Comment by khyberspache** [comment]
In the mean time, you can download and the use the AppImage version (which will work and is better because you get the automatic in-app updates)

**Comment by khyberspache** [comment]
Just download that off the site, `chmod +x prelude-operator-0.9.19-appImage` and it will run: 
![CleanShot 2021-03-26 at 17 22 02](https://user-images.githubusercontent.com/43142871/112693920-d44c4800-8e57-11eb-839f-315f1868105e.png)
