### ISSUE TITLE
python executor should not require all lines be terminated in a semicolon

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#143]
<img width="1512" alt="CleanShot 2021-04-02 at 10 11 09@2x" src="https://user-images.githubusercontent.com/43142871/113423318-44992300-939c-11eb-899d-5a0cb705a405.png">

We should allow python code be entered in editor without requiring EOL delimiting with `;`.

**Comment by privateducky** [comment]
@lzimm how do you feel about this one in relation to our discussion a few weeks back about various delimiters for languages?

**Comment by privateducky** [comment]
@lzimm bumping

**Comment by lzimm** [comment]
there's no requirement at all, that might just be an artifact of third party code getting imported
