### ISSUE TITLE
Cloud plugin, support password on Key Pairs

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#146]
* allow users to supply a password when settings up a redirector if the ssh key pair requires a password
* double check that we allow key pairs that don't have a `.pem` extension

**Comment by privateducky** [comment]
I'm not sure if this packs enough punch (i.e., worth the effort) or if having password-less keys is a fine requirement.. will stew on this one.

**Comment by privateducky** [comment]
Closing this one.
