### ISSUE TITLE
Support long running TTPs

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#149]
* TTPs have a timeout of 60 seconds built into pneuma
* Some TTPs need to run for extended periods of time
* Ability to customize time out would be nice

**Comment by privateducky** [comment]
Agreed. I think adding the ```timeout``` option we used on Caldera TTPs makes sense as a port to ours. Thoughts?

**Comment by privateducky** [comment]
This ticket has become far easier with the recent updates to Operator 1.3.

I'm going to open an internal ticket for us to start resolving this, as early as 1.4.

**Comment by privateducky** [comment]
I think all we need to do on this one is allow ```agents.js:recordResults()``` to accept an arbitrary link. 

Right now, it relies on a link being created before the instruction is sent to the agent and we apply the results to the already created link. If we additionally allow an arbitrary link to be created in this function, an agent can report new results anytime.
