### ISSUE TITLE
Command jitter support

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#150]
* Need to support jitter between TTPs executing

**Comment by privateducky** [comment]
Agreed. We have beacon jitter, adding TTP jitter makes sense.

**Comment by privateducky** [comment]
I have a PR with an explicit way of doing this: https://github.com/preludeorg/pneuma/pull/69/files

**Comment by privateducky** [comment]
@khyberspache bumping. curious what your thoughts are on the solutions for this..?

**Comment by privateducky** [comment]
@khyberspache i saw some movement on this, this week. Do we have this configured in Pneuma now? If so, can you post steps to use it?

**Comment by privateducky** [comment]
@khyberspache bumping question on this one.

**Comment by privateducky** [comment]
@khyberspache is this complete now?

**Comment by khyberspache** [comment]
This is done. There is a jitter argument on Pneuma now in the package JSON. In the future we can send a `jitter` argument with the beacon if we want
