### ISSUE TITLE
emulate UI doesn't show connected tunnels when leaving and returning to the page

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#151]
<img width="1512" alt="CleanShot 2021-04-12 at 18 32 18@2x" src="https://user-images.githubusercontent.com/43142871/114470757-6aed6880-9bbd-11eb-83cb-d8d675c496d8.png">

I connect, click on home, then come back:
<img width="1512" alt="CleanShot 2021-04-12 at 18 32 46@2x" src="https://user-images.githubusercontent.com/43142871/114470788-7b9dde80-9bbd-11eb-9a39-2b9db728645f.png">

Click on the UI element again and it shows connected:
<img width="1512" alt="CleanShot 2021-04-12 at 18 33 05@2x" src="https://user-images.githubusercontent.com/43142871/114470823-86587380-9bbd-11eb-9fff-fef794e04448.png">

**Comment by lzimm** [comment]
the default emulate icon only toggles based on the `TUNNEL_CONNECTIONS` global, which isn't used for managing switchboard connections, fixed inside the switchboard plugin here: https://github.com/preludeorg/plugins/commit/ca82edaa1e43308193545279a44e4db0453205b7
