### ISSUE TITLE
Feature: Need way to easily access the TTP yaml file on disk

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#161]
<img width="481" alt="CleanShot 2021-04-17 at 21 34 55@2x" src="https://user-images.githubusercontent.com/43142871/115131286-ed629780-9fc4-11eb-9290-6b848714bf76.png">

I couldn't copy the yaml ID here which I was trying to get in order to grab the underlying yaml file. Made me realize it would be nice to have an "open file location" button so it opens a folder window with the selector on that TTP yaml file.

**Comment by privateducky** [comment]
Marking as a bug to fix the COPY functionality of the ID. 

I'm going to push off the skip the 'open TTP file' locally option for later. I generally want the local file system to be left alone s the files aren't corrupted.
