### ISSUE TITLE
Feature: Enable Archive of Stale Agents & Associated Data

### ISSUE THREAD

**Issue by dkoch144** [preludeorg/operator-support#164]
From the emulate perspective, it would be nice to be able to archive old agents rather than just being able to either leave them or delete them. It would also be nice to be able to query the archived agents database to be able to recall work carried out in old operations such as to verify that steps taken to demonstrate a vulnerability on the corporate network no longer work or are detected. Containing this in operator seems like it might streamline the process of cumulative red team assessments.

**Comment by privateducky** [comment]
Good idea. I think it could work like this:

1. From the UI, mark an agent as "archived" which updates the agent config file 
2. The agent is then displayed/hidden differently within the Emulate section but the data remains intact and searchable.

**Comment by privateducky** [comment]
Linking this ticket to another which was just opened on the subject: https://github.com/preludeorg/operator-support/issues/170

**Comment by privateducky** [comment]
This will be available in version 1.0.

**Comment by stephanwampouille** [comment]
Hi @dkoch144 ,

I wanted to follow up with you in regards to the agent archive feature that we added upon your suggestion. Are you satisfied with the implementation from 1.0? Please let us know if you have any other ideas or suggestions that would improve your experience with Operator!
