### ISSUE TITLE
Feature: Adjust Automatic Sort of Agents in Emulate Perspective

### ISSUE THREAD

**Issue by dkoch144** [preludeorg/operator-support#165]
Currently the emulate perspective sorts by agent access datetime ascending. This places many stale agents ahead of active agents depending on how much activity you have and if you regularly clean out old agents. It may be preferable to sort active agents first with datetime ascending and then stale agents with access time descending to keep the most potentially relevant agents in focus in this perspective.

**Comment by privateducky** [comment]
Agreed.

**Comment by privateducky** [comment]
@dkoch144 this will be released in version 1.0
