### ISSUE TITLE
Manually Deleting TTP yaml Crashes Operator

### ISSUE THREAD

**Issue by dkoch144** [preludeorg/operator-support#167]
I had an adversary using a TTP which I built the yaml for manually and copied into the attack config directory. I needed to replace this TTP so I manually moved the yaml file to another location and then started up Operator. I was able to use the editor perspective to create the replacement TTP but when I went into the emulate perspective I noticed that no adversaries loaded. As I began to navigate this perspective, more things disappeared including my range options until I had nothing I could do. I navigated to the home perspective and that was missing almost all of its elements. Train was also missing everything. After restarting operator, I noticed that all perspectives functioned until I went into Emulate which caused the crash. After this, I put the TTP yaml file back into the attack config dir and now everything is working again.

It seems like a fix for this might be to check existing adversaries on launch to make sure their TTPs are intact. If not there could be a popup stating which adversary had an issue loading. Obviously this isn't an issue if people are just managing TTPs through Operator and not poking around behind the scenes so it could be possible to just lock down default permissions on the config directories as well.

**Comment by privateducky** [comment]
Agreed. 

I think the best move for this is to ensure that we scan an adversary's TTPs when Operator starts to ensure they are valid, else remove from the adversary (throwing a notification).
