### ISSUE TITLE
[Feature]: Mark agent as stale (versus) delete for beacon (non-TCP) agent

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#170]
![CleanShot 2021-04-27 at 17 57 27](https://user-images.githubusercontent.com/43142871/116317945-08ca6100-a782-11eb-91d3-5f850e614f38.png)

When an agent dies and I want to keep history, I don't have a way to mark an agent as stale/dead to prevent it from being tasked in future adversaries

**Comment by privateducky** [comment]
Linking this to a similar issue: https://github.com/preludeorg/operator-support/issues/164

This topic is currently on the internal Prelude roadmap, planned over the next 6-12 weeks.

**Comment by privateducky** [comment]
Closing as a duplicate ticket: this functionality will be available in version 1.0.
