### ISSUE TITLE
Sort and ordering capabilities to Plugins section

### ISSUE THREAD

**Issue by bfuzzy1** [preludeorg/operator-support#177]
Something to think about as the number of plugins grows having a way to bring organization i.e. sort by new, alphabetical, or recently updated would come in handy.

**Comment by privateducky** [comment]
;) you're always reading our minds.

Note the empty space/canvas when you open the plugins section. This will be getting a nice organization in the near future for finding and working with plugins.

**Comment by privateducky** [comment]
For the short term though, @bfuzzy1 i've added a search/filter on the plugins sidebar for the next release.

**Comment by bfuzzy1** [comment]
@privateducky sounds good!
