### ISSUE TITLE
Deploying compromised hosts does not work on any callback ports except for 2323

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#18]
Due to a bug in the deploy compromised server feature, there is a server-side patch that will only allow callback on port 2323. The bug is already fixed and will be available in next Wednesday's build (2 Dec 2020) of 0.9.6beta.

**Comment by khyberspache** [comment]
Related https://github.com/preludeorg/operator-support/issues/13

**Comment by privateducky** [comment]
Resolved in the last deployment
