### ISSUE TITLE
pneuma link in Agents training module displaying 404

### ISSUE THREAD

**Issue by xenoscr** [preludeorg/operator-support#2]
It may be know/intentional since this is in Alpha but the following link is currently a 404:

https://github.com/preludeinstitute/pneuma

**Comment by privateducky** [comment]
Good catch! We recently swapped to preludeorg from preludeinstitute.

**Comment by xenoscr** [comment]
The invalid one was, as of last night, still present in the upper right corner of the tutorial pages.

**Comment by privateducky** [comment]
Update made. This will be reflected in the next version, potentially getting cut today.
