### ISSUE TITLE
TTP import (directory/github) is broken

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#204]
TTP import fails for non-Prelude formatted TTPs.

**Comment by lzimm** [comment]
I'm not sure what to do with this @privateducky, you ripped out the non-prelude TTP parsing specifically, so in circumstances where you're trying to import non-prelude TTPs, it "should" fail now.

**Comment by privateducky** [comment]
correct - as long as directory + repo import of our format works, all good.
