### ISSUE TITLE
Error after login

### ISSUE THREAD

**Issue by cameronkownack** [preludeorg/operator-support#207]
![prelude error](https://user-images.githubusercontent.com/28039955/120048381-cc319580-bfcb-11eb-8ec7-b624595191d1.png)

**Comment by cameronkownack** [comment]
UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by khyberspache** [comment]
You seem to be on an old version of Operator.  Have you downloaded and run 0.9.27?

**Comment by cameronkownack** [comment]
Hello, yes I have tried that but for some reason the new version just sits
at the initial login window with the loading indicator. That's why I went
back to the older version.

**Comment by khyberspache** [comment]
You were on a pre-0.9.17 build (we are on 0.9.27 now).  The workspace structure has changed significantly which is why you can't authenticate.  If you're on linux, just run this command to blow away the old environment:
`rm -r ~/.config/Operator`

**Comment by cameronkownack** [comment]
That did the trick! Thank you so much!!

**Comment by khyberspache** [comment]
Woot! Glad it's working! Side note, this is the last beta, 1.0.0 expected next week :)
