### ISSUE TITLE
Toolbox 404 on js (also not loading from our S3)

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#209]
<img width="892" alt="CleanShot 2021-05-30 at 12 20 16@2x" src="https://user-images.githubusercontent.com/43142871/120111837-73840900-c141-11eb-91db-becc3c06683f.png">

**Comment by privateducky** [comment]
Appears to be the same issue on the ART plugin..?

**Comment by lzimm** [comment]
yeah, like i said, that's pending a release bump of the operator-support repo. jsdelivr pulls things from releases before it fronts them on their CDN. but once we do said release, it should resolve it right away.

**Comment by privateducky** [comment]
@lzimm can you clarify? i've pulled ART + Toolbox plugins from here (operator-support repo) into the S3 (dev) bucket. 

How does the operator-support versioning impact this?

**Comment by lzimm** [comment]
https://cdn.jsdelivr.net/gh/preludeorg/operator-support/plugins/toolbox/

note where it's pulling files from: preludeorg/operator-support@0.9.27/plugins/toolbox/ (ie: our latest release for the operator-support repo: 0.9.27)

once we bump that, jsdelivr will pull from the new latest release (of this git repo)
