### ISSUE TITLE
Feature Request: More TTP filters

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#22]
It would be handy to be able to filter TTPs by OS and also be able to filter out the ones that aren't available if you haven't paid.

![image](https://user-images.githubusercontent.com/22311332/100390992-5e41ec80-2fef-11eb-8498-4b86bd64cf87.png)

**Comment by privateducky** [comment]
Good ideas. Pulling @lzimm in to see this request, as he's working on a redesign of this area specifically to make it easier to work with procedures (separate from building an adversary).

**Comment by privateducky** [comment]
@clr2of8 we have completely redesigned the TTP filtering into a new section, called Editor. Give that a whirl and see how it feels!
