### ISSUE TITLE
[Windows OS] White drop down in agent range

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#220]
White drop down with white text in agent range makes it illegible unless highlighted

![image](https://user-images.githubusercontent.com/84744117/120527405-4be2aa00-c3a8-11eb-919a-326d29f9fddb.png)

**Comment by lzimm** [comment]
https://github.com/preludeorg/operator/commit/723bfcdc20aa1f0e46adf95ca907794d2ae34ac5

**Comment by w0rk3r** [comment]
Hey guys, this is also happening on Training section
![image](https://user-images.githubusercontent.com/26856693/120668749-236cb580-c465-11eb-91da-5639df7b6f02.png)
