### ISSUE TITLE
Protect Mode Empty-ish (Training Section)

### ISSUE THREAD

**Issue by bfuzzy1** [preludeorg/operator-support#221]
Returns nothing when selecting the impact selection. Not really sure how this is supposed to function.

<img width="1043" alt="Screen Shot 2021-06-02 at 1 55 11 PM" src="https://user-images.githubusercontent.com/54591490/120529205-3c646080-c3aa-11eb-8f41-383fe7486418.png">

**Comment by bfuzzy1** [comment]
<img width="1059" alt="Screen Shot 2021-06-02 at 1 58 01 PM" src="https://user-images.githubusercontent.com/54591490/120529458-8ea58180-c3aa-11eb-9690-aff0516e15af.png">

^ Before click.

Also, is protect mode rolling under training now? It wasn't before.

**Comment by privateducky** [comment]
@lzimm for consistency, think we should throw the "this course is completed" flag here?

as an alternative, we could just hide any program which has no challenges... not sure which is better, will defer to your judgement.

**Comment by lzimm** [comment]
yeah i think it makes a lot more sense not to show them, fixed here: https://github.com/preludeorg/operator/commit/b20d75616e1ac146c2806145e63a5ba2d7b849e8
