### ISSUE TITLE
Killed reports section with too many clicks..

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#223]
Steps I took:

1. Had a security recommendation, which i clicked
2. Clicked on one of the rows/links within the recommendation
3. Threw the below page, even when navigating away from and back to the section

<img width="1464" alt="Screen Shot 2021-06-02 at 2 25 18 PM" src="https://user-images.githubusercontent.com/49954156/120533238-83eceb80-c3ae-11eb-910a-dad396f29dc4.png">

**Comment by lzimm** [comment]
fixed here: https://github.com/preludeorg/plugins/commit/482921bb345a3c79c4aa7d5bfd1974a2027ae1a2

**Comment by lzimm** [comment]
fixed here: https://github.com/preludeorg/plugins/commit/482921bb345a3c79c4aa7d5bfd1974a2027ae1a2
