### ISSUE TITLE
Switchboard Error 

### ISSUE THREAD

**Issue by bfuzzy1** [preludeorg/operator-support#225]
<img width="601" alt="Screen Shot 2021-06-02 at 2 48 39 PM" src="https://user-images.githubusercontent.com/54591490/120535992-9fa5c100-c3b1-11eb-911b-d999e6201990.png">

Reproduce by clicking into the Switchboard Plugin

**Comment by privateducky** [comment]
looks like a plugin reset issue - recommended solution for version 1.0 (essentially 0.9.28 as well) will be to delete all plugins (or just reset your local environment via Settings, unless you want to keep anything specifically)

**Comment by bfuzzy1** [comment]
Local environment reset fixes this.

**Comment by khyberspache** [comment]
https://github.com/preludeorg/operator-support/issues/230
