### ISSUE TITLE
Cloud Plugin (AWS)

### ISSUE THREAD

**Issue by bfuzzy1** [preludeorg/operator-support#226]
Getting this error when attempting to deploy a redirector in AWS. It just hangs afterwards with nothing deploying.

<img width="570" alt="Screen Shot 2021-06-02 at 2 50 31 PM" src="https://user-images.githubusercontent.com/54591490/120536422-19d64580-c3b2-11eb-9213-6d46469170fb.png">

**Comment by privateducky** [comment]
looks like a plugin reset issue - recommended solution for version 1.0 (essentially 0.9.28 as well) will be to delete all plugins (or just reset your local environment via Settings, unless you want to keep anything specifically)

**Comment by bfuzzy1** [comment]
@privateducky issue resolved after resetting local environment. Would it be good to offer a quick option to reset that during the update to the end user? If they select no, then fire a warning about potential broken plugins / plugin errors?

**Comment by khyberspache** [comment]
https://github.com/preludeorg/operator-support/issues/230
