### ISSUE TITLE
Navigator Plugin (404 Error)

### ISSUE THREAD

**Issue by bfuzzy1** [preludeorg/operator-support#227]
<img width="565" alt="Screen Shot 2021-06-02 at 2 54 43 PM" src="https://user-images.githubusercontent.com/54591490/120536758-78032880-c3b2-11eb-9795-9cdb538a99c5.png">

Issue occurs when selecting an adversary in the dropdown.

**Comment by privateducky** [comment]
Confirmed this one. Same behavior for me.
