### ISSUE TITLE
'Training Flags Remaining' disappears on page after completion

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#234]
Flags on pages disappear once one is completed - you have to leave and come back to the page to refresh it.

![image](https://user-images.githubusercontent.com/84744117/120545905-3a57cd00-c3bd-11eb-977d-4d4571f771cc.png)
![image](https://user-images.githubusercontent.com/84744117/120545924-3f1c8100-c3bd-11eb-839b-ebc8972af5e4.png)

**Comment by stephanwampouille** [comment]
This is after refresh of page

![image](https://user-images.githubusercontent.com/84744117/120546147-8440b300-c3bd-11eb-8b60-7a9304e2d7bb.png)

**Comment by privateducky** [comment]
this is expected behavior.. these are the remaining training flags, so as you finish them here, they'll disappear.. but you'll see them inside the Train section as completed still.

**Comment by khyberspache** [comment]
Closing, ping me if there are any issues w/ this

**Comment by privateducky** [comment]
Re-opening: this issue is actually:
- Open a training flag by clicking a bubble
- Complete the flag
- Close the sidebar - all the remaining training flags disappear until i refresh the page.
