### ISSUE TITLE
Training flag auto moving to next flag before I'm ready

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#237]
When taking pink badge, I enter the answer to a flag while listening to the recording and it moves me to the next flag before the audio is complete. 

What options can we have to avoid this, if I want to remain on the page to finish listening?

**Comment by stephanwampouille** [comment]
possible solutions 
1)Double verification to check if both the audio recording has finished/passed a certain time stamp and the correct answer was inputted
2)Allow answer submittals once the audio recording has finished/passed a certain time stamp

**Comment by lzimm** [comment]
hmmm, i think the easiest solution is might be to disable the submit button while the audio is still playing, i can look at that

**Comment by privateducky** [comment]
> hmmm, i think the easiest solution is might be to disable the submit button while the audio is still playing, i can look at that

that seems like the slickest solution to me
