### ISSUE TITLE
TTP import (on app load) can cause the app not to load

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#239]
Force an error on a TTP while importing and it will block the ability log into the app.

**Comment by khyberspache** [comment]
Windows Defender eats the YAML file because it's malicious powershell

**Comment by lzimm** [comment]
"Force an error on a TTP while importing and it will block the ability log into the app." @privateducky what exactly does that mean? lol

**Comment by privateducky** [comment]
;) try to mange a yml file (in your workspace/attack directory) then start Operator and check your console log.

**Comment by lzimm** [comment]
did you manage to import a broken yml file in the first place though?

**Comment by lzimm** [comment]
furthermore, just did, i got this and the app just removed the broken ttp and started fine:

![image](https://user-images.githubusercontent.com/139388/120711233-fc69b000-c473-11eb-8783-1d980f7d17cb.png)

**Comment by privateducky** [comment]
@khyberspache you were testing this flow.. thoughts?

**Comment by khyberspache** [comment]
This is G2G. It was a red herring - there was another service bound to port 8888
