### ISSUE TITLE
MITRE ATT&CK Navigator integration + exportable adversary layers

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#24]
An integrated ATT&CK Navigator would be helpful for filtering on TTPs when deploying an adversary and for quick visual reference when browsing saved adversary profiles.

Exportable adversary profiles as Navigator layers would be useful for reporting.

**Comment by privateducky** [comment]
This is in our short term priority list. We'll be releasing a concept called plugins (likely this week) and the ATT&CK integrations are likely to come following this. Bookmarking this issue to come back to.

**Comment by privateducky** [comment]
@VVX7: @bfuzzy1 just contributed the ATT&CK Navigator plugin, which does a handful of things you've described above. This plugin will automatically be available to you in the 0.9.9 version next week.

The one thing not in so far would be automatic layer creation for existing adversaries.

**Comment by privateducky** [comment]
Closing with solution in place. Please re-open if necessary.
