### ISSUE TITLE
Plugins show incorrect plugin configuration fields

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#241]
![CleanShot 2021-06-04 at 14 02 05](https://user-images.githubusercontent.com/43142871/120844494-731eb000-c53d-11eb-91f3-69c569793362.png)

This is fixed here: https://github.com/preludeorg/operator/pull/1414/files

**Comment by privateducky** [comment]
@khyberspache removing 1.0.0 label for now, as we're not sure this is fixed yet
