### ISSUE TITLE
Editor plugin parsed results UI different from Operate section UI

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#242]
Editor:
<img width="162" alt="CleanShot 2021-06-04 at 20 12 22@2x" src="https://user-images.githubusercontent.com/43142871/120873712-3e2c5080-c571-11eb-9209-3d4daca92019.png">

Operate:
<img width="195" alt="CleanShot 2021-06-04 at 20 13 16@2x" src="https://user-images.githubusercontent.com/43142871/120873732-50a68a00-c571-11eb-96ec-442a53a609ff.png">

**Comment by khyberspache** [comment]
Operate section has the hover view implemented

**Comment by lzimm** [comment]
fixed here: https://github.com/preludeorg/plugins/commit/571a7892cd4f1fd2bfec03a9260502c096e1cf10
