### ISSUE TITLE
Update agent configuration modal tasks agent with a sleep value that matches the agents current sleep value

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#243]
<img width="1512" alt="CleanShot 2021-06-04 at 21 43 01" src="https://user-images.githubusercontent.com/43142871/120876289-ed6f2480-c57d-11eb-8a82-1dfa008f8751.png">

agent is getting tasked with a new Sleep = 4 value, but the agent already has a sleep value of 4

**Comment by khyberspache** [comment]
Repro:
1. Start agent with sleep value 4
2. open configuration modal
3. click save
4. agent will get new task to update sleep to 4

**Comment by privateducky** [comment]
This is a nice-to-have - won't hold next release for it.. but if we fix it today, great.

**Comment by privateducky** [comment]
OK, since this is an easy one, we'll aim to get this in for 1.1.

**Comment by privateducky** [comment]
Fixed in 1.1.
