### ISSUE TITLE
ART plugin not loading all atomic tests properly

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#246]
No TTPs are loaded from this file, which means we are probably missing some other TTPs as well:

- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1059.001/T1059.001.yaml

**Comment by doctormay6** [comment]
I was able to reproduce this on v1.0 with the local environment reset before testing

**Comment by doctormay6** [comment]
We can link this to my PR #248

**Comment by khyberspache** [comment]
This is now available in production!
