### ISSUE TITLE
ART plugin not importing input arguments correctly

### ISSUE THREAD

**Issue by doctormay6** [preludeorg/operator-support#247]
When input arguments of the same name occur multiple times, the config.yml that is saved only contains the most recent value for that variable. For instance in [T1059.001](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1059.001/T1059.001.yaml), the input argument `file_name` is used multiple times, but the resulting config.yml after the ART plugin import only contains one instance of the variable which will not work for most the tests using it.

**Comment by doctormay6** [comment]
I ran the following script from the atomic-red-team top level directory:
```python
import yaml
import os

for root, dirs, files in os.walk("atomics"):
    for filename in files:
        if (".yml" in filename or ".yaml" in filename) and filename != "index.yaml":
            inputArgs = []
            try:
                with open(os.path.join(root, filename), "r") as atomicFile:
                    atomic = yaml.load(atomicFile, Loader=yaml.FullLoader)
                    for test in atomic["atomic_tests"]:
                        if "input_arguments" in test:
                            for arg in test["input_arguments"].keys():
                                if arg in inputArgs:
                                    raise(ValueError(f"Found duplicate input arg '{arg}' in {filename}"))
                                else:
                                    inputArgs.append(arg)
            except ValueError as e:
                if not "charmap" in str(e):
                    print(e)
            except Exception:
                pass
```
It looks like there are many files with duplicate input args for the same subtechnique. We will have to extend the prefix all the way out to test number within the subtechnique (ex. T1003.001.1.output_file where the last digit is the test number).

**Comment by privateducky** [comment]
@ClickForDetails can you release a new version of this plugin?

**Comment by ClickForDetails** [comment]
This has been deployed. Users will receive a prompt to download the new ART plugin

**Comment by privateducky** [comment]
Perfect - we'll keep this open as soon as the servers refresh and the plugin is available. Good work!

**Comment by doctormay6** [comment]
I got the update and it looks like it's importing properly now. Thanks for your work on this!

**Comment by stephanwampouille** [comment]
Hi C.J.,

I wanted to follow up on this ticket and thank you for reporting this bug! Are you satisfied with the fix and do you have any other questions for us! Please do not hesitate to reach out, we appreciate it greatly!

Best,
Stephan

@lawndoc
