### ISSUE TITLE
Cloud Plugin returns success even with incorrect creds

### ISSUE THREAD

**Issue by w0rk3r** [preludeorg/operator-support#251]
The cloud plugin doesn't validate the response's status code, resulting in returning success when we got status 400 for Invalid creds or other errors related to the account.

![image](https://user-images.githubusercontent.com/26856693/122165376-7fb0db80-ce4e-11eb-95dd-217846a6ea97.png)

![image](https://user-images.githubusercontent.com/26856693/122165426-8f302480-ce4e-11eb-86aa-f88ea51945d0.png)

I was going to try implementing something but ended up with some hacky stuff, but I think checking res.ok and including the response text in the failure notification would do the job on https://github.com/preludeorg/operator-support/blob/7bf15deb5501381de8743fc7f8e0df944474d4ca/plugins/Cloud/Cloud.html#L272 

Thank you guys!

**Comment by privateducky** [comment]
Good find - and eye for the fix. We'll roll out a fix today!
