### ISSUE TITLE
Blank Reports Window

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#252]
Empty reports window with the following errors attached. Refresh doesnt fix.
![Reports Error](https://user-images.githubusercontent.com/84744117/122606929-c4539700-d047-11eb-99b0-d0b5db295002.png)

**Comment by stephanwampouille** [comment]
@lzimm wont let me assign you but wanted you to see

**Comment by lzimm** [comment]
fixed here: https://github.com/preludeorg/plugins/commit/799cedf4192a5171688ce77abc9f15d47791d16a

**Comment by privateducky** [comment]
@lzimm can you update the reports plugin in prod so we can get the change?

**Comment by lzimm** [comment]
should be fixed now. locked out of my AWS account so I had to do some tricks though :P
