### ISSUE TITLE
High number of modified TTPs

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#253]
I had a large amount of modified TTPs when I know I definitely didn't modify that many. Could be a bug? @lzimm 
![modified](https://user-images.githubusercontent.com/84744117/122615680-e9033b00-d056-11eb-9a43-1c6963744aca.png)

**Comment by stephanwampouille** [comment]
Again wont let me assign @lzimm

**Comment by lzimm** [comment]
this looks like the remnants of professional TTPs that were never upgraded (possibly due to switching accounts from a community user -> professional without going through the app to do it)
