### ISSUE TITLE
Cloud plugin doesn't display correct options

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#255]
<img width="1512" alt="CleanShot 2021-06-27 at 15 30 11@2x" src="https://user-images.githubusercontent.com/43142871/123557038-a16a6680-d75c-11eb-950d-83780b4b3fa6.png">

**Comment by privateducky** [comment]
Dip of Operator issue 1488.

**Comment by lzimm** [comment]
this should actually be fixed here: https://github.com/preludeorg/operator-support/pull/268
