### ISSUE TITLE
Enable per-range Encryption/Decryption functions

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#257]
It would be extremely useful to allow each range to have a discrete Encrypt/Decrypt function for each range. This would enable us to deploy and test agents in a "Dev range" for example, while still having production agents in other ranges with actual encryption functions

**Comment by bfuzzy1** [comment]
Would this just offer the ability to decrypt the agent itself or the traffic or both?

**Comment by secdev-01** [comment]
So , my thinking was, you may have a range, where you only need Base64, dependent on the agent. Others may need full encryption for request/responses.  This would give you the ability to have a profile per range, or perhaps it could be a Fact, that is specific to a range.

**Comment by privateducky** [comment]
This makes sense - and would be a pretty quick thing to do on our end (probably only a couple hours to implement and test). We'll keep this thread going until we circle on it.

**Comment by bfuzzy1** [comment]
> So , my thinking was, you may have a range, where you only need Base64, dependent on the agent. Others may need full encryption for request/responses. This would give you the ability to have a profile per range, or perhaps it could be a Fact, that is specific to a range.

I like this!

**Comment by privateducky** [comment]
You'll get a global option starting in 1.1, where you can check the encryption types you want to accept across all agents/ranges. 

![Screen Shot 2021-07-29 at 8 16 05 AM](https://user-images.githubusercontent.com/49954156/127499205-6b4c6f6a-1d07-49a3-99fb-56524292192a.png)

**Comment by privateducky** [comment]
closing, as we extended this feature per ^^
