### ISSUE TITLE
Build out and support a fully script-based agent

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#258]
fully in-memory agents would help in windows environments where App Control is enabled and Pneuma cannot run

**Comment by bfuzzy1** [comment]
I agree with this file-less malware is / was pretty common. This is a good opportunity to extend emulation/simulation capabilities for the platform and offer organizations a chance to test a file-less malware option in their environment especially the smaller orgs who might not have been hit with malware like this before.

**Comment by privateducky** [comment]
@khyberspache i know you were tinkering on this with someone... what's the status? just curious.

**Comment by privateducky** [comment]
@khyberspache what's the status of this as a ticket, overall? I know we've achieved multiple agents but unsure what you have in mind in general for scoping this particular ticket.

**Comment by privateducky** [comment]
@khyberspache bumping

**Comment by khyberspache** [comment]
@privateducky closing this as we have script-based agents for all platforms now (schism -> linux, jambi -> windows, hush -> macOS)
