### ISSUE TITLE
Integrate and support ngrok for redirectors

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#259]
ngrok would provide a simple way for people to hook up ephemeral redirectors to Operator. Extending cloud plugin to either leverage a local ngrok binary or use the ngrok reverse SSH capability (or both) would provide an infrastructure-less redirector for HTTP/S (and maybe TCP/GRPC) agents

**Comment by bfuzzy1** [comment]
Having a server-less option would be interesting. Ngrok rate limits requests for non-paid versions. https://ngrok.com/pricing
Not sure what the impact would be outside of setting the sleep/jitter to be higher for this specific option. Something to think about probably a lot to discuss around this specifically.

**Comment by secdev-01** [comment]
It may be specific to teams, our team has workflows for ngrok, we can ensure we whitelist call back ips, leverage ssh gateways, register custom domains (CNAME Redirects), and import certificates. IT may be unique to us, but the business license is what our team uses. If this doesn't appeal to broader Operator users, that is completely fine. 

In addition ngrok gives us TLS inspection and logging on callbacks.

`https://ngrok.com/docs#client-api`. 

For us the specific use case insulates our organization from our AWS api keys, and is functionally equivalent to Gateway Redirectors.

**Comment by privateducky** [comment]
> 

"server less" with ngrok just means you don't own the server, ngrok does right? or is there a different approach I'm missing here?

**Comment by privateducky** [comment]
> Having a server-less option would be interesting. Ngrok rate limits requests for non-paid versions. https://ngrok.com/pricing
> Not sure what the impact would be outside of setting the sleep/jitter to be higher for this specific option. Something to think about. Probably a lot to discuss around this specifically.

@bfuzzy1 "server less" with ngrok just means you don't own the server, ngrok does right? or is there a different approach I'm missing here?

**Comment by privateducky** [comment]
If someone wants to give this a run, I'd recommend starting with an ngrok plugin which installs/manages the ngrok binary and connection to their cloud service. that would give us a bit of a playground we could explore options more tangibly. 

I'd be hesitant to add it to the core Operator platform, as it's a separate code base (not open source, right?) that we'd be accountable for - but a plugin would allow us to fully trial the best use case.

**Comment by secdev-01** [comment]
I tend to agree.  I wonder how many teams use ngrok?  If its just 1 or 2  teams, then it may not be priority.  There is a requirement that you would have to have a paid plan to take advantage of the features like ip filtering, custom domains and such. I like the plugin idea as well.

You can start a tunnel with ssh as well. https://ngrok.com/docs#ssh-gateway. 

Which is nice to create a tunnel without having to have the binary.

**Comment by privateducky** [comment]
closing, as we haven't had a big push for ngrok plugins. wouldn't mind re-opening if this becomes of interest!
