### ISSUE TITLE
Fresh Ubuntu 18.04 requires dependency 

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#26]
When installing Operator on a fresh Ubuntu 18.04 image, it requires:
```
sudo apt-get install libappindicator3-1
sudo apt --fix-broken install 
```
In order to install successfully.

**Comment by khyberspache** [comment]
I'll put this up on the website as an installation note.

**Comment by khyberspache** [comment]
Update merged into master: https://www.prelude.org/download/current
