### ISSUE TITLE
Create a "Tab" system in Editor (or similar) to enable easier kill chain construction

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#261]
When working in editor, it is very hard to build complex kill chains because I cannot keep multiple TTPs open at the same time.  It would be very useful to have a Tab system so that I can flip between TTPs quickly. Even better if I can split view TTPs side-by-side so that I could see the Inputs/Outputs of multiple TTPs as I'm working on them

**Comment by bfuzzy1** [comment]
I think this would streamline what is essentially a "workspace". Could potentially have a button that uses all the open tabs or selection of tabs to one-click create a full adversary.
