### ISSUE TITLE
Default operator to running with no discovered facts, add ability to toggle on "use all discovered facts"

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#262]
Very rarely do I find it useful to carry facts over between discrete operations. Usually I want to run a kill chain, manually do something, then either run the same kill chain again OR use a small subset of the Facts in a secondary (and so on) operation.

It would be useful to default to running all operations with an empty "discovered facts" set, unless it's explicitly toggled on and a desired behavior.

**Comment by khyberspache** [comment]
At the very least, there needs to be a way to empty the discovered facts from an agent.

**Comment by privateducky** [comment]
agreed on both accounts

**Comment by khyberspache** [comment]
Will this be in 1.2?

**Comment by privateducky** [comment]
because you're the best - i'll get a PR for this in right now.

**Comment by khyberspache** [comment]
Dawwwww

**Comment by privateducky** [comment]
donezo- PR pushed. lemme know if you can take a QA crack at that.

**Comment by khyberspache** [comment]
Is it the facts endpoint PR? That seems like it's addressing a different ticket based upon read?

**Comment by privateducky** [comment]
nope, that's a different one! i'm double-fisting a few PRs over here ;) i'll link the ticket to that PR

**Comment by khyberspache** [comment]
👍

**Comment by privateducky** [comment]
@khyberspache this is now available in dev.
