### ISSUE TITLE
Allow TTPs to "inject" facts into the planner when user events happen later on 

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#263]
Example:
- Operation runs through several TTPs and stages a payload that contains a curl command that executes when a user double clicks on it.  Operation blocks/waits for a specific fact.  Later on, user clicks on file and things happen (like collecting their password/token/etc) and cURLs that information back to Operator which fills in the missing fact, resuming the operation.

**Comment by lzimm** [comment]
presumedly this one is attached to here: https://github.com/preludeorg/operator/pull/1518
