### ISSUE TITLE
Editor technique drop-down is hard to use for some tactics

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#265]
Some tactics uses the same name for multiple techniques and it hard to know which is the correct Technique. Example, resource development:

![CleanShot 2021-07-07 at 10 59 19](https://user-images.githubusercontent.com/43142871/124782897-9bba1100-df12-11eb-8334-ea7587ec4629.png)

**Comment by privateducky** [comment]
Re-marking as bug. 

It should be easy to add the technique name. 

In solving this, we should also make our back end API compatible with latest ATT&CK (we are one version behind).

**Comment by lzimm** [comment]
have an editor side change here: https://github.com/preludeorg/plugins/commit/ef4df29d50de8f9cf5b32a09a1c5b64542969663

currently going up on dev

**Comment by privateducky** [comment]
We are now showing sub-techniques in the Editor drop downs.
