### ISSUE TITLE
Add pneuma local and remote configuration file specification

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#266]
Change pneuma to leverage the new go 1.16 embed capability for the local configuration file.
Add a remote configuration file specification option.

**Comment by khyberspache** [comment]
Part 1 implemented here: https://github.com/preludeorg/pneuma/pull/71/files

**Comment by khyberspache** [comment]
next up, argument to a file path with the config vs embedded config

**Comment by privateducky** [comment]
@khyberspache checking on this one, as it's been open for awhile. any plans to do this?

**Comment by khyberspache** [comment]
@privateducky closing this as I don't want to sink any more effort into pneuma, we will focus on next flagship agent
