### ISSUE TITLE
Editor deploy TTP does not use Automatic variables that have been overridden in Operate

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#267]
Repro:
1. Start agent
2. Change operator.payloads to not have a port number
3. Deploy TTP in Operate, Variables load properly
4. Deploy in Editor, variables do not load properly

![CleanShot 2021-07-08 at 15 18 53](https://user-images.githubusercontent.com/43142871/124978460-cfbf3000-dfff-11eb-85a7-68aa91354228.png)
![CleanShot 2021-07-08 at 15 17 07](https://user-images.githubusercontent.com/43142871/124978436-c59d3180-dfff-11eb-9a5f-9e15c05a4808.png)
![CleanShot 2021-07-08 at 15 19 00](https://user-images.githubusercontent.com/43142871/124978468-d352b700-dfff-11eb-870e-2d89f5947e9b.png)

**Comment by lzimm** [comment]
fixed here and uploaded to dev: https://github.com/preludeorg/plugins/commit/b99958c6bc0be212257ec373c75cdc73f391bfa8
