### ISSUE TITLE
author/tag fields broken when creating new TTP in editor section

### ISSUE THREAD

**Issue by lzimm** [preludeorg/operator-support#27]
In version 0.9.6, there is a bug that may prevent you from properly entering the author and tag fields when creating a new TTP on the editor section.

**Comment by lzimm** [comment]
fixed here: https://github.com/preludeorg/operator/commit/16a30dbc7a5e700831203e25ca242dd16d40e545

**Comment by privateducky** [comment]
This will be available in the 0.9.7 version, coming next week.
