### ISSUE TITLE
Add a multi-select agent delete option

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#272]
During development, I spam agents, and deleting individually is a pain. Having a bulk delete would be nice

<img width="1512" alt="CleanShot 2021-07-12 at 22 00 11@2x" src="https://user-images.githubusercontent.com/43142871/125378379-a0d8ef00-e35c-11eb-89da-188157e1addf.png">

**Comment by privateducky** [comment]
@khyberspache i've thought about this a little bit... what do you think about an option in settings, when you 'reset local environment', that gives you a list of things you can reset? like: 

- agents (maybe all or by range?)
- ttps
- settings
- adversaries

do you think that would additionally cover you case here, or do you think there's enough cases of deleting only subsets of agents aside from ranges?

**Comment by khyberspache** [comment]
I don't want to have to leave the operate tab to perform this action. Settings is a bad UX for both clicking away from where I am and we don't save app state

**Comment by khyberspache** [comment]
I also want a "delete range" option in Operate too.

**Comment by khyberspache** [comment]
Bumping this. It's too important to not integrate ASAP.

**Comment by privateducky** [comment]
This will be deployed in version 1.2.
