### ISSUE TITLE
Sending configuration update to HTTP agent doesn't work

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#273]
<img width="886" alt="CleanShot 2021-07-13 at 09 37 42@2x" src="https://user-images.githubusercontent.com/43142871/125461650-04a3e4ee-32ca-49a0-8479-7d523c8ad327.png">

`[2021-07-13T13:38:37.982Z]: :1551:Uncaught TypeError: Cannot create property 'Address' on string 'http'`

**Comment by privateducky** [comment]
Interesting you posted this today-- I was getting ready to open a bug on the same thing, but in a different way: if you send in a beacon.Target without a port, you get a similar issue as this (related to how we split on a colon). The same fix should solve both cases.
