### ISSUE TITLE
Issue: Failing to import TTPs from github repo

### ISSUE THREAD

**Issue by cristiancamps93** [preludeorg/operator-support#277]
Hello,

I've tried to import TTPs from RedCanary Atomic Red Team and I'm not able to do so.

Following the instructions given in youtube it doesn't import the TTPs:
Youtube official video I've followed: https://www.youtube.com/watch?v=kY3-NBES1gk
Github repo I'm trying to import: https://github.com/redcanaryco/atomic-red-team.git

Attaching a screenshot, it keeps thinking and doesn't import anything.

![image](https://user-images.githubusercontent.com/14968196/126303340-a1ab3f14-7066-48f7-9af7-b5388d05fe3a.png)

Thanks in advance.

**Comment by privateducky** [comment]
Hi @cristiancamps93 thanks for getting in touch!

There's actually a dedicated ART plugin that does the import and handles things like input arguments and default values now. Head to the plugins section and choose ART.

We'll update the YouTube clip.

**Comment by privateducky** [comment]
@khyberspache bumping this one.

**Comment by cristiancamps93** [comment]
After downloading the project from RC github I tried to import the folder to Prelude but it still does not work.

I've tried to import by entering the path of a yaml file and same result.

Maybe should be worth to detail the use case of importing all the RC tests.

However, thanks for your quick response.

**Comment by privateducky** [comment]
@cristiancamps93 here are the complete steps:

1. Go to the Plugins section of Operator, click on the ART plugin (and confirm the install, if you haven't yet)
2. Inside this plugin, you'll see an input box to enter your local path to your atomic-red-team cloned repository. Enter that. 
3. You should see all the TTPs which have been imported
4. Click into the Editor section, where you will see all your TTPs under the ART tactic.

![Screen Shot 2021-07-28 at 12 00 39 PM](https://user-images.githubusercontent.com/49954156/127356420-922678dc-f062-4eed-bd0f-3997a865ddde.png)

**Comment by privateducky** [comment]
@khyberspache can you patch the demo video we have on YouTube?

**Comment by khyberspache** [comment]
@privateducky I'll push a new video when I get a few hours later this week. We can pull the video down for now though?

**Comment by privateducky** [comment]
Yep, feel free to pull the video in the meantime. Thanks!

**Comment by privateducky** [comment]
@khyberspache bumping this one, as we've had a few people get turned around after watching the video. got cycles this week to patch it?

**Comment by privateducky** [comment]
The video with the misleading/old way of doing ART import has been pulled offline.
