### ISSUE TITLE
OperatorAPI /plugin endpoint does not return config

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#280]
The  /plugin/<pluginName> endpoint always return `false`.

Expected behaviour:
The  /plugin/<pluginName> endpoint should return the plugin config.

```
curl -H "Authorization: $operator_token" localhost:8888/plugin/cloud
false
```

**Comment by lzimm** [comment]
hmm, i can't repro that at all. is the cloud plugin installed on your current workspace @VVX7 ?

**Comment by VVX7** [comment]
It is installed but not deployed.  All plugins return false.
I'm using the linux appimage on Ubuntu 20.

**Comment by lzimm** [comment]
@ClickForDetails @khyberspache @privateducky can one of you guys try to repro this?

**Comment by khyberspache** [comment]
@lzimm tried on Operator 1.0.0 and it worked for me:

```
curl -H "Authorization: $operator_token" localhost:8888/plugin/cloud

{"name":"Cloud","description":"Deploy redirectors and test ranges","version":"29341b8cfa3253c850f10b60737fb447","native":false...
```

**Comment by khyberspache** [comment]
AH! I can repro on Kali

**Comment by khyberspache** [comment]
@lzimm 

```
[2021-07-22T21:45:07.357Z]: Error: ENOENT: no such file or directory, open '/home/kali/.config/Operator/login.prelude.org/plugins/cloud/config.yml'
﻿```

**Comment by khyberspache** [comment]
@lzimm figured it out.  Case sensitive file system vs non-case sensitive file system.
<img width="1115" alt="CleanShot 2021-07-22 at 17 47 16@2x" src="https://user-images.githubusercontent.com/43142871/126713683-cf0e650b-4ddd-4745-8be5-fa642bf2d9a2.png">

**Comment by khyberspache** [comment]
Any endpoint that does any kind of mapping to filesystem paths is going to have this issue on any case sensitive file system

**Comment by privateducky** [comment]
We are making an update for 1.1 that will return a 404 for a requested plugin of incorrect case.
