### ISSUE TITLE
Switchboard will not connect deployed redirectors (Operator 1.0.0)

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#281]
![image](https://user-images.githubusercontent.com/43142871/126707040-43c53064-70ff-4dc3-b702-564cc24e281c.png)

Get failure to open tunnel, but agents can still connect

**Comment by privateducky** [comment]
This required a Switchboard tool update, correct? Did that get deployed last night or still in progress?

**Comment by lzimm** [comment]
correct, and yeah, was deployed last night, should be updated now.
