### ISSUE TITLE
Support queue of TTPs to new agents in a range that has queued TTPs remaining on some agents

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#283]
- Use case:  task agent to ID and leverage a priv esc that responds with an escalated agent to either the same range (or a new range); I might want to immediately call persistence TTPs for example.

Ideas for how to handle this:
- Support "requeue" somehow if agents in the range have queued TTPs remaining
- Support "queue transfer" so that agents could be ID'd as a source Agent and try to pass their TTPs to agents that they specifically spawned (by PID?)

**Comment by privateducky** [comment]
I've been thinking on this one for awhile. We did it the way you describe in Caldera but there are some cons to that approach, primarily the assumption of where you want the new agents to start in the operation (beginning or a specific part of the kill chain). 

I think we can address this when we add "chain of chains", as the break between chains could be the ideal point to re-check which agents should be in the operation. So if chain 1 starts a new agent in the range, chain 2 would include it. This would give us a predictable way to approach the con above.

**Comment by privateducky** [comment]
Chain of chains may be coming sooner vs later btw because of how we'll be addressing scheduling soon.
