### ISSUE TITLE
Agents beaconing in on new ranges doesn't update operate range drop down

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#284]
Using my chain for next week the operate range drop-down isn't updated as I would expect when the elevated agent beacons in:

<img width="312" alt="CleanShot 2021-07-22 at 23 44 51@2x" src="https://user-images.githubusercontent.com/43142871/126735230-e86ab673-d9a2-4e23-920a-a055d6eef877.png">

**Comment by privateducky** [comment]
@khyberspache i haven't noticed anything abnormal in the drop-down when agents come in... are you not seeing a new range in the drop down when the first agent of the range beacons in? Repro steps for your case would be helpful on this one.

**Comment by privateducky** [comment]
This was found to be due to having a space in the range name. Solved for version 1.1.
