### ISSUE TITLE
ThirdEye cannot handle certain TTP inputs

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#286]
a large TTP (8+ lines) will cause ThirdEye to fail. I assume we aren't chunking on either the send or the receive 

<img width="897" alt="CleanShot 2021-07-23 at 01 24 55@2x" src="https://user-images.githubusercontent.com/43142871/126740617-6ec1992c-591e-413a-b88f-337ad510bbeb.png">

**Comment by khyberspache** [comment]
This TTP will repro:
```bash
cat <<EOF > /tmp/email.eml
User-Agent: Microsoft-MacOutlook/16.51.21071101
Date: Fri, 23 Jul 2021 01:16:26 -0400
Subject: Team contact info update
From: Alexander Manners <alex@prelude.org>
To: "prelude_placeholder@prelude.org" <prelude_placeholder@prelude.org>
Message-ID: <BN6PR1801MB19075ABD0F5E8B318A84B36EA4E59@BN6PR1801MB1907.namprd18.prod.outlook.com>
EOF
```

**Comment by lzimm** [comment]
hmm, seems to be working in master. was `1.0.0` before we split thirdEye and hooked it directly into the agent without going over the network @privateducky ?

![image](https://user-images.githubusercontent.com/139388/126812500-1d64b604-5ec0-4de6-98cd-55c9f15d0b0a.png)

**Comment by privateducky** [comment]
Yes, it was

**Comment by lzimm** [comment]
ahh yeah, should be fixed in master now then.
