### ISSUE TITLE
OperatorAPI /agent link type

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#290]
`agent.links.pid` normally returns an int but may return a string when no executors are found.

pid should return int `-1` to avoid issues with typed languages.

```
curl -H "Authorization: $operator_token" localhost:8888/agent?facts=1&links=1

...
"links": [
            {
                "unique": "0df5e19e-2b9c-4471-9ca0-a02ca4496e51",
                "tag": "fe3e9c69-5519-4b50-95d0-4c0f9366cab9",
                "host": "yOXtUvLcDyGl",
                "platform": "linux",
                "timestamp": 1627170239771,
                "ttp": "6469befa-748a-4b9c-a96d-f191fde47d89",
                "executor": "Skipped",
                "request": "",
                "response": "No Executors Found",
                "status": -1,
                "pid": "Skipped",
                "tactic": "collection",
                "technique": "T1074"
            },
...
```

**Comment by privateducky** [comment]
This is a good point. Right now, we're using the convention of "Skipped" for non-executed links - but the typing is definitely not consistent. 

Empty/none would be equivalent to a 0 integer. Any issues with that?

We'll look around for any other use-cases for skipped links, because if we have a few potential reasons it'll be easy to get behind a -1, -2, -3 type of convention for reasons why links didn't run.

**Comment by VVX7** [comment]
Yep, 0 is the ideal value for an empty/none type int.

It would be great if we could omit returning literal `null` values because it makes it easier to handle in typed language like Nim (I'm a few hundred lines of hooks into massaging JSON to serialize it correctly because of this).

**Comment by lzimm** [comment]
@VVX7 what if we made the pid a string instead, and just coerced actual process ids to strings? that way we'd break less of our plugin code while preserving the explicit 'skip' state on links that were never executed.

**Comment by VVX7** [comment]
Sure @lzimm, that would work. btw I'll open a separate issue for returning `null` to not taint this one.

**Comment by lzimm** [comment]
awesome. thx man, both issues will likely be fixed at the same time (you should be getting `"0"` instead of null) but keeps things tidy spitting up issues :)
