### ISSUE TITLE
OperatorAPI /schedule constructor incorrect params

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#291]
The Schedule constructor at line 330 of handler.js sets the adversary id to `'no'` which breaks the param assignment order.

Removing `'no'` should fix this.
```
const sch = new Schedule(req.body.range, 'no', req.body.adversary, req.body.day, req.body.hour, req.body.minute);
```

**Comment by privateducky** [comment]
Good find, this was a legacy option for scheduled adversaries. We'll address for v1.1.

**Comment by lzimm** [comment]
hmm, it looks like this was already fixed a while ago (https://github.com/preludeorg/operator/blob/cec2469b9f8c2e68d65a66fcf2b65d4f7e4b4180/static/js/api/api.js#L329)

**Comment by privateducky** [comment]
perfect, thanks for the confirmation @lzimm !
