### ISSUE TITLE
Add ability to "prompt for plugin updates later"

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#296]
- During an engagement or any production testing teams will probably tend to shy away from updating anything right before or during execution of an exercise or engagement so maybe having those update pop ups occur less frequently once a user hits no on them would be good to look into if it's not a "required" update.

**Comment by lzimm** [comment]
solving this via the updates proposed here: https://github.com/preludeorg/operator-support/issues/295#issuecomment-992866469

**Comment by privateducky** [comment]
This change will be reflected in 1.4.
