### ISSUE TITLE
Editor: remove tags from the sidebar

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#298]
Tags on the sidebar get in the way of navigating tactics and techniques.
Consider using a tag search bar that pins tags to build a filter.

**Comment by lzimm** [comment]
for the new editor we have a bunch of updated navigation behaviours (including the ability to search for things like `tactic:collection` or `technique:t1005` or `tag:custom`, but we've also removed the technique tree at the bottom, and though the tag tree is still there, it shouldn't get in the way of navigating by primary tactics or anything like that anymore.
