### ISSUE TITLE
Error:error:1e000065:Cipher

### ISSUE THREAD

**Issue by xenoscr** [preludeorg/operator-support#3]
Getting the following error trying to test an agent after changing the key:

![beacon-decrypt-error](https://user-images.githubusercontent.com/2199813/97793427-213a3400-1bc2-11eb-8e1d-cfb62fd845c9.PNG)

I have tried closing and restarting Operator, doesn't seem to help. The compiled version of the agent gives me the same error.

**Comment by xenoscr** [comment]
Ok, figured out my error. I guess maybe be prepared for a few questions on this. Or consider clarifying the documentation in Operator.

**Comment by privateducky** [comment]
Do you think a more clarifying error/notification would have helped?

**Comment by xenoscr** [comment]
The training content and the UI refer to the value that needs to be changed as the encryption key. The variable in main.go, that the tutorial talks about is called key, the variable in the cryptic.go is called SALT. The value in the GUI that actually matches the SALT is called the encryption key. In my mind I matched key to encryption key and not to salt. It was not until I read the light grey warning that it clicked that the value I needed to change was in the cryptic.go file.

I think that this section of the tutorial could do a much better job of calling out the process of downloading the source and tools required to complete it. I first searched my computer for the presence of the "main.go" file before realizing that I would have to download it separately. The documentation around this process could be covered in the agent documentation I think. You could call out where to get the source as well as discus the tools needed a bit. If this is truly to teach newcomers, there should be no assumed knowledge. Researching the answers is a great way to learn but you need to provide enough pointers for it to be effective or people will just give up and won't find value in it. If the experience is too frustrating, they won't keep trying.

**Comment by privateducky** [comment]
This is valid. I'm going to reopen and address.

**Comment by privateducky** [comment]
First part complete, where I renamed SALT to encryptionKey in the agent. This wording will be reflected in training as well (give it up to 30 minutes to show up):

https://github.com/preludeorg/pneuma/commit/308468d910fc48b43277c707973383c566232f1f
https://github.com/preludeorg/training/pull/53/files

Last remaining item on this ticket is to have a clearer error notification on mismatch of encryption key.

**Comment by privateducky** [comment]
OK final update made. Next minor release version will include a better error message for a mismatch of encryption key.
