### ISSUE TITLE
Editor: filter executors + platforms

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#300]
As a user, I'd like to filter out TTP executors I'm not immediately using, so that I'm not distracted by stuff I'm not interested in.

**Comment by lzimm** [comment]
the new editor introduces a different behaviour that tries to keep track of the executors you most recently viewed when tabbing between different files. furthermore, with the new tab behaviour, all but the active executor are effectively filtered by default, both of which combined should help address this issue a lot better than it is now.

**Comment by privateducky** [comment]
i'd say this ask is covered by the 1.2 design. i'll label as that. 

@VVX7 DM us if you'd like to trial the new Editor before 1.2 is released.
