### ISSUE TITLE
Ability to control compile time of Windows agent binary

### ISSUE THREAD

**Issue by kpsmiley23** [preludeorg/operator-support#310]
The agent's compile time requires a Windows Attack Surface Reduction rule exception when "Block executable files from running unless they meet a prevalence, age, or trusted list criterion" is in block mode

This is a minor hinderance as it won't trigger after 24 hours, but would allow for adhoc local testing without an ASR exception

**Comment by privateducky** [comment]
@khyberspache have you run into this / come up with any interesting work arounds?

**Comment by khyberspache** [comment]
@privateducky When I get around to building a version of "Builder" plugin for Operator (realtime payload compilation) this will resolve itself. 

In the mean time, we could have Outpost take a flag to only recompile Agents every X hours which would solve this at the source

**Comment by privateducky** [comment]
Cool; slowing down our Outpost compile frequency seems like an easy win. Hourly is fairly aggressive. Not a burning issue, so I'll let this one mull for a bit longer.

**Comment by sintax1** [comment]
+1 vote for a "Builder" plugin for Operator (realtime payload compilation). 

In addition to binary compilation, it would be nice to have for dynamic document generation using facts (e.g. phishing attachments).

**Comment by khyberspache** [comment]
@privateducky If we go the route of my Payload building service (supporting outpost + customer submitted builds) we can knock out this issue.

Plus then I get to build some cool infrastructure

**Comment by privateducky** [comment]
LOL. Yes, we most definitely will be doing work in this direction. I'd anticipate it being a Q2 initiative for us though, as we'll be ramping up our systems team in that time frame.

**Comment by privateducky** [comment]
@khyberspache given today's strategy on agent building, where do you think we stand on this ticket?

**Comment by privateducky** [comment]
@khyberspache bump on this. whatcha want to do?

**Comment by privateducky** [comment]
closing this ticket (no action)

I'm going to link this ticket to a generic one on our board, which should resolve this topic: https://github.com/preludeorg/operator-support/issues/450
