### ISSUE TITLE
Accessibility: Text visibility in the desktop app

### ISSUE THREAD

**Issue by alandixon** [preludeorg/operator-support#311]
Could we have some better contrast on the text in the windows desktop app please?
My sight is not that great and light grey on dark grey doesn't work well for me, I'm squinting to read it most of the time.
I know I can zoom to help things, but I also like lots of data on the screen.
At least some sort of high-contrast option would be useful; a few options would be great.
Thanks.

**Comment by khyberspache** [comment]
@alandixon Have you tried the theme changer plugin? You can change it to higher contrast white background with black text

**Comment by alandixon** [comment]
Ahh .. didn't know there was one, I only installed it today.
Yes, that's better, thanks.

**Comment by stephanwampouille** [comment]
Hey Alan, 

I wanted to follow up with you on this ticket and check if you are satisfied with ThemeChange? Please let us know if there are any other suggestions you may have that would improve your time with Operator!

@alandixon
