### ISSUE TITLE
Create a more flexible/powerful HTTP/S operator endpoint

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#316]
It would be nice to have a more flexible way to send HTTP requests to Operator's HTTP endpoint.  Ex:
* GET /tasks
* POST /results
* GET /module/{module_name}

keyword "malleable"

**Comment by privateducky** [comment]
The reason I've generally stayed away from typical REST API endpoint naming, for example GET /tasks, is that these tend to quickly get signatured and you need to swap it to something else, like GET /tasks-2, and you end up in a game of word changing. 

nothing wrong with that but I've kept it out of CALDERA and Operator (for the most part) for this reason and opted to use just a flat / root URL with a POST (more flexible on size) with the directions inside the (encrypted) beacon itself. 

now, this isn't proper API design - by a mile - but I have gotten better mileage out of it.

**Comment by khyberspache** [comment]
@privateducky to clarify a few things, the request here is to allow us to break up the components of the beacon into different formats.

Here's specifically what I want to do via Plugin:
1. Import a dirbuster list (https://github.com/daviddias/node-dirbuster/blob/master/lists/directory-list-2.3-medium.txt)
2. Have an "endpoint template" that lets you select what/how the beacons are formated
3. Assign common paths to those actions


So an example of what this would look like. Let's say I use `Wordpress.org` as the template:
* GET / (heartbeat/indicate it needs to hit a tasks endpoint) 
* GET /website-builder (instructions)
* POST /start/user?ref=website-builder-lp (results endpoint)
* GET /logo-maker/ (payloads)

**Comment by privateducky** [comment]
Nice, that makes a lot more sense (dynamic paths vs static). 

I could see eventually wrapping this into the network settings sidebar but great to prove this out in a plugins to start.

thx for the extra details!
