### ISSUE TITLE
Add payload upload button to sidebar

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#318]
When testing payloads it's easier to not have to tie them to ttps
![CleanShot 2021-08-20 at 14 32 06](https://user-images.githubusercontent.com/43142871/130278233-69af1eb3-d6af-4ec1-bfe1-6523cdb6c905.png)

**Comment by lzimm** [comment]
should have a new payload sidebar in our next release:

![image](https://user-images.githubusercontent.com/139388/133500137-72521239-4a41-46e9-b871-9cb7e775b34b.png)

**Comment by privateducky** [comment]
fancy!
