### ISSUE TITLE
Cannot import more than 1 plugin in sequence

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#32]
The file input/selection does not seem to clear after importing a plugin, disallowing multiple plugins from being imported manually in sequence.

**Comment by privateducky** [comment]
Resolved in 0.9.9.

**Comment by privateducky** [comment]
Actually - this is still open.

**Comment by lzimm** [comment]
i can't reproduce this anymore, seems to have been fixed in 0.9.11

**Comment by privateducky** [comment]
Cool. Very likely, given the plugin updates as of recent. Thanks for testing - closing.
