### ISSUE TITLE
Editor: search literal strings

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#321]
Quotation should enable literal string matching.  Right now "Copy NTDS.dit from Volume Shadow Copy" returns a bunch of results when it should only return TTPs that match the full string.

**Comment by privateducky** [comment]
Good point - we'll adjust.

**Comment by lzimm** [comment]
will be added to new editor here: https://github.com/preludeorg/plugins/commit/1427643ec2426746546d6dfed755d564d0c62450
