### ISSUE TITLE
Base64 generated for Obfuscated PSH appears wrong.

### ISSUE THREAD

**Issue by kwadner** [preludeorg/operator-support#328]
[dup: I posted this in the [wrong repository](https://github.com/preludeorg/pneuma/issues/84) originally.] 

I believe this is related to the issue outlines on this [ServerFault post](https://serverfault.com/questions/778123/powershell-executing-base64-commands-returns-error) where the base64 generated is incorrect.

The result output seen for the TTP is:
![image](https://user-images.githubusercontent.com/2546881/131410617-820c290c-8963-4696-bb5d-94749085d54a.png)

Executing this PSH directly, and then with the Base64 encoding method outlined in the ServerFault post can be seen below with the second, different base64, working correctly.

![image](https://user-images.githubusercontent.com/2546881/131410788-3c392e32-a6a6-49af-9321-fb36bf3c0954.png)

**Comment by privateducky** [comment]
We'll look to address this before version 1.2.

**Comment by privateducky** [comment]
@khyberspache tossing this ticket your way ahead of our QA cycle.

**Comment by khyberspache** [comment]
fixed here: https://github.com/preludeorg/operator/pull/1966

**Comment by privateducky** [comment]
in 1.2, we're going to push people toward Editor's "variant" feature, which is a duplicate way to achieve the same end result. we're trying to lower our surface area for duplicate "things" in 1.2. 

inside Editor, you can build TTP variants (such as base64) on the fly for all/some of your TTPs. this will allow you to more quickly create variants of encoding or other potential stealth modules we'd kicked around internally w/out relying on internal Operator implementations.
