### ISSUE TITLE
Toggle mode theme changer setting not remembered on Prelude restart

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#330]
I install the ThemeChange plugin and click "Toggle mode" to make the background white but every time I restart prelude it is back to a black background and I have to go click "Toggle mode" again.

**Comment by clr2of8** [comment]
Also, clicking "View->Reload" sets the background back to the default black as well.

**Comment by privateducky** [comment]
I can reproduce this one as well.

**Comment by privateducky** [comment]
Fixed and rolled out to production.
