### ISSUE TITLE
GUI to create a TTP not functional because "Select a Tactic" dropdown doesn't work.

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#331]
Prelude Operator v1.1. The select a tactic drop down doesn't let you select a tactic and it is required so you can't continue using the GUI interface to create your own TTP. When you pick a tactic, the text "SELECT A TACTIC (REQUIRED)" remains in the text box.

**Comment by clr2of8** [comment]
I restarted Operator and now the drop-down is working. If I figure out a consistent way to break it again, I'll let you know.

**Comment by clr2of8** [comment]
It seems to be a bug with the UI in general because I just clicked to add an adversary and I can't give it a name. I click on "Change Me" and it won't let me type anything. I click on "Add TTPs" and I can't type anything in the search bar. I go back to the original "Select a tactic" dialog in the editor and it is again broke. In fact, I can't type in any dialog in the app, not in "Settings", not to answer a question in the training, and so on. Going to "View->Reload" fixes it.

**Comment by privateducky** [comment]
@clr2of8 we haven't had this reported yet, which makes me suspect it's contained to a specific operating system. what OS/version are you on so we can test on that?

**Comment by clr2of8** [comment]
Host Name:                 art-vm0
OS Name:                   Microsoft Windows Server 2019 Datacenter
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00430-00000-00000-AA008
Original Install Date:     8/21/2021, 3:12:43 PM
System Boot Time:          8/31/2021, 1:39:33 PM
System Manufacturer:       Microsoft Corporation
System Model:              Virtual Machine
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 85 Stepping 4 GenuineIntel ~2095 Mhz
BIOS Version:              American Megatrends Inc. 090008 , 12/7/2018
Windows Directory:         C:\windows
System Directory:          C:\windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC) Coordinated Universal Time
Total Physical Memory:     4,096 MB
Available Physical Memory: 2,465 MB
Virtual Memory: Max Size:  4,800 MB
Virtual Memory: Available: 3,283 MB
Virtual Memory: In Use:    1,517 MB
Page File Location(s):     D:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\art-vm0
Hotfix(s):                 11 Hotfix(s) Installed.
                           [01]: KB5004335
                           [02]: KB4535680
                           [03]: KB4577586
                           [04]: KB4577667
                           [05]: KB4580325
                           [06]: KB4589208
                           [07]: KB5000859
                           [08]: KB5003711
                           [09]: KB5004424
                           [10]: KB5005112
                           [11]: KB5005030
Network Card(s):           1 NIC(s) Installed.
                           [01]: Microsoft Hyper-V Network Adapter
                        
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by privateducky** [comment]
Appears linked to: https://github.com/preludeorg/operator-support/issues/339

**Comment by privateducky** [comment]
closing, with linked PR.
