### ISSUE TITLE
Have to click on Plugin twice to get it to load

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#332]
Operator v1.1. Click on Plugins then click a plugin you already have installed (like ART or ThemeChange) and it just loads the screen that says "Plugins are a powerful way to extend Operator to meet ...." and you have to click the plugin again to get it to load.

**Comment by privateducky** [comment]
@clr2of8 i suspect this is linked to the 'create TTP' ticket you opened (https://github.com/preludeorg/operator-support/issues/331), as we haven't had a report of this yet (or ability to reproduce). if you pass along your operating system + version, we'll see if we can isolate the issue(s).

**Comment by clr2of8** [comment]
Host Name:                 art-vm0
OS Name:                   Microsoft Windows Server 2019 Datacenter
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00430-00000-00000-AA008
Original Install Date:     8/21/2021, 3:12:43 PM
System Boot Time:          8/31/2021, 1:39:33 PM
System Manufacturer:       Microsoft Corporation
System Model:              Virtual Machine
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 85 Stepping 4 GenuineIntel ~2095 Mhz
BIOS Version:              American Megatrends Inc. 090008 , 12/7/2018
Windows Directory:         C:\windows
System Directory:          C:\windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC) Coordinated Universal Time
Total Physical Memory:     4,096 MB
Available Physical Memory: 2,465 MB
Virtual Memory: Max Size:  4,800 MB
Virtual Memory: Available: 3,283 MB
Virtual Memory: In Use:    1,517 MB
Page File Location(s):     D:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\art-vm0
Hotfix(s):                 11 Hotfix(s) Installed.
                           [01]: KB5004335
                           [02]: KB4535680
                           [03]: KB4577586
                           [04]: KB4577667
                           [05]: KB4580325
                           [06]: KB4589208
                           [07]: KB5000859
                           [08]: KB5003711
                           [09]: KB5004424
                           [10]: KB5005112
                           [11]: KB5005030
Network Card(s):           1 NIC(s) Installed.
                           [01]: Microsoft Hyper-V Network Adapter
                        
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by clr2of8** [comment]
This is a "classroom" VM for student use. I can give you RDP access to it for debugging if you like.

**Comment by privateducky** [comment]
Ah, this is perfect. We can definitely do a round of testing on this setup. 

Getting RDP access would be perfect! If you can shoot me an email/DM with details, we can do a full round of UI testing this week and ensure we apply fixes ahead of our 1.2 release in 2 weeks.

**Comment by privateducky** [comment]
Appears linked to: https://github.com/preludeorg/operator-support/issues/339

**Comment by privateducky** [comment]
closing, with linked PR.
