### ISSUE TITLE
No notification received for Pneuma download

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#338]
Most of the time I go to the Agent Library and click on Pneuma Windows from my Windows server 2019 machine I never get any notification that something has downloaded and there is nothing in the text to indicate we should go look in c:\users\public to find it, so if we don't know to expect no output and to go look in C:\users\public then we are left confused.

**Comment by privateducky** [comment]
Do you get any notifications from Operator? Depending on your OS/settings, you may have notifications disabled for the app, which will silence them.

**Comment by clr2of8** [comment]
Sometimes ... This is a default win 10 install with default notification settings. It's the same as the test VM I provided to you so if you have a minute, can you try it out there?

**Comment by VVX7** [comment]
I'm able to reproduce this on my Win10 machine with default notification settings.

**Comment by privateducky** [comment]
re-labeling as a bug. we'll investigate before 1.2.

**Comment by privateducky** [comment]
@khyberspache do you have any thoughts? this seems to be in your area of expertise.

**Comment by sanoopsktm-git** [comment]
I have seen the agent is downloaded in to C:\Users\public folder < windows platform >

**Comment by privateducky** [comment]
Confirmed. We will be testing our built-in notifications (for things like agent downloads) on this platform. Look for an update next week, before our 1.2 release.

**Comment by privateducky** [comment]
This will be resolved in version 1.3.
