### ISSUE TITLE
Training bar covers the save button

### ISSUE THREAD

**Issue by bfuzzy1** [preludeorg/operator-support#34]
The training bar covers the save button preventing users from saving new TTPs in the editor. 

Going through the training indicated by the 3 dots at the bottom will uncover the save button and allow users to save new TTPs in the editor.

![image](https://user-images.githubusercontent.com/54591490/101808471-5cdeec80-3ae4-11eb-9da6-450cbdd7c528.png)

**Comment by privateducky** [comment]
Resolved in 0.9.9.
