### ISSUE TITLE
Replace PathToAtomicsFolder during ART import

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#341]
I see that during ART import, input arguments become global facts for all agents within Prelude Operator. Many of the default values for these input arguments include a "magic" variable called `PathToAtomicsFolder` or `$PathToAtomicsFolder`. It is intended that this be replaced with the path to atomics folder on disk and this path is supplied to Operator during the install. My request is that Operator replace the magic `PathToAtomicsFolder` variable for this path so at least this variable is functional for local execution. As it is now, these paths as imported are not usable.

**Comment by privateducky** [comment]
Specific request for who takes this ticket up:
- On the ART plugin, let's print out the key/values for each imported fact and give the user a chance to adjust them before flushing to disk/Operator.

**Comment by privateducky** [comment]
This will naturally fall under the work for this issue: https://github.com/preludeorg/operator-support/issues/342
