### ISSUE TITLE
Art plugin: avoid resetting changed facts

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#342]
If you import ART TTPs via the plugin, the facts are saved in the ART plugin's config.yml file (next to the plugin file on disk). Each time you restart Operator, these facts will be re-read into Operator.

If you then manually change one of these facts for an individual agent - and restart Operator - the ART plugin facts (original ones) will reload as normal but you'll end up with two facts instead of one.

Change requests:
- Show the ART command and ingested facts within the ART plugin's UI before importing them. Give the user a chance to modify the fact values. 
- Ensure the ART facts are shown on the page each time you enter the plugin, and the user can modify the values.
- Disable "plugin generated facts" from being modified in each agent's fact sidebar, similar to how we handle automatic facts.

**Comment by privateducky** [comment]
Note the linked issue, which this change request also encompasses: https://github.com/preludeorg/operator-support/issues/341

**Comment by lzimm** [comment]
what if instead we just kept things the way they were and didn't override the ART facts once they've already been loaded? so if you load the plugin, it initially writes all the facts that aren't there yet, then if you go to make a change manually the next time the plugin loads it'll see the fact(s) already there and not attempt to override them—unless you delete the fact(s) which will allow the plugin to then re-write that(those) individual key(s).

**Comment by privateducky** [comment]
that would only partially solve the issue.. couple of points it wouldn't cover:
- a user wants to change a specific fact/value for every agent before import (see the closed/linked ticket)
- a user imports ART, gets two facts (say art.one=123 and art.one=456). then they go in and delete art.one=123, then re-import ART, we'd have no way to determine which art.one facts they may want.

**Comment by privateducky** [comment]
The ART plugin has been updated. It will now display the input arguments within the plugin, and allow you to update them globally for all agents.

In version 1.3, Operator will disable the ability to manage ART facts from each agent sidebar, instead directing people to use the plugin.
