### ISSUE TITLE
Can't set python as last executor for ThirdEye Agent

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#346]
The Emulation course gives these instructions:

Change the order of the executors in your ThirdEye agent so either 'psh' or 'python' is last.

But if you put python last and then click update it just removes python as an unaccepted executor. You have to list psh last to pass this training question.

**Comment by privateducky** [comment]
We did not have the python executor attached to the Windows version of ThirdEye. I adjusted today and it'll be reflected in 1.2.
