### ISSUE TITLE
Protect beta-7 (Pink Badge) not authenticating 

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#348]
Our beta-7 version of Protect, which is part of the PInk Badge training program in Operator has been reported to not be authenticating (just spinning).

**Comment by privateducky** [comment]
OK, we've confirmed this issue is due to a missing dependency in the existing beta-7 build of Protect.

To fix this we must:
1. checkout the 1.1.0 Operator build
2. add the missing dependency to the package.json file
3. rebuild MacOS and Windows binaries for Protect
4. overwrite our beta-7 binaries we store in S3

**Comment by jpmoss** [comment]
https://s3.amazonaws.com/protector.versions/dist/prelude-protector-1.0.0-beta.7.dmg is ready and I tested it briefly. Can someone else download this and give it a go before broadcasting out that a new old beta is ready?

**Comment by stephanwampouille** [comment]
I downloaded and ran it, but it works. When I get back to school tonight I can send some chains and test those as well.

**Comment by privateducky** [comment]
cool. if you can validate:
- you can install it
- you can log in (use a new account)
- you receive the "ransom note" chain and can pass it
