### ISSUE TITLE
Dark theme tough to see on some monitors

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#349]
We've had a number of reports on some monitors where the grey-on-black font is difficult to see/read.

Let's look at new fonts, closer to white, which may offer better contrast.

**Comment by lzimm** [comment]
unfortunately because this is kinda spread all through the app its going to be something that we have to iterate on as we retouch different aspects of the UI over time. definitely noted though.

**Comment by privateducky** [comment]
@lzimm i want address at least parts of this before 1.3. we've had a few more reports come in, with similar asks (mostly around the grey-on-black font usage).

i did a quick scan of our CSS file and simply find-and-replacing #666 to #ccc brightens things up quite a bit. obviously, we can be more tactful with the change (to also include the react plugins) but a bit of tweaking here before 1.3 will go a long ways.
