### ISSUE TITLE
AppImage `chrome-sandbox` permissions incorrect on some linux distributions

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#350]
Need to fix chrome-sandbox permissions before packing the app image in the build pipeline.

Current work around commands:

```bash
./Operator.appImage --appimage-extract
sudo chown root chrome-sandbox && sudo chmod 4755 chrome-sandbox
./operate
```

**Comment by kpomeroy1979** [comment]
Not that you need to download the imagefile and run operator as a regular user and not root.

When you run ./prelude-operator-1.2.0-appImage --appimage-extract a new squashfs-root directory is created. Change to that directory first, and then change the owner to root and permissions as above. Then run ./operate as a regular user and your good to go.

**Comment by secdev-01** [comment]
I ran into this today , in our range with an older Kali distro.  I was able to get it to work with 
`./Operator.appImage --no-sandbox` likely not the best override, but it may help. 

But wanted to share in case it helps.

**Comment by privateducky** [comment]
thanks - it does - we'll be looking at solving this before our 1.3 release in the coming week.

**Comment by privateducky** [comment]
@jpmoss do you have any thoughts on this one?

**Comment by jpmoss** [comment]
So many thoughts! Also a PR submitted to address this during the build. Should be set for the next release, pending testing.
