### ISSUE TITLE
Try to parse output regardless of command status code

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#351]
There are situations where the status code will be non-zero, but a command worked. For example, finding recent files will throw some access errors, but still produce paths

**Comment by privateducky** [comment]
this used to be an issue with "dumb" parsers, such as ones which parse out each line as a fact. but now all our parsers are regex-based and "smart" so this should be a non-issue swap.

**Comment by khyberspache** [comment]
?

**Comment by privateducky** [comment]
originally, i wrote parsers in Caldera which parsed out each line of the output into an expected fact. for example, if this were the output:
```
/users/me/some.txt
/users/me/else.txt
``
each line would be parsed out as a file. this doesn't work when the output is:
```
could not find file or directory!
```
Because of this, I originally wrote protections around our parsers to only work when the link was successful. we're not doing these "line parsers" in Operator but I'd kept the same protection idea originally here as well, just because. However, our parsers are "smarter" than the original quick ones I wrote on Caldera, so we can parse all link output vs just the expected/success scenarios.

**Comment by privateducky** [comment]
@khyberspache this is now available in dev.
