### ISSUE TITLE
Editor: Add a filter by platform section to left hand column

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#354]

**Comment by privateducky** [comment]
You can use the search bar - but we've heard it isn't reporting all TTPs you search for with platform/executors.

**Comment by khyberspache** [comment]
Validating that searching for `linux` or `Darwin` doesn't provide all TTPs

**Comment by lzimm** [comment]
should be able to as soon as https://github.com/preludeorg/plugins/commit/e6c07217f3cd491d487ae5c7e261cde6febb7071 gets published, requires specialized search though `platform:linux` and `platform:darwin` should pick things up in each case respectively.
