### ISSUE TITLE
pneumaEX-windows agent installation

### ISSUE THREAD

**Issue by sanoopsktm-git** [preludeorg/operator-support#357]
Any reference guide to deploy agent on windows and Linux Server . 

I have  downloaded  and install on windows 2016 and its not reflected on Prelude Operator console.

**Comment by privateducky** [comment]
You'll want to check the README that comes with the downloaded ZIP. It'll be very similar to the normal Pneuma agent.

**Comment by khyberspache** [comment]
Pass the pneuma ex binary your target C2. 

`.\pneumaEX-windows.exe -address https://server:port -contact http`

**Comment by sanoopsktm-git** [comment]
@khyberspache  , Thank u , now I'm able to get the connection from Pneuma agent .
