### ISSUE TITLE
Would like to see Dependencies and Expected Outputs when viewing a TTP from the Operate menu

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#359]
This is currently only possible from the Editor menu

![image](https://user-images.githubusercontent.com/22311332/133286473-922b51e2-f030-4dea-b0cb-8cabbad8c539.png)

**Comment by privateducky** [comment]
You'll actually see a change, sometime between 1.2 and 1.3, where the Editor section will absorb the "Edit TTPs" button (on the home/Operate section). This will allow us to condense the editing of adversaries into one place, which should solve this. 

stay  tuned.
