### ISSUE TITLE
Protect formatting issue on Windows 10 Pro

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#361]
the_sensei on discord is having formatting troubles with protect beta 11 on his windows OS. He says 1/4 of the window is off screen. attaching his screenshot of this issue.

![image](https://user-images.githubusercontent.com/84744117/134704715-3a8bd1f8-1258-4546-a191-722c71f28ba6.png)

**Comment by privateducky** [comment]
cool desktop!

@stephanwampouille can you reproduce this on your Windows? @lzimm can you help remediate?

**Comment by lzimm** [comment]
hmm, it looks like that screenshot itself is even cut off, i haven't used windows in a while so forgive my ignorance, especially if i'm about to put my foot in my mouth, but shouldn't we see his windows try and the prelude icon that protect should be extending off of in the first place too?

**Comment by stephanwampouille** [comment]
Let me replicate - sorry I didn't see this earlier

**Comment by stephanwampouille** [comment]
Tested this on my windows. Looks like it has to do with changing the scale and layout setups on the laptop itself. Protect doesn't adjust for the change.

![Screenshot 2021-09-24 182316](https://user-images.githubusercontent.com/84744117/134746615-b16b671a-81e7-46eb-a927-336f8f4785c1.png)

![Screenshot 2021-09-24 182525](https://user-images.githubusercontent.com/84744117/134746650-8bf0d3fd-959f-4671-9054-9700ea7aebcb.png)

<img width="960" alt="Screenshot 2021-09-24 182639" src="https://user-images.githubusercontent.com/84744117/134746655-da356f4f-cd57-40e0-ba48-2cc5f2ccbaed.png">

![Screenshot 2021-09-24 182611](https://user-images.githubusercontent.com/84744117/134746663-945dcae9-a59c-4074-b3b1-9b55691b9666.png)

**Comment by privateducky** [comment]
we've got a fix in, this will be available in version 1.3.
