### ISSUE TITLE
Deleting adversary technique results from Operate view is inconsistent

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#363]
Deleting adversary technique results from Operate view often does not remove all results. I need to switch views, or load a different adversary profile, in order to continue deleting technique results.

Image shows the spinner 'working' after a couple minutes of no progress.

Expected bahaviour: the delete operation should remove all technique results for an agent at once.

![image](https://user-images.githubusercontent.com/46228229/134786897-4a4a7a26-3ec7-4646-8a46-e94f514ac81e.png)

**Comment by privateducky** [comment]
I haven't been able to repro this one specifically.. but i do know deleting large numbers of links can take a few seconds. we'll try and flush out what you're seeing.

**Comment by VVX7** [comment]
Using the Linux appImage on Ubuntu 20.04.  Deleting more than a dozen links consistently triggers this.  It's a different issue than the time delay while deleting.

**Comment by lzimm** [comment]
Interesting @VVX7, sorry about the slow follow up on this one. If you're seeing the spinner stay stuck there though that kinda hints to me at some sort of exception being thrown somewhere. so with that said, you don't happen to see anything in your console log when this happens, do you?

**Comment by VVX7** [comment]
No, nothing in console logs.

**Comment by lzimm** [comment]
Hmm, damn, thanks @VVX7, I'm assuming you're hitting the delete button on the right side of the screen here right?

![image](https://user-images.githubusercontent.com/139388/136080328-1ba55cc4-c4e1-4059-b00f-3d787ec0e903.png)

does it make a difference if you use the built-in thirdeye vs. an external agent?

**Comment by VVX7** [comment]
Oh, yeah. It works as expected with thirdeye. Hitting this issue with Pneuma/PneumEX.

**Comment by lzimm** [comment]
haha, alright, thanks dude, i'll try to dig into it and see.
