### ISSUE TITLE
Agent Beacon

### ISSUE THREAD

**Issue by ColeVan** [preludeorg/operator-support#364]
After reconfiguring my kali to reflect new IP the agent downloads will not change from 127.0.0.1 to correct beacon IP.

Is this a bug?

![image](https://user-images.githubusercontent.com/70167373/134814147-64e8c7a8-5c2c-46ab-aeae-504c4df7bff7.png)

**Comment by khyberspache** [comment]
You need to pass the flag: `-address ip:port` to pneuma when you start it
