### ISSUE TITLE
pneuma grpc broken in 1.2

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#365]
I'm unable to get the pnema/pneumaEX agents to connect via gRPC on Operator 1.2

![image](https://user-images.githubusercontent.com/46228229/134828620-67d2cc58-22ad-42fc-a14b-8d06313c2323.png)

**Comment by privateducky** [comment]
In 1.1, we removed gRPC as a built-in listening post and instead moved that to our collection of translators. 

A translator is any non-builtin listening post you want to use as a proxy to Operator (https://feed.prelude.org/p/can-you-hear-me-now). 

You can run translators manually, by downloading the Python script from the Community repository (payloads directory) or by choosing a translator in the Cloud plugin while deploying a redirector.
