### ISSUE TITLE
No agent source codes in new homepage AgentLibrary

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#366]
We have the supported OS agents but no source code available to download within Operator. Need to push the payloads.

**Comment by stephanwampouille** [comment]
@privateducky @khyberspache Not sure what your thoughts are but I feel like this may be an issue to prioritize

**Comment by privateducky** [comment]
Yep, I'd like to get this in for/ahead of 1.3. 

It should be a pretty easy add, on the Outpost side.

**Comment by stephanwampouille** [comment]
@khyberspache @privateducky bumping this for 1.3

**Comment by privateducky** [comment]
Yep, this is on the 1.3 list. If you are a current Pro customer looking for agent source code, head to Discord and jump in the professionals channel.
