### ISSUE TITLE
Include adversary UUID in data sent to remote/custom planners

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#367]
- Need the adversary UUID sent to the remote planner so that it is possible to resolve and discretely order TTPs

**Comment by privateducky** [comment]
I thought about this a bit yesterday. I'm going to add the operation property to the planning params, as that's part of the Link object (i.e., it is usable if you only have results to reference, not your Operator object model). This property can be used to look up any operation details, including adversary ID.

I'll likely add this this week. This will be a core change but we can make an ad-hoc patch plugin, for anyone who may want to use it now.
