### ISSUE TITLE
env Path isn't puling local users bash profile

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#368]
Ignoring the dino you can see the two different pathings for Operator and my local terminal. Per Alex: "The command lookup is performed using the options.env.PATH environment variable if it is in the options object. Otherwise, process.env.PATH is used." 

<img width="1349" alt="Screen Shot 2021-09-29 at 2 01 12 PM" src="https://user-images.githubusercontent.com/84744117/135510476-01e39566-4d5d-4411-b2fb-d0fb300ead48.png">

**Comment by privateducky** [comment]
closing. see linked PR for discussion.
