### ISSUE TITLE
Adversary/Technique access control

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#37]
I'd like to have some way to prevent accidentally running ATC's T1070.004 - "DELETE FILESYSTEM - LINUX".  Same for any other destructive/disruptive techniques like file cryptors, etc.

Off the cuff, including a technique id in the beacon would let users compile allowed ids in the agent to exclude  techniques at the agent level.

**Comment by khyberspache** [comment]
Adding the tag "destructive" to a technique will prevent it from being run until it's explicitly enabled. This we will be adding that tag block during the next release on Wednesday.

**Comment by khyberspache** [comment]
Also note, technique IDs are provided in the instructions that are sent from the C2 server to the agent. You can see details here: https://github.com/preludeorg/pneuma

Example instruction:
```
{
  ID: "067e99fb-f88f-49a8-aadc-b5cadf3438d4",
  ttp: "0b726950-11fc-4b15-a7d3-0d6e9cfdbeab",
  tactic: "discovery",
  Executor: "sh",
  Request: "whoami",
  Payload: "https://s3.amazonaws.com/operator.payloads/demo.exe",
}
```

**Comment by khyberspache** [comment]
If you're using the destructive tag on TTPs you will see this in the UI for editor:
![image](https://user-images.githubusercontent.com/43142871/102375005-fba99400-3f8f-11eb-946c-1aefe5f84323.png)

If you click enable you are prompted to confirm that you want to use a destructive TTP:
![image](https://user-images.githubusercontent.com/43142871/102375061-0cf2a080-3f90-11eb-99ae-27090351474f.png)

If you enable the TTP and add it to an adversary, you will see:
![image](https://user-images.githubusercontent.com/43142871/102375122-2267ca80-3f90-11eb-83ff-b56ccf73c05b.png)

**Comment by privateducky** [comment]
The solution above is now deployed into 0.9.9. Let us know if there are any adjustments you'd like to see. Thanks!

**Comment by privateducky** [comment]
Closing with solution in place. Please re-open if necessary.
