### ISSUE TITLE
Add colour blind safe and high contrast themes

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#374]
This tool from Adobe helps create colour blind friendly palettes.
https://color.adobe.com/create/color-accessibility

The same tool can be used for showing contrast ratio between colours.  A ratio of at least 4.5:1 is ideal for high-contrast text.
https://color.adobe.com/create/color-contrast-analyzer

**Comment by privateducky** [comment]
The theme change plugin is now dead. We have made the theme in 1.4 much brighter - and 1.5 will continue this trend of making things more accessible.
