### ISSUE TITLE
Have to restart app to switch back to dark mode

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#375]
with the ThemeChanger plugin I enter `C:\Users\art\Downloads\light.css` and it changes to the light theme, but then I choose "Default (dark)" from the "Pick you theme" dropdown and it doesn't change back to dark until I close and reopen the app or press Ctrl+R

**Comment by stephanwampouille** [comment]
Can confirm that you cannot switch back and forth between light and dark themes without restarting. I also noticed that the light.css theme that I imported kept getting deleted once I restarted the app. I took these steps:

- Import the light.css theme, which will activate it
- Clicking back and forth between light and dark(default) will not switch them.
- Click default dark theme and restart app (Ctrl R)
- Dark theme would return but light.css theme would be deleted, and I would have to re-add through import.

**Comment by privateducky** [comment]
ok - this might be another good screen-share one w/you and @lzimm
