### ISSUE TITLE
Splitting ART plugin in technique categories

### ISSUE THREAD

**Issue by CT-H00K** [preludeorg/operator-support#380]
Hi, 
I was wondering if it would be possible to split the ART plugin in technique sub-categories like discovery, credential-access, privilege escalation etc. 

Since right now it's just a long list of TTPs, and it's kind of hard to find the techniques for e.g discovery in it, if the technique number is not known. 

Also it would be easier to create custom adversaries by category.

**Comment by privateducky** [comment]
Absolutely! I've been wanting to do that myself for awhile. 

If you're comfortable with JavaScript - and want to take a stab at solving this, you can find the plugin code here online: https://github.com/preludeorg/community/blob/master/plugins/ART/ART.html

It's something that we'll definitely circle on - but if you/someone else solves it first, we'll likely merge it.

**Comment by CT-H00K** [comment]
Sorry I'm not really good in Javascript, but the information is already in the YAML file. So for an experienced Javascript developer it would be much quicker to solve. 

The part should be here, not going over data.atomic_tests.Each but over data.Each and checking if atomic tests are not empty, I guess. 
https://github.com/preludeorg/community/blob/757e9805119fd34f15a1e53d16f76616224247f5/plugins/ART/ART.html#L105-L115

**Comment by privateducky** [comment]
perfect. we'll definitely circle on this!

**Comment by privateducky** [comment]
If possible, try and knock out this at the same time while we're in the plugin code:
https://github.com/preludeorg/operator-support/issues/381
