### ISSUE TITLE
Operator not receiving results from windows HTTP agent

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#383]
What happens:
- Tasks go to agent, are executed, responses are never collected

OS:
- Operator on linux
- Agent on windows

Repro:
1. Build this adversary:
<img width="228" alt="CleanShot 2021-11-09 at 08 34 39@2x" src="https://user-images.githubusercontent.com/43142871/140933458-859b4376-26bc-4feb-9d8e-28db15a025e6.png">
2. Deploy redirector and switchboard from Linux
3. compile and build fresh agent, connect through redirector using HTTP
4. deploy against HTTP agent

<img width="812" alt="CleanShot 2021-11-09 at 08 36 20@2x" src="https://user-images.githubusercontent.com/43142871/140933661-adbed868-ae2a-4a81-aa11-9237e63e378c.png">
<img width="1427" alt="CleanShot 2021-11-09 at 08 36 40@2x" src="https://user-images.githubusercontent.com/43142871/140933699-b4aa7266-1488-4da2-9763-c767e82c9722.png">

**Comment by privateducky** [comment]
@stephanwampouille can you test this on latest master code to see if it'll be an issue in 1.3 or if we resolved it?

**Comment by khyberspache** [comment]
Removing `List local active services` makes everything run perfectly

**Comment by khyberspache** [comment]
Root Cause: Express payload size exception

**Comment by stephanwampouille** [comment]
Tested the original chain that was included in the first post. I got the following results which has killed my redirector connection and frozen it from connecting again. This was tested on master code.
<img width="1113" alt="Screen Shot 2021-11-09 at 9 02 50 PM" src="https://user-images.githubusercontent.com/84744117/141036162-5bd5590f-92ab-442e-ab73-17db727c43b1.png">
<img width="1345" alt="Screen Shot 2021-11-09 at 9 03 21 PM" src="https://user-images.githubusercontent.com/84744117/141036163-905472f9-fd8c-426d-8cb1-37ed6b9b6c9e.png">
.

**Comment by stephanwampouille** [comment]
I deployed that chain onto the linux VM agent connected through tcp and got this:
<img width="1103" alt="Screen Shot 2021-11-09 at 9 35 37 PM" src="https://user-images.githubusercontent.com/84744117/141039295-f20b02cb-dcce-4dad-ac0f-db4dc79f98bf.png">

**Comment by privateducky** [comment]
this has been resolved through a patch + an update to Pneuma. Marking as solved in 1.3.
