### ISSUE TITLE
Requesting non-existing payloads hangs agents and throws unhandled error

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#384]
<img width="882" alt="CleanShot 2021-11-09 at 09 18 31@2x" src="https://user-images.githubusercontent.com/43142871/140940684-8bbfb268-29ba-4ef6-a01a-c10459d7a992.png">

**Comment by privateducky** [comment]
Confirming: this is the agent requesting a missing payload, which Operator then looks for and throws the above exception, right?

**Comment by khyberspache** [comment]
yes

**Comment by privateducky** [comment]
@stephanwampouille can you try this in master to see if we resolved it in 1.3? 

we made updates in this area but i don't think anything that would have fixed this particular bug - but it'd be good to check first.

**Comment by stephanwampouille** [comment]
Testing in 1.3 throws only the following error:
I didn't get the unhandled error.
<img width="1102" alt="Screen Shot 2021-11-10 at 11 22 14 AM" src="https://user-images.githubusercontent.com/84744117/141151693-2b1032a7-2a11-4921-ba57-26afb1350b3a.png">
:

**Comment by privateducky** [comment]
@lzimm can you check on this one?

**Comment by lzimm** [comment]
@stephanwampouille how did you trigger that? did you manually specify a payload that not only doesn't exist locally, but doesn't exist AT ALL, and then it fails expectedly when we try to download when hitting outpost? as opposed to just downloading one that SHOULD exist but doesn't?

**Comment by lzimm** [comment]
btw @stephanwampouille @privateducky this error seems handled:

```
                app.route('/payloads/:file(*)')
                    .get((req, res) => {
                        const fileName = req.params.file.replace(/^(\.\.(\/|\\|$))+/, '');
                        const filePath = Listen.resolvePayloads(fileName);
                        if (filePath?.length) {
                            fs.readFile(filePath[0], (err, data) => {
                                res.writeHead(200, {'Content-Disposition': `attachment; filename="${path.basename(filePath[0])}"`});
                                res.end(Encryption.decryptBuffer(data));
                            });
                        } else {
                            new Promise((resolve, reject) => {
                                if (Listen.payloadCache[fileName]) {
                                    resolve(Listen.payloadCache[fileName]);
                                } else {
                                    return Requests.hq.getPayload(fileName).then(res => {
                                        if (res.status === 200)
                                            return res.blob();
                                        reject()
                                    })
                                    .then(blob => blob.arrayBuffer())
                                    .then(data => {
                                        resolve(Listen.payloadCache[fileName] = data);
                                    })
                                    .catch(reject);
                                }
                            })
                            .then(data => {
                                res.writeHead(200, {'Content-Disposition': `attachment; filename="${path.basename(fileName)}"`});
                                res.end(Buffer.from(data));
                            })
                            .catch(err => {
                                res.statusCode = 404;
                                res.send("File not found.");
                            });
                        }
                    });
```

note the catch at the end, and even though the downloads fail, everything keeps running fine.

**Comment by stephanwampouille** [comment]
I ran the following piece of code from a shell: `curl http://localhost:3391/payloads/doesnotwork/missing.exe`

**Comment by lzimm** [comment]
yeah, looks like that behaves as expected
