### ISSUE TITLE
Add paywall filter to Editor

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#385]
Need a toggle to remove all the paywalled TTPs from editor.

![image](https://user-images.githubusercontent.com/43142871/141467232-8afc812c-4f31-4c89-841c-6aa860f4e09a.png)

**Comment by privateducky** [comment]
@lzimm @ptiglias noted this last week on our 1.3 dev build as well. can you check if we lost the filter somewhere?

**Comment by privateducky** [comment]
marking this as a 1.3 blocking ticket (we won't release until it's solved)

**Comment by lzimm** [comment]
this got removed on purpose (via unanimous discussion) a few months ago, regardless, adding back here: https://github.com/preludeorg/plugins/commit/90c377670ba9ff018c232db3b3b13bebddda5186

**Comment by privateducky** [comment]
:) I feel like this is the element none of us can remember what to do with
