### ISSUE TITLE
QA Conti (Discovery)

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#386]
Tested on windows laptop. Wasn't able to test WORKGROUP or DOMAIN functionalities as my computer is not apart of either.
----
1. Syntax error result
![image](https://user-images.githubusercontent.com/84744117/142059677-52f5d873-03cb-4a2f-bcba-790eea6d9a80.png)
----
2.Antivirus pickup while deploying against thirdeye but not pneuma
![image](https://user-images.githubusercontent.com/84744117/142060023-37a69c95-ece8-47af-af4b-63a2785e0fcd.png)
----
3.Dumping error for thirdeye on both 'DUMP HASHES FOR KERBEROASTABLE ACCOUNTS TO DISK' and 'DUMP ACCOUNT HASHES USING AS-REP ROASTING'. Both actions came back as green thinking it was successful. Also if run against pneuma you get proper results and error messages (ie for domain dumping because I am not in one)
![image](https://user-images.githubusercontent.com/84744117/142060274-4e50210b-073b-4eda-80e6-7a8abd051b4f.png)
----
4. Odd result and picking up weird facts when running against pneuma.
![image](https://user-images.githubusercontent.com/84744117/142060676-5540485e-3aed-42d4-aea9-1bd8efcb1878.png)
![image](https://user-images.githubusercontent.com/84744117/142060789-7a525283-5aa6-4a6a-80ca-0661d465aba3.png)
----
5. This hangs while running against pneumaEX
![image](https://user-images.githubusercontent.com/84744117/142066763-6cb73f9b-c696-4f44-87be-b7a17697490f.png)
---
6. 'Enumerate User and Domain' fails against pneumaEX
---
7. No results for this one on pneumaEX, works on thirdeye and pneuma
![image](https://user-images.githubusercontent.com/84744117/142066960-7721bbf5-e3c6-456e-8ad0-f611ad28717f.png)

**Comment by stephanwampouille** [comment]
Also for the antivirus pickup. My windows firewall and defender is turned off...

**Comment by bfuzzy1** [comment]
> Also for the antivirus pickup. My windows firewall and defender is turned off...

Your step 2 is AMSI, which should work even with Defender turned off.

**Comment by khyberspache** [comment]
Verifying several of these TTPs need to be fixed.

**Comment by khyberspache** [comment]
https://github.com/preludeorg/professional/pull/161/files
