### ISSUE TITLE
QA Kaseya VS Attack Chain

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#388]
Tested on windows laptop using pneuma, pneumaEX, and thirdeye. Was not able to see this chain through

Succesfully stages agent config file and creates staging directory then hangs on the following TTPs that remain executing without change:
![image](https://user-images.githubusercontent.com/84744117/142089316-bfa0f58e-6348-466a-b2aa-062847030f9a.png)
---
Leaves these 3 on queue waiting.
![image](https://user-images.githubusercontent.com/84744117/142089134-32dbbf7f-d7c8-4983-a269-1e2b71955320.png)

**Comment by khyberspache** [comment]
You need to check the chains website for manual facts you need to specify

**Comment by stephanwampouille** [comment]
thanks @khyberspache , that was an oversight by me. closing as it works without issues
