### ISSUE TITLE
QA Staging Server (WIP)

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#390]
1. No executors for windows, should update its 'global' use on chains.prelude.org
---
2.

**Comment by khyberspache** [comment]
global is available for the client side component of it

**Comment by privateducky** [comment]
Not sure I'm tracking here: @khyberspache are you saying that global is listed in Operator but not chains.prelude.org for this chain?

**Comment by khyberspache** [comment]
We globally support "bash" for some of these TTPs, so it shows up on chains website as global.

This chain consists of a server & client side. I will break them out into separate chains this week for the release

**Comment by privateducky** [comment]
gotcha - great!

**Comment by khyberspache** [comment]
I used staging server regularly, so this is g2g from my side

**Comment by stephanwampouille** [comment]
My only issue with this one is still the same. It gets skipped entirely on windows, and on the chains.prelude website the platform is indicated as global.

**Comment by privateducky** [comment]
@khyberspache update on this ticket?

**Comment by privateducky** [comment]
@khyberspache bump on this topic.

**Comment by privateducky** [comment]
@khyberspache what's our status here?

**Comment by khyberspache** [comment]
@privateducky We're looping this into our re-do of all of the chains. I'm going to close this
