### ISSUE TITLE
Operator 1.3 crashes on Windows

### ISSUE THREAD

**Issue by tr4cefl0w** [preludeorg/operator-support#391]
This occurred when running Operator following the upgrade.

![image](https://user-images.githubusercontent.com/39302712/142667840-1355dba0-735e-4ac4-a5f9-083f45d9c50d.png)

Crashes then exits.

**Comment by khyberspache** [comment]
Looking into this

**Comment by khyberspache** [comment]
I can replicate 
<img width="539" alt="CleanShot 2021-11-19 at 12 58 15@2x" src="https://user-images.githubusercontent.com/43142871/142669527-c46da9a8-f354-461b-993f-7feb0ef9c8f8.png">

**Comment by privateducky** [comment]
The Windows build that went out last night was corrupted - we've rectified this now, so if you pull a new copy from https://www.prelude.org/download/current it should work fine. 

If you wait a few minutes, you'll see a new 1.3.1 version being pushed up to the site. We're rolling in a few patches we noticed on edge cases for 1.3.0.

**Comment by privateducky** [comment]
fixed now
