### ISSUE TITLE
Operator 1.3.0+ slow to boot up

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#392]
We noticed a significant slow down in how long it takes the app to start in version 1.3.0 and 1.3.1. This seems sporadic and we're not sure which operating systems it is occurring on yet. 

When clicking into the Plugins section, it is also quite slow, which is likely related.

We are currently investigating.

**Comment by privateducky** [comment]
Update: we've made some back end changes to make Operator faster than 1.2 on boot, these will get deployed in patch version 1.3.3 this week.

We're investigating one more potential win in this area before pushing the patch, through the use of electron-link and/or V8 snapshots. 

More to come.

**Comment by tr4cefl0w** [comment]
Updated to the latest and it fixed the issue. Thanks!

**Comment by privateducky** [comment]
Perfect! I'll close this ticket once 1.3.3 comes out (today or tomorrow, hopefully). This update will improve the start up experience dramatically.
