### ISSUE TITLE
Recommendations not showing the chain which generated it

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#394]
Run the "ransom note" chain and you'll get 1 chain recommendation in Reports. It appears empty, on the TTPs which generated the recommendation. 

<img width="1335" alt="Screen Shot 2021-11-19 at 3 54 25 PM" src="https://user-images.githubusercontent.com/49954156/142690999-20cdcc6d-4fb6-4a80-9245-3c8e67534611.png">

**Comment by lzimm** [comment]
@privateducky this should have been fixed with one of the other result bugs, works fine for me now:

![image](https://user-images.githubusercontent.com/139388/142935293-d03352a4-b152-4be5-9eba-f7762873b983.png)

**Comment by privateducky** [comment]
perfect. marking as 1.3.3 bug fix.
