### ISSUE TITLE
Duplicate redirector agent custom facts

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#398]
I was connected to my agent via redirector.

Reprod:

Create a custom fact, in this scenario I used chisel.port
- Enter in the key and value, then have it save. 
- Go back into it clicking only into the value and editing it and ensuring it saves once more.
- Open the facts and see the both the original and new one.

**Comment by lzimm** [comment]
this looks like nothing to do with redirectors, can reproduce locally
