### ISSUE TITLE
When results are parsed, the file parser returns false positives

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#40]
Here is an example output:

![Screen Shot 2020-12-16 at 1 54 40 PM](https://user-images.githubusercontent.com/49954156/102393391-4d5d1900-3fa6-11eb-989a-a191d06da206.png)

**Comment by khyberspache** [comment]
I think I fixed this

**Comment by privateducky** [comment]
ooh, just saw this. gonna keep an eye out over the coming days.
