### ISSUE TITLE
Updating modified TTPs from Editor throws a console error

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#400]
<img width="1816" alt="Screen Shot 2021-11-22 at 11 28 59 AM" src="https://user-images.githubusercontent.com/49954156/142898740-7faa8af1-1e5c-43f2-a005-9cdb6bb97412.png">

**Comment by lzimm** [comment]
should be patched here:

https://github.com/preludeorg/plugins/commit/ee97338e028f8ef23cf9761cf52582a227af9bb8

**Comment by privateducky** [comment]
perfect, closing down as this'll be out in just a few minutes.
