### ISSUE TITLE
Importing modified prelude TTP in editor hides delete button

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#401]
<img width="1512" alt="CleanShot 2021-11-22 at 11 32 20@2x" src="https://user-images.githubusercontent.com/43142871/142899160-59994a57-8866-4b11-ba7e-d013a37460a3.png">

Repro:
1. Export any Prelude TTP
2. Change UUID & name (add `test`)
3. Import TTP
4. Cannot delete TTP

**Comment by lzimm** [comment]
this is because the way we check if a TTP is a prelude TTP is via the `license` field inside metadata: we don't allow deletes of any licensed TTPs, as a proxy for not deleting prelude TTPs (which we do because they'll just be auto-updated on restart)

**Comment by lzimm** [comment]
ie: remove the license from the TTP and you can delete, unfortunately this needs to happen pre-import.

**Comment by lzimm** [comment]
fixed here to use `/stockpile` as our source of truth instead:

https://github.com/preludeorg/plugins/commit/2d000c548dd7703d99f7eb8b686eb96585535849
