### ISSUE TITLE
Enable chains to use specific facts or TTP variants

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#402]
Many chains require users provide facts to use we provide a few default values in the chain definition. 

https://chains.prelude.org/chains/sharphound

has: `payload.uri: /discovery/bloodhound/SharpHound.exe`

it would be better if I could provide default values directly in the syntax of a ttp. For example:

```yaml
$url="#{operator.payloads}#{payload.uri:"/discovery/bloodhound/SharpHound.exe"}";
```

**Comment by privateducky** [comment]
Instead of:
```
$url="#{operator.payloads}#{payload.uri:"/discovery/bloodhound/SharpHound.exe"}";
```
why not just:
```
$url="#{operator.payloads}/discovery/bloodhound/SharpHound.exe"}";
```
If you're confident in the fact value, I'd probably just create this as the first variant of the TTP.

**Comment by khyberspache** [comment]
This is way more nuanced than you might think, I'll try to explain what I'm encountering.

So I have 2 separate chains:
1. Sharphound (https://chains.prelude.org/chains/sharphound)
2. Vulnerable Certificates (https://chains.prelude.org/chains/vulnerable-certificates)

Both chains leverage the same first 2 TTPs:
1. Create an XOR byte - this works fine, chain independent
2. Ingress payload to XOR'd file - this does not work fine, chain independent

Right now both of those chains require that you manually specify a `payload.uri` value of either:
1. /discovery/certify/Certify.exe
2. /discovery/bloodhound/SharpHound.exe

So the TTP layout is basically such at that Primary command uses a `payload.uri` while variant 1 uses Sharphound and variant 2 uses Certify. The "Real" ask is:
Can we make it so that variants can be tied directly to chains and have the planner know to use that variant instead of waiting for the primary (blocked) TTP? 

Realistically any other payload using this ingress methodology will scale this problem further.

**Comment by privateducky** [comment]
ah, glad you provided this example - that helps showcase what you're problem set is. 

we're tracking a few other parallel areas with TTP order and extending planner blueprints into variants. this ticket would be good to match up with those for a more holistic approach to whatever we implement across these areas. 

will keep this ticket updated as we look at this.

**Comment by privateducky** [comment]
@khyberspache I believe our 1.5 variant strategy - which wasn't intended to solve this ticket in particular - may end up addressing it. 

In 1.5, you'll be able to define a chain like this (snippet):
```
name: Ducky's Fancy Adversary
ttps:
  - 4e97e699-93d7-4040-b5a3-2e906a58199e
  - 90c2efaa-8205-480d-8bb6-61d90dbaf81b:windows:psh:0
  - 6469befa-748a-4b9c-a96d-f191fde47d89
  - 300157e5-f4ad-4569-b533-9d1fa0e74d74:darwin:sh:1
```

Read: TTP identifier (for usual handling) or include platform:executor:variant (0=top level) to specify an exact match to use.

**Comment by khyberspache** [comment]
ooooh interesting
