### ISSUE TITLE
supported chains for TTPs not showing in editor

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#403]
<img width="1395" alt="Screen Shot 2021-11-22 at 4 40 40 PM" src="https://user-images.githubusercontent.com/84744117/142939565-7f108673-fae8-44a3-bb4d-351d7b9f8c02.png">

**Comment by stephanwampouille** [comment]
this one is part of training

**Comment by lzimm** [comment]
that one isn't part of any chains: https://github.com/preludeorg/community/blob/master/ttps/exfiltration/ea713bc4-63f0-491c-9a6f-0b01d560b87e.yml

someone's gotta make that wire correctly if that's an ommission

**Comment by privateducky** [comment]
:) I think that's what the bug is

it should be part of a few, last I knew. it should be referenced on this object in results_svc, which == our Operator chain clusters:
```
self.technique_chains = dict()
```

**Comment by lzimm** [comment]
lol, no i mean the ttp itself doesn't have any chains specified in the metadata

**Comment by privateducky** [comment]
ah, you're (understandably) mixed up: the chain clusters are essentially "potential chains" not existing ones. They aren't read from the TTPs - but are instead generated dynamically from the ATT&CK Procedures program and stored on HQ's technique_chains dictionary. 

When you click on chain clusters from Editor, you're essentially checking this dict to see if there are any good ways to combine this procedure with others in your system to create a chain.

**Comment by lzimm** [comment]
oh wow this changed around completely

```
    async def get_adversary_chains(self, procedures) -> dict:
        try:
            adversary_chains = dict()
            for chain in [c for chain in self.get_service('results_svc').technique_chains.values() for c in chain['chains']]:
                technique_procedures = dict()
                for technique in chain:
                    matches = [i for i, ttp in procedures.items() if ttp['technique']['id'] == technique]
                    technique_procedures[technique] = matches
                for v in list(itertools.product(*technique_procedures.values())):
                    adversary_chains[self.md5_encrypt(','.join(v))] = list(v)
            return adversary_chains
        except Exception as e:
            self.log.error('Error getting adversary chains: %s' % e)
```

how is this even supposed to work? do i need to pass in my entire attack DB now?

**Comment by lzimm** [comment]
note: the endpoint we used to use for this before got changed a long time ago and i have no idea what the original logic was supposed to be doing

**Comment by lzimm** [comment]
nm, i think i'm just going insane

**Comment by lzimm** [comment]
can someone give me a spot check on what they THINK is supposed to get picked up for the file.io exil TTP?

**Comment by privateducky** [comment]
This isn't perfect but you should see something to this effect.

For example (first line of output), file.io should get scooped up with all combos of T1074 and T1002 procedures (since file.io is a T1041).
```
(T1074|T1002|T1041)
```

<img width="907" alt="Screen Shot 2021-11-22 at 6 45 33 PM" src="https://user-images.githubusercontent.com/49954156/142951505-7400106a-f17f-4a9e-9f52-c5b4d5e8771e.png">
