### ISSUE TITLE
Dates Not Sorted Properly in Operate Tab

### ISSUE THREAD

**Issue by bwhack16** [preludeorg/operator-support#404]
The dates are not being sorted in order in the operate tab:
![image](https://user-images.githubusercontent.com/42819634/143132224-e74b80c2-ef9b-4f1b-9785-065144d3e4a1.png)

**Comment by privateducky** [comment]
were you running through a redirector by chance? curious if time diffs between local/remote machines is causing this.

**Comment by bwhack16** [comment]
Yeah, all of the procedures were run through a redirector.

**Comment by privateducky** [comment]
perfect. this will help identify the solution.
