### ISSUE TITLE
Cannot deploy TTPs through editor when agent is through Connect Redirector

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#406]
<img width="466" alt="CleanShot 2021-11-23 at 16 32 49@2x" src="https://user-images.githubusercontent.com/43142871/143132638-db2f023e-ddb3-4faf-927b-97b6a5269108.png">
<img width="272" alt="CleanShot 2021-11-23 at 16 34 05@2x" src="https://user-images.githubusercontent.com/43142871/143132713-9e9fcfed-00b0-43cb-b8a9-a67c7004d43d.png">

**Comment by lzimm** [comment]
this was intentional to limit our surface area of things to go wrong. once we burn in redirectors a little more we'll look at re-enabling that, as there were a few little quirks that made things a little awkward (specifically around tracking instructions being completed)
