### ISSUE TITLE
Changing operator IP to 0.0.0.0 crashes 'Connect' and 'Editor' on Windows

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#407]
Per @bartimus on discord:
Changing the Operator IP address within network settings to 0.0.0.0 will cause both 'Editor' and 'Connect' to crash. Clicking on them with hang indefinitely and both icons will disappear entirely upon restarting Operator.

console log after clicking into either plugin:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/84744117/143604293-269ef85b-d67e-485a-a9f2-68b6a2083b00.png">
---
console log after restarting Operator:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/84744117/143604403-9654557c-0fc1-4685-b688-a1da2e65973e.png">
---

**Comment by privateducky** [comment]
We've had a report of this on Mac as well. 

We will have a fix in place for 1.4 but if anyone needs a patch ahead of time, just let us know.

**Comment by privateducky** [comment]
this is still open
