### ISSUE TITLE
Add Chains to the Editor side navigator

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#408]
I can't search directly for chains by name in Editor have it reliably pull the chains. The new Operate section makes it impossible to see what the actual TTPs are or enable me to make edits.

I need to make modifications to chains as a whole and there is no way to do it in editor effectively

**Comment by khyberspache** [comment]
@privateducky talked to Lewis. My current ask is add the Chains to the left hand sidebar and make the top-level (chains, tags, tactic) collapsible

**Comment by privateducky** [comment]
yep, that's what I'd want as well.

**Comment by privateducky** [comment]
**Update**: This is still a pre-1.4 priority item for us. We've made some major updates to the Operate section, related to searching/viewing of adversaries and chains. The last piece to this puzzle is the incorporation into the Editor section which we'll be working on next.

**Comment by privateducky** [comment]
@lzimm before we move our current dev iteration of this into prod (i.e., list the chains like the adversaries) we should formulate a plan for how this area will expand with 1+ chains per week. We can likely get ahead of it by creating a sub-menu on the left sidebar for chains, where they're organized first by release MONTH/YEAR, then names.
