### ISSUE TITLE
Payloads should not be showing up in Provision Virtual Machine

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#409]
These payloads should not be showing up:
* Install chisel
* execute assembly
![CleanShot 2021-11-29 at 13 53 42](https://user-images.githubusercontent.com/43142871/143926102-32ce53bc-60e8-4f3a-8ead-4fc44bae001c.png)

**Comment by privateducky** [comment]
@lzimm are these payloads marked as redirector purpose by chance?

**Comment by lzimm** [comment]
I have no idea tbh. Obvious fix right :P

**Comment by privateducky** [comment]
> I have no idea tbh. Obvious fix right :P

yep - that stands to reason!

**Comment by privateducky** [comment]
This should self-heal in about an hour. @stephanwampouille can you confirm and close this if that's the case?

**Comment by stephanwampouille** [comment]
Can confirm I am only seeing vulnerable.sh! Closing!
