### ISSUE TITLE
AgentLibrary plugin should include .exe extension when downloading

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#41]
When using the plugin to download a Windows executable, it should include the .exe extension.

**Comment by khyberspache** [comment]
This should be fixed on the build/server side when the `pneuma` agent is constructed.  We just need to add `.exe` to the `-o` in the `build.sh`

**Comment by privateducky** [comment]
This will be released in v0.9.10

**Comment by privateducky** [comment]
Closing with solution in place. Please re-open if necessary.
