### ISSUE TITLE
Planner plugin missing dependency 

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#410]
Planner plugin throws console error about missing "express" library. 

<img width="1168" alt="Screen Shot 2021-11-30 at 8 44 08 AM" src="https://user-images.githubusercontent.com/49954156/144058421-88ccb928-aeaa-4b33-bc8a-59c99a3e3475.png">

**Comment by lzimm** [comment]
my bad, should be patched here: https://github.com/preludeorg/professional/commit/44e2215d926c2b12cd4983d663e167558442bf7c
