### ISSUE TITLE
Enable cross-range fact injection

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#411]
What I'm trying to do:
1. Launch Windows agent on Red range
2. Launch Chisel Server on system in Cloud range
3. Inject fact (`chisel.server: http://ec2-address:8443`) from Cloud agent/range into Red range
4. Red range agents use `chisel.server` fact to launch `chisel client` connection back to Cloud range server

**Comment by privateducky** [comment]
@khyberspache refresh my memory: did you end up with a solution for this?

there are a few ways to accomplish this type of cross-range/global fact usage, with the question being which is the most natural way to do it.. I do want to consolidate a "global" fact usage inside the app which is likely the most natural way to handle this sort of thing in the future though. 

Depending on your answer, I may convert this ticket into a "consolidate global facts within Operator" type of action item.
