### ISSUE TITLE
Fluently transition account icon

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#415]
Upon startup of Operator there is the following transition of account icons, which I think we should look at doing better
https://user-images.githubusercontent.com/84744117/145253507-c397b55e-3c57-4e0e-a7ef-47b3d6b7d20b.mov

**Comment by privateducky** [comment]
@stephanwampouille the link here isn't rendering for me. 

Is this ticket referring to the weird-looking icon when you first open Operator? Like how it expands/contracts on load?

**Comment by stephanwampouille** [comment]
@privateducky Oh i attached a video showcasing it, but no. Trying to reproduce now I can't so I might have been a little too eager with this one! Closing.
