### ISSUE TITLE
Cannot re-import same plugin immediately

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#416]
after importing a plugin and deleting it, you cannot re import the plugin until after you click out of the section and back in

**Comment by bartimus-primed** [comment]
I will start working on this.

**Comment by privateducky** [comment]
Assigned it over to ya.

**Comment by bartimus-primed** [comment]
This should fix it. submitted a pull request:
https://github.com/preludeorg/operator/pull/2487
