### ISSUE TITLE
Cannot delete invalid plugins

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#417]
When importing a plugin that isn't valid, the delete icon will not show. Thus having to either re-import the plugin or manually delete it via workspace.

**Comment by privateducky** [comment]
Can you post an example bad plugin? 

Hard for me to visualize how to re-create this.

**Comment by stephanwampouille** [comment]
@privateducky So if you make a new plugin .html and just put 
`<script>
    function blah
</script>
`
Which won't work right, but  It will still get imported and will stay in the plugin section with no tray to delete. Even if you restart Operator it will remain. The only way to delete it is via the user's workspace.

**Comment by bartimus-primed** [comment]
working on this.

**Comment by bartimus-primed** [comment]
fixed in https://github.com/preludeorg/operator/pull/2488
