### ISSUE TITLE
Feature Request: Vim mode

### ISSUE THREAD

**Issue by gerbsec** [preludeorg/operator-support#418]
Hey, while using the editor in Operator I noticed that vim mode is not a feature that is available. I believe that vim allows a lot of professionals to become more effecient when writing their code, whether its a TTP or a payload, it does speed up operations. I understand that its not top priority, but I do believe it should be added eventually.

**Comment by privateducky** [comment]
Update: we're making some big adjustments starting in version 1.5 around the ability to edit/manage TTPs. As such, Editor as it stands today will be going through a metamorphosis and vim support won't be provided in the new direction we're going. 

What we're pushing toward, is meeting people where they currently work, in the IDEs of choice. We're evaluating different IDE solutions to consider plugins. If VIM is an interest to you, I'd recommend investigating that from a plugin perspective. 

Al Operator TTPs are stored on disk, in your workspace directory. So a vim plugin should just interact with the files there.
