### ISSUE TITLE
Connect a redirector icon isn't rendering correctly on 1.3.3

### ISSUE THREAD

**Issue by sthomps** [preludeorg/operator-support#423]
![Broken icon](https://user-images.githubusercontent.com/813716/147163963-84d430d9-3050-41eb-bd62-ab078275927a.png)

**Comment by lzimm** [comment]
@sthomps can you copy and paste what you see inside of your `config.yml` file for the switchboard plugin? (ie: `cat ~/Library/Application\ Support/Operator/login.prelude.org/plugins/Switchboard/config.yml`)

that should be getting automatically deleted, unless you don't actually have one that's marked as "native" for some reason.

**Comment by privateducky** [comment]
@sthomps are you still seeing this? would like to solve this for 1.4 if we can.

**Comment by sthomps** [comment]
oh whoops, let me try. sorry i didnt see the original

Spencer Thompson

Founder
Sokanu
***@***.***
604.349.1256

**Comment by sthomps** [comment]
<img width="1390" alt="CleanShot 2022-01-10 at 18 58 12@2x" src="https://user-images.githubusercontent.com/813716/148873580-8e518433-d652-43ea-8a8c-5e7e9aadda73.png">

This is what I see now (I haven't copied/pasted Lew's code yet).

**Comment by lzimm** [comment]
looks like its gone right?

**Comment by sthomps** [comment]
exactly. thank you!
