### ISSUE TITLE
Edge case exists where token becomes invalid

### ISSUE THREAD

**Issue by sthomps** [preludeorg/operator-support#424]
<img width="350" alt="CleanShot 2021-12-23 at 09 42 03@2x" src="https://user-images.githubusercontent.com/813716/147275270-34911270-9278-4210-a9c1-111e318486ab.png">

**Comment by sthomps** [comment]
Logging out and then in fixed this. It seems like I had an invalid token likely due to bad token refresh.

**Comment by lzimm** [comment]
not perfect, but when we fail to load the full attack schema from HQ, i'm building a local version from your on-disk attacks as a placeholder instead:

https://github.com/preludeorg/plugins/commit/d72b8671e4d3d680c192f59a52f29f59f679019d
