### ISSUE TITLE
Feature Request: Provide feedback when upgrading Operator versions

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#426]
Right now when you click update to new version, there is no set notification or download % of Operator grabbing the latest version. This leaves you questioning if it already upgraded or failed to upgrade. After about 15s or so you will receive another prompt asking to install, then it refreshes and you have latest version. I think we should be a bit more clear on the process to mitigate any confusion at all.

**Comment by privateducky** [comment]
Agreed. There's a slowness to this which is pretty variable (1-20s I've seen!). We can address this.

**Comment by privateducky** [comment]
@lzimm this is a pretty easy ticket to knock out - but this has been a historically tough area for us to test. do you have a good test set up for this process by chance?

**Comment by stephanwampouille** [comment]
@privateducky , I tested using the builds provided to me by @jpmoss after merges by @lzimm were made and it worked perfectly.
