### ISSUE TITLE
Headless redirector backwards compatibility issue

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#428]
Redirectors provisioned in 1.3 will not work in 1.4 without a manual configuration change to `settings.yml`.

The issue is:
```
tools:
  - team/headless
```
which needs to be updated/changed to:
```
tools:
  - headless/headless
```

**Comment by lzimm** [comment]
should be fixed here: https://github.com/preludeorg/plugins/commit/9c05334658c7ad265da235a2f857579cd9033dee
