### ISSUE TITLE
Feature Request: Bulk export TTPs

### ISSUE THREAD

**Issue by w0rk3r** [preludeorg/operator-support#430]
A way to bulk export TTP files now that they are encrypted in disk would be awesome.

@privateducky I think you once mentioned a script that could do this task

**Comment by privateducky** [comment]
Yep! In 1.5, we're aiming to launch a whole new way to approach TTPs/payloads which will include working with them in bulk. 

In the meantime, you can write a plugin which does a bulk decrypt using this snippet:
```
        Basic.recursiveFiles(path.join(Settings.settings.local.workspace, 'attack')).forEach(file => {
            try {
                const location = path.join(...); //where do you want to store me?
                let decryptedTTP = Encryption.decrypt(Basic.loadData(file), Settings.settings.local.keys['data']); //decrypts
                Basic.storeData(decryptedTTP, location); //writes decrypted form back to disk
            } catch (e) {
                console.log(e)
            }
        });
```

**Comment by privateducky** [comment]
The way to handle this in 1.5 will be over the API. Note the /ttps endpoint(s) in the upcoming documentation: https://github.com/preludeorg/community/blob/master/docs/operator/advanced/api.md
