### ISSUE TITLE
Feature Request: Payload importing

### ISSUE THREAD

**Issue by olafhartong** [preludeorg/operator-support#432]
It would be great to be able to import payloads via:
* the yaml/git import 
* the API

**Comment by sintax1** [comment]
+1 !

**Comment by privateducky** [comment]
New payload API documented here, coming in 1.5: https://github.com/preludeorg/community/blob/master/docs/operator/advanced/api.md

**Comment by olafhartong** [comment]
this is looking great team! can't wait to test this!
