### ISSUE TITLE
Terminating redirectors in other regions (not us-east-1) throws an error

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#434]
<img width="347" alt="CleanShot 2022-01-31 at 22 06 37@2x" src="https://user-images.githubusercontent.com/43142871/151907471-4184a313-1dde-42d1-8adb-6264d23d6991.png">

**Comment by khyberspache** [comment]
This is still broken in PROD, unless you're referring to DEV

**Comment by privateducky** [comment]
@lzimm you know the status on this by chance (in dev)?

**Comment by stephanwampouille** [comment]
will do

**Comment by lzimm** [comment]
i think it got fixed the other day actually, via: https://github.com/preludeorg/community/pull/396

**Comment by privateducky** [comment]
@stephanwampouille can you test if this was resolved via 1.5?

**Comment by privateducky** [comment]
@lzimm @stephanwampouille update on this bug?

**Comment by stephanwampouille** [comment]
I was able to terminate the redirector in us-east-2 but got this error. It did terminate successfully though<img width="633" alt="Screen Shot 2022-04-07 at 1 04 10 PM" src="https://user-images.githubusercontent.com/84744117/162258134-7e48156e-9848-46dd-9d70-afcb1c305189.png">

**Comment by privateducky** [comment]
were you connected to a redirector when you did this, by chance?

**Comment by stephanwampouille** [comment]
I was not, I had just disconnected right before

**Comment by stephanwampouille** [comment]
I actually need to correct myself I got this error for a different reason which I will open. But I did not receive nor have any troubles terminating redirectors on east-2
