### ISSUE TITLE
Redirectors do not work if you use an IP instead of DNS

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#441]
1. Create redirector
2. Relaunch redirector with IP instead of DNS as hostname
3. Swap DNS name in Settings.yml with IP
4. Operator will temporarily connect to redirector then drop connections

**Comment by khyberspache** [comment]
Could impact team environments as well (if someone tried to add the ip)

**Comment by privateducky** [comment]
we didn't treat this explicitly in 1.5, so I'd assume this is still outstanding. I know you looked at this @lzimm .. any insights?

**Comment by seijisakurai** [comment]
![redirector_test](https://user-images.githubusercontent.com/97065717/162036731-1fc47744-2103-4f6f-bb0a-d1c06de3db61.png)

Redirectors does work if you use an IP instead of DNS. Closing issue.
