### ISSUE TITLE
[Bug] Non-Existent TTP submitted via API blocks the agent queue

### ISSUE THREAD

**Issue by w0rk3r** [preludeorg/operator-support#444]
When you submit an TTP id via the Operator API that doesn't exist, it doesn't return a error, rather it break the agent ability to execute any action, even if the queue is cleared.

I think checks for this could be implemented to solve the problem.

Steps to reproduce:
* Use swagger/python to submit a random TTP ID that doesn't exist on Operator

Tested with PneumaEX

**Comment by privateducky** [comment]
@bartimus-primed know if this'll cause an issue on the /v1 API coming out with 1.5?

**Comment by bartimus-primed** [comment]
> @bartimus-primed know if this'll cause an issue on the /v1 API coming out with 1.5?

I can check, I had tried to ensure all api calls fail gracefully. Ill take a look.

**Comment by bartimus-primed** [comment]
Yeah I checked, this effects 1.5. Submitted a PR to check this.

**Comment by privateducky** [comment]
> Yeah I checked, this effects 1.5. Submitted a PR to check this.

Great!!

**Comment by privateducky** [comment]
Fixed in 1.5. This endpoint will also return the instruction IDs that were queued up for each agent.

**Comment by w0rk3r** [comment]
Nice, great work guys ;)
