### ISSUE TITLE
Source buttons don't load source code (windows version v1.4.2)

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#445]
I click the "Source" button for agents and it flashes a tab on my browser but doesn't go anywhere. My default browser is Chrome on Windows)

![image](https://user-images.githubusercontent.com/22311332/155044706-40222e7f-72b2-4996-9f41-77f5f7883eb0.png)

**Comment by privateducky** [comment]
@stephanwampouille can you check on this tomorrow?

**Comment by stephanwampouille** [comment]
Tested on my Windows machine, using chrome as default browser as well. Works as intended for me, the source button will open a windows browser but will automatically prompt the file to download. The new tab will then close itself if you had a browser already open. Is nothing being downloaded for you @clr2of8 ?

**Comment by clr2of8** [comment]
where would it be downloaded to?

**Comment by clr2of8** [comment]
Ha Ha, yeah, never mind, I never noticed that it was downloading stuff. It's working.

**Comment by stephanwampouille** [comment]
Woohoo Awesome!
