### ISSUE TITLE
Question: Should Vectr plugin send Targets to Vectr API?

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#446]
The Targets are blank on test cases sent from Operator to Vectr but I would expect that information could/would be sent along with all the other info and automatically filled in.

![image](https://user-images.githubusercontent.com/22311332/156067835-26bc61f7-a0cd-4990-a843-c903d18d125a.png)

**Comment by khyberspache** [comment]
I haven't set it up to export that data. The Vectr API would need to support that field, which I haven't dug into. @thebluecheese might be able to answer that

**Comment by thebleucheese** [comment]
the test case data inputs in the API currently allow you specify targets and sources while creating test cases

`targets: [String!]
 sources: [String!]`

If you have that data while you're creating the test cases, you can just add them there.

**Comment by khyberspache** [comment]
When passing in the 1 target should it be an array with a single sting  or string

**Comment by khyberspache** [comment]
Will be available in 1.5:
- https://github.com/preludeorg/community/pull/386

**Comment by clr2of8** [comment]
Excellent. Thank you!
