### ISSUE TITLE
Cannot access a TTP's attack chains in Editor

### ISSUE THREAD

**Issue by stephanwampouille** [preludeorg/operator-support#451]
When trying to access a TTP's associated attack chains in editor we get the following error. Im assuming we have renamed or removed this endpoint.
<img width="393" alt="Screen Shot 2022-03-29 at 7 59 52 AM" src="https://user-images.githubusercontent.com/84744117/160607042-4ef1c185-4c92-4a65-8c79-7ec7138a887a.png">

**Comment by privateducky** [comment]
closing, as this is no longer an issue in 1.5.
