### ISSUE TITLE
Add advanced search filters

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#452]
Without search filters it's difficult to find ttps and chains unless you already know what you're looking for.

Previously we had search filters like `platform` to help narrow down results.  If the search is the only interface to browse ttps then it needs to facilitate exploration rather than assume the user knows what exists.

Advanced search should have the filters for:
- tactic
- technique
- platform
- executors
- tags
- facts
- command

**Comment by privateducky** [comment]
A few other to consider:
- author
- release date
- theme

**Comment by privateducky** [comment]
@VVX7 one question: in 1.4, the advanced search filters were an often overlooked feature (we got "oh, I didn't know that was there!" often). likely because we didn't place much prominence on the tooltip. any thoughts on where/how you'd handle that in 1.5?

**Comment by VVX7** [comment]
@privateducky  I'd drop a high visibility "advanced" button in the search bar itself. Clicking on it should drop down a list of filters and examples, and stay open as the user builds their query, closing automatically when the search is executed. Persisting the last advanced search would be useful since the user might not get it in one.

It would be a huge quality of life improvement if you could also build a query graphically using the advanced search pane (selecting tactic from a dropdown vs copy/pasting text, selecting platform from a list, etc).

**Comment by privateducky** [comment]
Combining https://github.com/preludeorg/operator-support/issues/453 into here.

The scope of this ticket can be: upgrades to our TTP search function (in general). We'll spec these out for a future release. But in the meantime, plug any thoughts/requests here to track.
