### ISSUE TITLE
Add search boolean operators

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#453]
Exploring ttps/chains using a single filter is inefficient when the search returns many results. ex. `platform:windows`

The chain search should support basic boolean operators on filters to make it easier to find relevant chains. ex. `platform:windows AND NOT (tag:destructive OR tag:yolo)`

Supported booleans should include:
- AND 
- OR
- NOT
- parentheses for order for operation

**Comment by privateducky** [comment]
combining this into https://github.com/preludeorg/operator-support/issues/452
