### ISSUE TITLE
Cloud provisioning on account fails with error 400

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#455]
Attempting to provision was failing with an error 400

**Comment by lzimm** [comment]
it looks like this is broken because we're failing to locate `cb01547d2ad40c544cfbb69e6f08158a312256eb/headless`

which itself is referenced by: https://github.com/preludeorg/community/blob/master/ttps/resource-development/e22b3ca7-6181-49ca-ab14-52ff9b7f49be.yml

**Comment by lzimm** [comment]
@jpmoss can you check to make sure that the headless binary is up on the 1.5 outpost?

**Comment by jpmoss** [comment]
It is but not in `cb01547d2ad40c544cfbb69e6f08158a312256eb`. Fixed now.

**Comment by stephanwampouille** [comment]
I haven't been able to reprod the error 400 but I have been unsuccessful in trying to connect to a redirector that I deployed via AWS on Connect.

**Comment by stephanwampouille** [comment]
I retested again and can't reprod the 400, but still experiencing the refresh behavior when trying to connect to it.
