### ISSUE TITLE
When using an exfiltration TTP over a redirector, the redirector IP is not used

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#46]
When you use an exfiltration TTP, unless you hard-code the address, the local (either 127.0.0.1 or 0.0.0.0) address is used to send the exfil'd data to instead of the actual IP address (or FQDN) of the local server or redirector.

**Comment by privateducky** [comment]
We will apply a "micro" solution to this, where we:

1) select the connected redirector, if applicable
2) use the local IP address, if serving Operator on all interfaces
3) use the Operator host:port otherwise

**Comment by privateducky** [comment]
The "macro" solution would include smartly determining per agent which IP or FQDN it is using to communicate with Operator. This solution would require more extensive changes and is a smaller use case, so we're opting for the micro solution for now.

**Comment by khyberspache** [comment]
This worked for me during testing, think we can mark it 0.9.12

**Comment by khyberspache** [comment]
@privateducky

**Comment by privateducky** [comment]
> @privateducky 

Agreed, resolved a few days ago
