### ISSUE TITLE
Pink Badge registration hangs after clicking verify

### ISSUE THREAD

**Issue by seijisakurai** [preludeorg/operator-support#461]
Clicking on "verify" for "register for pink badge" causes a hang.
![unknown](https://user-images.githubusercontent.com/97065717/162268710-40f3e21b-63c9-4be0-9e5d-a01073306fc6.png)

**Comment by privateducky** [comment]
fixed: https://github.com/preludeorg/community/commit/2693750bc0aa4a8b12b4c71c5f29b64d2695be7c

@jpmoss we need to pop this into dev/prod outposts.
