### ISSUE TITLE
redirector deletions hangs

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#463]
<img width="1612" alt="CleanShot 2022-04-07 at 20 12 19@2x" src="https://user-images.githubusercontent.com/43142871/162339021-858786c6-4f14-491a-8d53-95a89e4121db.png">

deleting a redirector hangs the connect UI

**Comment by khyberspache** [comment]
appear to delete properly though

**Comment by privateducky** [comment]
I can't replicate. I've tried two scenarios:
- manual redirector (just one delete prompt, to remove from list)
- cloud redirector (two delete prompts, one for list removal, one for aws termination).

it's possible latest code changes have resolved this issue or a different bug you reported was masking the issue. 

I'm marking this as resolved but to retry with the latest release candidate (this upcoming week).
