### ISSUE TITLE
redirector connection doesn't out any outpost or publisher information

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#464]
<img width="1612" alt="CleanShot 2022-04-07 at 21 15 15@2x" src="https://user-images.githubusercontent.com/43142871/162344150-3eeaab6c-fa7b-477b-9f1e-b6de7d4f634b.png">

**Comment by privateducky** [comment]
How was the redirector provisioned, manual or cloud? No console errors, right?

**Comment by khyberspache** [comment]
cloud provisioned with connect plugin, no console errors

**Comment by privateducky** [comment]
reason: this is another bug introduced by the node-fetch "patch" applied here: https://github.com/preludeorg/operator/commit/63d5c7097d1da4724586fe3d1c9bca85dfa97b7a

will work through an appropriate https solution.

**Comment by privateducky** [comment]
This should be resolved with the removal of node-forge. 

I have currently swapped self-signed certs for HTTP. I'm debating leaving as-is for 1.5.3 or looking for alternative https solutions that work with our redirectors this week.
