### ISSUE TITLE
race condition on login still exists

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#465]
something seems to have happened to my operator 1.5.2 where it gets stuck on load and just spins with the 3x3 square of dots flashing on the Agent Dashboard page. I deleted the app, reinstalled it, rebooted, nothing seems to help. When I reverted to 1.4.2 it seemed to load fine but even after factory reset when I chose to upgrade I'm back to spinning and can't escape. Any ideas?

**Comment by privateducky** [comment]
This should be resolved with the full removal of node-forge. Will need a retest on the next release candidate build (upcoming week).
