### ISSUE TITLE
Requests library broken for plugins in 1.5.2

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#466]
```
Requests.fetchOperator = (endpoint, params, host=null, token=Settings.s.public.token, contentType='application/json') => {
    return new Promise((resolve, reject) => {
        require('./lib/fetch').fetch(`https://${host ? host : Settings.s.public.server}:${Settings.s.public.api}${endpoint}`, {
            agent: Requests.insecure,
            headers: {
                authorization: token,
                'Content-Type': contentType
            }, ...params
        }).then((res) => resolve(res)).catch(reject)
    });
}
```

![image](https://user-images.githubusercontent.com/43142871/162490745-05d1bd9b-7c4f-4752-af4a-714477887724.png)

**Comment by privateducky** [comment]
@khyberspache this was resolved in https://github.com/preludeorg/operator/commit/68123444431d67661720a2edbb4895099dddb81d, correct?

**Comment by privateducky** [comment]
It looks like the original bug was introduced in our patch version: https://github.com/preludeorg/operator/commit/63d5c7097d1da4724586fe3d1c9bca85dfa97b7a

**Comment by khyberspache** [comment]
Yep

**Comment by lzimm** [comment]
this should be patched now, though @khyberspache do you mind giving it a kick with any plugins you've got that would make sense to do so with?

**Comment by lzimm** [comment]
scratch that, needs to be validated here: https://github.com/preludeorg/operator/pull/3687

note: the ART plugin seems to completely hang Operator on load right now, but at least its not throwing errors.
