### ISSUE TITLE
adding ART plugin pushes "automatic facts" and fact entry to last page

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#467]
![CleanShot 2022-04-08 at 17 20 00](https://user-images.githubusercontent.com/43142871/162533639-85c2c1ca-cd6e-43d1-9806-a6999bc38768.png)

these should be pinned to the first page of facts

**Comment by privateducky** [comment]
putting automatic facts first: https://github.com/preludeorg/operator/pull/3646
