### ISSUE TITLE
Redirector crashes on beacons

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#469]
Sent a Jambi beacon to the redirector and it completely crashes:
```
[server] operator connected
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Response>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by khyberspache** [comment]
Equivalent error in Operator happens

<img width="1719" alt="CleanShot 2022-04-09 at 00 39 40@2x" src="https://user-images.githubusercontent.com/43142871/162556615-c3481e8a-589d-4b4a-9f1d-8efe50e9df26.png">

<img width="1725" alt="CleanShot 2022-04-09 at 00 40 06@2x" src="https://user-images.githubusercontent.com/43142871/162556624-bd3c6fa1-b09e-4a68-a485-6809fbfbb742.png">

**Comment by privateducky** [comment]
@khyberspache two issues here:
1. the redirector shouldn't die on a bad request like this. I'll take a look.
2. the payload is 404'ing, which your screen shots look like you may be missing a "/" in your payload name (to separate the agent name from the module name).

**Comment by privateducky** [comment]
This resolves the first issue: https://github.com/preludeorg/operator/pull/3645

**Comment by khyberspache** [comment]
Jambi should be g2g now I patched that side

**Comment by lzimm** [comment]
if this was the simple 404 issue, can confirm that should be working properly now. bad payloads just cause operator to chill.
