### ISSUE TITLE
ThinkTank tag exists on TTPs but no tag option in Editor

### ISSUE THREAD

**Issue by privateducky** [preludeorg/operator-support#47]
The Editor section does not seem to be showing all tags for all procedures. There are several ThinkTank tagged procedures but no filter description on the lefthand side.

The filter exists but no informational hover.

**Comment by privateducky** [comment]
@khyberspache assigning this one to you. Just adding this to our descriptions should do the trick.

**Comment by khyberspache** [comment]
PR in. I'll bump PROD services once it's merged then close this.

**Comment by khyberspache** [comment]
In production
