### ISSUE TITLE
Operator Networking and causing issues with services

### ISSUE THREAD

**Issue by Xanthonus** [preludeorg/operator-support#470]
In Operator 1.4 I ran into an issue where when my ethernet adaptor did a DHCP release the IP did not change in Operator causing not only agents not to work but also things like HQ not to communicate. 

In updating to Operator 1.5.2, my IP settings were left blank again causing Operator not to be able to login to HQ and I had to track it down. 

The tool acts normally during this event and doesn't provide error so you end up having to troubleshoot and I can see this being a really bad user experience. I use multiple NICs and vNICS and I'm sure we have other customers who do that too. Our tool really doesn't have the ability to change NICs seamlessly nor is it really IP aware.

**Comment by privateducky** [comment]
Not sure how to classify this one yet, so I'll leave open for now. I'm sure we can come up with a few scenarios to consider/put under test.

**Comment by privateducky** [comment]
closing, as this is too nuanced to get in before 2.0 release - and 2.0 will render this not possible, given the direction we're going.
