### ISSUE TITLE
Latest chains display is wrong inside Operator

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#474]
![CleanShot 2022-04-13 at 14 41 11](https://user-images.githubusercontent.com/43142871/163248348-a2c3a174-b704-46d2-8e99-1092a94cb6ca.png)

**Comment by privateducky** [comment]
In 1.5.3, the chain files will be read from Outpost, with the release date in the YML file. This should auto-resolve this issue, as I believe the date is being manipulated incorrectly somewhere along the code path as the chains get constructed.
