### ISSUE TITLE
Several chains broke during the 1.4 -> 1.5 cutover

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#476]
We need to go back and revalidate _all_ chains function since the 1.5 cutover

**Comment by privateducky** [comment]
@khyberspache are these fixes now rolled out or waiting for 1.5.3?

**Comment by khyberspache** [comment]
This is going to be a longer process (all of next week). 

Move forward with 1.5.3 as we will be tackling in parallel

**Comment by Xanthonus** [comment]
Progress Tracking:

**APT29 Theme** 
COVID19: Works as intended

DNC: Missing the Collect E-Mail Data TTP and at least on initial run can the chain out of order. I had to lock the chain and then force run Self-Extracting RAR malware first. At least 2/3 TTPs ran sucessfully but missing the TTP to actually get anything. 

ExBox: Needs complete reworking for both getting the payload from server and AdFile is copied wrong. 

Goldilocks: Host Dynamically Named Payload is missing phish.payload.url on line 52 but also following the YT guide I believe you will run into errors like Im having where the server will not host the file. In any case, the YT guide should be looked at to ensure that we are informing people how to set this up the right way. In following it, it fails for me. 

OperationGhost: Needs a new encoded PNG

Polarcalm: Needs updates

**Comment by Xanthonus** [comment]
**Ransomware Theme**

Windows LoTL and Linux LoTL works as intended 

Trying to get redirectors to work for me to test S(C)wipe Cswipe posted issues in #Operators-prod

**Comment by Xanthonus** [comment]
This is effectively completed with only Goldilocks an issue that we are tracking.
