### ISSUE TITLE
Broken "chains website" link in v1.5.3 Docs

### ISSUE THREAD

**Issue by sintax1** [preludeorg/operator-support#480]
The "chains website" link under **Docs/What is a chain** is broken in the latest release. 

**Repro Steps:**
1. Start Prelude Operator
2. Navigate to Docs->What is a chain
3. Click on "chains website" within "TTP Tuesday" paragraph.
4. Observe web page opens to invalid url (https://%3Cmark%3Echains%3C/mark%3E.prelude.org).

**Comment by privateducky** [comment]
@sintax1 I can reproduce this issue. what operating system are you on?

note the docs are read from our community repo, this page in particular is here: https://github.com/preludeorg/community/blob/master/docs/operator/terms/chain.md.

**Comment by sintax1** [comment]
@privateducky  I'm on OSX.

**Comment by privateducky** [comment]
@sintax1 we haven't been able to reproduce this issue. can you take a few screen shots of what you see/are doing?

**Comment by sintax1** [comment]
Working for me now as well. ¯\_(ツ)_/¯
