### ISSUE TITLE
Feature Request: Enhance chain Docs

### ISSUE THREAD

**Issue by sintax1** [preludeorg/operator-support#481]
When inspecting chain yaml files it appears several undocumented chain configuration parameters exist such as **variables** and **metadata**. 

Request that those additional parameters and their purpose be captured within all chains documentation, especially **Docs/Operator API** and **Docs/What is a Chain**

My assumption is that I may be able to set chain variables which could be used by the ttps, but the Docs don't make this clear.

**Comment by privateducky** [comment]
@khyberspache can you scoop this up?

**Comment by khyberspache** [comment]
Yep! Amazingly fast catch here haha

**Comment by privateducky** [comment]
@khyberspache let me know if you think this is a 1.6 candidate.

**Comment by privateducky** [comment]
@mireaulf since you're looking at docs, think you can get this in?

**Comment by mireaulf** [comment]
Added to the next iteration of our doc
