### ISSUE TITLE
Some labels for identified IOCs overlap the value.

### ISSUE THREAD

**Issue by bartimus-primed** [preludeorg/operator-support#483]
<img width="902" alt="image" src="https://user-images.githubusercontent.com/465079/164504894-10989302-759f-4e32-b72f-5eab5e7f084b.png">
<img width="894" alt="image" src="https://user-images.githubusercontent.com/465079/164505571-406410eb-a910-4592-a6a5-d01dbafb90bc.png">

**Comment by privateducky** [comment]
now fixed for 1.6.
