### ISSUE TITLE
Modified TTPs are not saving in production

### ISSUE THREAD

**Issue by Xanthonus** [preludeorg/operator-support#484]
When modifying a TTP in 1.5.3 the modified TTP is not saving and just retains the original TTP.

**Comment by khyberspache** [comment]
Repro steps? 

I made and saved several today

**Comment by Xanthonus** [comment]
@khyberspache This actually shows both this issue and the #485  

https://user-images.githubusercontent.com/10197660/164555703-53effda2-7f78-4faf-beca-051176bb536f.mov

**Comment by Xanthonus** [comment]
I think with 1.5.0 you used to have then two chains one that was modified and one that wasn't but if you look, I only have that 1 chain.

**Comment by Xanthonus** [comment]
O wow that is not obvious at all! 

@makk94 I found something else while testing this. So if you modify the chain we don't provide any designation that particular chain was modified other than going into the chain and seeing the modified TTP. This is a potential issue because say you select the chain that is not modified and then you re-search for the modified chain and select that chain. Now you have added back the unmodified TTP to the execution order. 

Also take a look at the line jumping that happens in this video when you modify the YML. If you could fix that I would be in your debt. Its the most annoying bug ever!

**Comment by makk94** [comment]
Yeah, I can do a quick fix to name modified chains in the same way that modified ttps are named (ie. appending `(Modified)` to the chain name)

Will continue to think about how to make it obvious that you need to click the button to save a new chain

And that yaml bug is super annoying ha trying to tackle that in https://github.com/preludeorg/operator/pull/3819
