### ISSUE TITLE
Unable to connect to redirector 1.5.3 

### ISSUE THREAD

**Issue by Xanthonus** [preludeorg/operator-support#486]
I've setup a redirector and it will not connect. In one case, I was able to connect to the redirector and when running a TTP it disconnected. 

https://user-images.githubusercontent.com/10197660/164554613-33e7030c-5dc6-403b-ab33-ff082c8be449.mov

**Comment by khyberspache** [comment]
The redirector is dead, the heartbeat is red. Check it's running properly

**Comment by khyberspache** [comment]
We might need to update the headless binary for auto provisioning

**Comment by Xanthonus** [comment]
@khyberspache Unless Im doing something wrong here it still fails even when I make a new one. 

https://user-images.githubusercontent.com/10197660/164556735-9dd19e6f-b67e-4a5f-9b61-787cf5992444.mov

**Comment by Xanthonus** [comment]
I feel like if it's a AWS account issue it wouldn't have made the EC2 instance

**Comment by khyberspache** [comment]
Did we update the headless binary and deployment TTP on prod?

**Comment by Xanthonus** [comment]
I'm going to guess we haven't. I'll take a look at it.

**Comment by privateducky** [comment]
I've tried a few, manual and cloud, and can't repro. @khyberspache any luck on your side?

**Comment by Xanthonus** [comment]
I noticed we have the old 1.5.2 on the EFS and the MD5 sum on the website is broken.

**Comment by privateducky** [comment]
ah, wonder if there's an incompatibility with 1.5.2 -> 1.5.3 on certain systems...

**Comment by Xanthonus** [comment]
@privateducky It works now! yay 💯

**Comment by Xanthonus** [comment]
@privateducky Welp it worked 1 time. I ran a chain on it. Disconnected and now fails every time to connect. Ive also removed the redirector. Closed Operator, Remade redirector. Fails to connect.

**Comment by Xanthonus** [comment]
Now its working again

**Comment by Xanthonus** [comment]
Ok I'm going to close again. I know I didn't pull the old binary when I first connected successfully, but it seems to be stable and working consistently. If it breaks consistently Ill reopen. Probably something weird happened with the workspace or something that first time.
