### ISSUE TITLE
Add indicator that user is logged out

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#490]
We need to somehow indicate to the user that they are logged out. We still do not do this and have to tell users to open their Dev console to check.

**Comment by privateducky** [comment]
Our current approach is the green icon in the bottom right. 

My guess: when hitting 403's, we're not actually logging you out / changing that icon back to grey. sound right?

**Comment by privateducky** [comment]
This is largely solved in 1.5.3, where there can only be 1 request to HQ (authentication) at a time.

In 1.6, @makk94 just added a forced logout if you delete your active security token, which should be the last "surprise" 403 path you can encounter. 

Adding the 1.6 label to this ticket as such. But let me know if you can think of any other edge cases the 403 could pop up in.
