### ISSUE TITLE
Search bar and deploy button obscure ttps

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#495]
The ttp search bar and deploy button are not locked in place. When scrolling a list of ttps they obscure the ttps beneath them.

Expected behaviour: the bar/button should not move from the top and bottom of the view.  

<img width="923" alt="CleanShot 2022-05-02 at 10 03 00@2x" src="https://user-images.githubusercontent.com/46228229/166247212-0134f6ce-9704-46b4-b88c-9ec751843459.png">

**Comment by privateducky** [comment]
@VVX7 fix just merged. Can you validate it?

**Comment by VVX7** [comment]
Fixed!
<img width="721" alt="CleanShot 2022-05-11 at 20 20 50@2x" src="https://user-images.githubusercontent.com/46228229/167967964-46c67c4d-eb0c-4bb1-b2e2-f9f88eed2b21.png">
