### ISSUE TITLE
Locked/unlocked phrasing is confusing

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#497]
Using locked/unlocked for TTP execution order is confusing because locked implies that the order is immutable and because locked/unlocked are used elsewhere in the app for a different purpose.

Consider alternative language such as ordered/unordered when referring to ttp execution.

Cross post from Discord:

![CleanShot 2022-05-02 at 16 14 44](https://user-images.githubusercontent.com/46228229/166319127-d8111afb-3f93-4c3c-99b9-17b6b7827728.png)

**Comment by privateducky** [comment]
good idea. fixed, will be in 1.6.
