### ISSUE TITLE
TTPs which don't have a matching script for an os should throw an error

### ISSUE THREAD

**Issue by Eric-Tyrrell22** [preludeorg/operator-support#5]
Was trying to deploy an agent with the following TTPs:
- DUMP LSASS MEMORY
- SNIFF NETWORK TRAFFIC
- FIND RECENT FILES
and got the following output:
![Screen Shot 2020-11-01 at 11 52 10 AM](https://user-images.githubusercontent.com/58529434/97809211-9f85ed00-1c39-11eb-98ce-26ded79599a6.png)

It would be helpful if there was some indication that incompatible TTPs weren't ran

**Comment by privateducky** [comment]
Perfect- we'll address this before v1.0. I was wondering how noticeable/findable this would be.

**Comment by privateducky** [comment]
This will be in our 0.9.2 build
