### ISSUE TITLE
Link is Sliver documentation is broken

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#501]
<img width="296" alt="CleanShot 2022-05-05 at 12 14 26@2x" src="https://user-images.githubusercontent.com/43142871/166967069-97a851d6-8d2b-4d44-8833-a4853f6a93c8.png">

Clicking that link send you to: https://github.com/BishopFox/%3Cmark%3Esliver%3C/mark%3E

probably a markdown library issue

**Comment by gerbsec** [comment]
This effects every link if the word you search for is in the URL.
