### ISSUE TITLE
Uploading Artifacts to Agents

### ISSUE THREAD

**Issue by bartimus-primed** [preludeorg/operator-support#502]
When attempting to upload an artifact to an agent using a:

(PUT HTTP://127.0.0.1:3391/)
Headers include a "key: $TOKEN" and "agent: $AGENTNAME" based on what it looks like in the code. Essentially the request hangs and has to be killed on the client-side. I attempted to debug in the app, but the request never hits the resolveUpload function in the debugger.

**Comment by privateducky** [comment]
Likely needs a header that we don't have documented. 

As part of solving this, we'll ensure there is a doc page specific to this endpoint put into the Community repo.

**Comment by privateducky** [comment]
@makk94 the ask on this one, to be clear, is for us to test our HTTP upload endpoint (PUT request against localhost:3391), which should accept arbitrary files and place them in a chosen agent's artifacts directory (in the prelude workspace).

We also need to verify our existing documentation (in the Community repo) is accurate to this endpoint.

**Comment by privateducky** [comment]
@makk94 sounds great - feel free to adjust docs anytime!
