### ISSUE TITLE
xss in facts

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#504]
There's an xss vuln in fact values in Operator.

Repro:
- create a new fact
- set the fact value to `"><script>alert('oh no')</script>`
- save fact and navigate back to 'My Profile'

![image](https://user-images.githubusercontent.com/46228229/167417362-0d7bbd5a-81c3-49b4-9440-a6903950c552.png)

**Comment by privateducky** [comment]
I'd equate this to DOS'ing yourself.. we have several of these cases inside the app itself, where we render HTML, but as a client-side app this one (in particular) looks like it's a no impact.

**Comment by VVX7** [comment]
Why stop and DOs'ing yourself when you can get the whole team?

When users connect to a redirector to share an agent then one user may store and execute code via a fact on anothers machine.  In this pic I set up a redirector, configured an agent and fact on one machine, connected to the redirector and opened 'my profile' on the second machine. 

![CleanShot 2022-05-09 at 10 28 27](https://user-images.githubusercontent.com/46228229/167432210-dd906705-738a-4ca5-b52b-9059ec830eca.png)
