### ISSUE TITLE
recent chain link is broken

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#506]
Recent chain "learn more" link in Operator does not link to the chain page.

<img width="824" alt="CleanShot 2022-05-09 at 11 21 03@2x" src="https://user-images.githubusercontent.com/46228229/167442579-c817bf37-71e9-427b-b6cb-96c69f782bbc.png">

![image](https://user-images.githubusercontent.com/46228229/167442530-ee137ea7-a962-4b1c-89cc-0541b22069bc.png)

**Comment by gerbsec** [comment]
This is a much more complicated bug as we don't have a way to track themes.
