### ISSUE TITLE
valid encryption keys may be reported as invalid

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#507]
A valid encryption key may appear invalid when a previous key was invalid.

Repro:
- save an invalid key
- save any valid key
- the key list will be red indicating the key is not valid

Expected:
- the box isn't red when the key is valid

Workaround:
- reload operator 

<img width="702" alt="CleanShot 2022-05-11 at 08 23 16@2x" src="https://user-images.githubusercontent.com/46228229/167849204-02515de9-6b5e-4a2c-bfbb-6dd13a91578f.png">

**Comment by privateducky** [comment]
@VVX7 can you validate the feature branch fix here? 
https://github.com/preludeorg/operator/pull/3864
