### ISSUE TITLE
Run Stockpile download on login in the background as worker thread

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#51]
* Requesting all the TTPs from the server on initial log in makes the UI look like it is hanging. We should handle this by running the stockpile request in the background

**Comment by privateducky** [comment]
Agreed. Adding our async guy on this ticket ;)

**Comment by lzimm** [comment]
I think this was actually already fixed here: https://github.com/preludeorg/operator/commit/1a8ecb22f5850a2cc5e6a0bd0edf6246b9811e52
