### ISSUE TITLE
HTTP Beacon agents show dead after first beacon wait

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#514]
<img width="403" alt="CleanShot 2022-05-16 at 20 12 34@2x" src="https://user-images.githubusercontent.com/43142871/168702127-ab88f69e-ae58-470d-ad37-fad63185e64f.png">

HTTP agents will connect, then go red (if interval over 10s), then go green once the calculation is made.

Repro:
1. Launch pneuma HTTP w/ sleep 60
2. Let agent connect
3. Wait for beacon to go red
4. wait for next beacon to go green

**Comment by privateducky** [comment]
@makk94 this should be an easy/quick fix. let me know if you'd like extra eyes on this.
