### ISSUE TITLE
Deleting third eye agent when another agent is present hides it. 

### ISSUE THREAD

**Issue by gerbsec** [preludeorg/operator-support#521]
Before deleting third eye: 

<img width="301" alt="image" src="https://user-images.githubusercontent.com/67713732/169342707-d05520d2-4a04-4309-9167-9e46c7c365c1.png">

After deleting thirdeye:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/67713732/169345940-0338e62c-d122-45fd-9949-ba5bc78f291d.png">

After deleting schism:

<img width="291" alt="image" src="https://user-images.githubusercontent.com/67713732/169346004-7e1800de-b1ad-4c57-b147-b74c6d376ae0.png">

**Comment by privateducky** [comment]
Odd. It should delete then re-appear immediately in this case.

**Comment by privateducky** [comment]
did a quick check on this - this is the intended behavior:
- if you delete the last agent (regardless of what it is) the page will reload, re-generating the thirdeye agent.
- if you delete an agent when more are in the list, no page reload occurs. if you deleted the thirdeye agent and do a manual page refresh, it will regenerate. 

This is primarily a safeguard against having 0 agents in the list, which would require us to have some additional handling of an empty app/page. 

I could see changing this behavior to be more intuitive but it's an edge case I'm not concerned with addressing at this point (unless it becomes a confusion point).
