### ISSUE TITLE
descriptive status codes

### ISSUE THREAD

**Issue by VVX7** [preludeorg/operator-support#523]
Operator should return more descriptive http status codes. 
I suggest https://http.cat/

**Comment by privateducky** [comment]
Which API are you interacting with?

**Comment by VVX7** [comment]
Right now? None.  If they return these cats? All of them.

**Comment by privateducky** [comment]
Did a quick scan through the internal Operator API and it looks right; we return 200s, 400s, 402s, 403s, 404s, 500s in the places I'd anticipate. I think we're good to go there but let me know if a given endpoint is mixed on status code!

**Comment by privateducky** [comment]
Per comment, not seeing any statuses that are off, in a quick scan. Please re-open if there are (specific) status codes not caught.
