### ISSUE TITLE
PROD headless asking for update but it is on latest version

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#528]
![image](https://user-images.githubusercontent.com/43142871/170107040-e3b5dfb2-6801-4be1-9e4e-9867530f711f.png)

**Comment by privateducky** [comment]
I saw this in development too, but figured it was a mismatch on our version numbers in the package.json file.

We need to:
- Validate our package.json versions are accurate
- Validate we are handling the /ping return (from Operator's headless API) correctly, where the version is returned back to this Connect panel.
