### ISSUE TITLE
Split TTP into variants is clone TTPs and not splitting them

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#532]
TTPs without variants are being split into X clones of the TTP where X are the number of executors on the TTP

**Comment by privateducky** [comment]
I have temporarily added a UX fix for 1.7, which will auto-switch the view to 'identifiers' if you click a SPLIT button.

This may get re-done before 1.7, but I wanted a stop gap just in case, that was at least clearer.
