### ISSUE TITLE
Auto update crashes headless

### ISSUE THREAD

**Issue by bartimusprimed** [preludeorg/operator-support#536]
this was reported by occupy_eip,

OS: Ubuntu 20.04

When headless is running from /opt/headless, an update will crash the headless instance.

"Run me from /opt/headless to enable automatic updates.... heh. even though I have latest headless and local version it says I need an upgrade done, but when I try to upgrade it seems to crash my headless version"

**Comment by privateducky** [comment]
It should stop and restart the process.. but it's possible there's a diff between /tmp and /opt.

**Comment by privateducky** [comment]
I have a feeling this is an after-effect of https://github.com/preludeorg/operator-support/issues/528, where we're firing off an upgrade attempt when there is none available. 

I'll keep these as separate issues for now, until we can confirm this.

**Comment by bartimus-primed** [comment]
> I have a feeling this is an after-effect of https://github.com/preludeorg/operator-support/issues/528, where we're firing off an upgrade attempt when there is none available. 
> 
> 
> 
> I'll keep these as separate issues for now, until we can confirm this.

Sounds good.
