### ISSUE TITLE
Links for ARM versions of pneuma

### ISSUE THREAD

**Issue by bartimus-primed** [preludeorg/operator-support#537]
It would be nice to have ARM versions of pneuma/pneumaEX in the "Add Agents" section.

**Comment by khyberspache** [comment]
This is actually more complicated than just adding another link... we currently don't have a way to designate architecture across TTPs/binaries

**Comment by privateducky** [comment]
Agreed. Would be nice to do more platforms (and we can 1-off if someone needs it) but closing, as this is unlikely to get prioritized anytime soon.
