### ISSUE TITLE
training section asks to install ART plugin that doesn't exist

### ISSUE THREAD

**Issue by makk94** [preludeorg/operator-support#539]
^ under introduction/advanced/3rd flag

**Comment by privateducky** [comment]
Ask: let's swap this training flag to the HTTPs plugin.

**Comment by privateducky** [comment]
@bartimus-primed could you pick this up now?
I'm ok if we kill this training flag for now as the solution.

**Comment by bartimus-primed** [comment]
flag removed in: https://github.com/preludeorg/community/pull/516
