### ISSUE TITLE
v1.6.0 training says use "-help" option but that doesn't work on Windows

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#541]
Agents question 3

![image](https://user-images.githubusercontent.com/22311332/171313036-5c163cd7-6507-4433-b07b-fd6893ab6364.png)

**Comment by privateducky** [comment]
@khyberspache could you patch this instruction?

**Comment by khyberspache** [comment]
This should be working cross platform. I'm going to label this bug. It's a golang argparse thing

**Comment by privateducky** [comment]
fixed, so closing
