### ISSUE TITLE
Add indicator that a user is logged

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#543]
We need a UI/UX element that shows a user is logged out

**Comment by privateducky** [comment]
@makk94 report here is that the green light is still on if a log out occurs.

**Comment by khyberspache** [comment]
I hit a case where I was logged out, not sure what happened/repro steps. https://github.com/preludeorg/operator-support/issues/490

will try to reproduce and get you steps

**Comment by makk94** [comment]
our earlier fix was fairly specifically to log out (and turn off the green light) if you delete the currently-in-use security token. If magical logouts are happening, I don't think the green light will turn off

**Comment by privateducky** [comment]
@makk94 can we do a short-cut for 1.7 on this topic, with an alert box on a log out event?

**Comment by makk94** [comment]
I can't find a way to trigger an event when a magical log out occurs. I can alert on every 403 response from HQ, but that sounds a little heavy handed, what do you think @privateducky

**Comment by privateducky** [comment]
I think a 403 can only occur in a logout scenario, as nothing else goes through that http logic aside from calls to HQ... right? if that is true, then an alert per 403 could work.
