### ISSUE TITLE
global.fetch not rejecting failed connections

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#545]
`fetch` attempts that hit an ECONNREFUSED are not rejected, which means promises resolve instead of reject:

![CleanShot 2022-06-02 at 18 52 18](https://user-images.githubusercontent.com/43142871/171751064-3c3bf5fa-e5bf-4dd3-8e25-0da5ae24016c.png)

We need to properly throw an error here so that the promise doesn't resolve and lead to undefined states

**Comment by privateducky** [comment]
this the root cause of the http/vectr dual plugin install bug?

**Comment by khyberspache** [comment]
I don't know if it's root cause, but it's definitely part of it

**Comment by khyberspache** [comment]
Fixed:
- https://github.com/preludeorg/operator/pull/3978
