### ISSUE TITLE
v1.6.0 cam

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#546]
If I X out a redirector then return to the "Deploy Manual Redirectors" form it can't be typed on. So I can fill in the FQDN and Token. I have to restart the app first.

**Comment by clr2of8** [comment]
If I X out a redirector then return to the "Deploy Manual Redirectors" form it can't be typed on. So I can fill in the FQDN and Token. I have to restart the app first.

**Comment by privateducky** [comment]
closing as duplicate
