### ISSUE TITLE
make chain endpoints consistent with TTP endpoints

### ISSUE THREAD

**Issue by ax-anadrowski** [preludeorg/operator-support#550]
At the moment, when I create my own attack chains and import them via API, all the data is not imported. Only name, ttps, summary and ordered are imported. I would like metadata, id and variables (and whatever other keys exist for chains) added to enable me to use all the same features for my own attack chains. 

In addition, this makes it easier and more convenient to build automation for backup/restore of chains. To explain, I'll elaborate on my existing process for backing up TTP's, and then show how this is not possible for chains.

1. I download all TTP's via API and commit them to a private github repo.
2. I work in operator for days and make edits to multiple TTP's.
3. I lose track of my work in operator and forget which TTP's were updated/changed.
4. I redownload all TTP's
5. I use git diff to see what TTP's changed, and commit changes to git as needed.

This is all possible because all the keys of a TTP are allowed to be imported via the API. So what matches the yaml file on disk, matches what's in operator.

Since the chains endpoints don't accept all the keys I am submitting via API, what I have on disk is never going to match what's in operator.

**Comment by privateducky** [comment]
This makes complete sense and is easy for us to do, while remaining backwards-compatible. 

@makk94 can you take a look at this one for 1.7?

**Comment by privateducky** [comment]
Combining this with a duplicate, earlier ask: https://github.com/preludeorg/operator-support/issues/482
