### ISSUE TITLE
Nested lists in docs don't render correctly

### ISSUE THREAD

**Issue by jaherne** [preludeorg/operator-support#552]
Nested unordered lists in markdown don't render correctly. With [links.md](https://github.com/preludeorg/community/blob/master/docs/operator/advanced/links.md) for an example, each list shows as a single paragraph: 
<img width="626" alt="Screen Shot 2022-06-15 at 5 46 32 PM" src="https://user-images.githubusercontent.com/2062225/173954730-2b90bf41-a618-4606-9b1a-af9421686f33.png">

In Github, the markdown is rendered correctly:
<img width="728" alt="Screen Shot 2022-06-15 at 5 44 46 PM" src="https://user-images.githubusercontent.com/2062225/173954661-403b8c65-3c40-4fc0-8269-1b1161f47a14.png">

**Comment by privateducky** [comment]
Good find. 
I'm labeling this as a 'solved in 1.7' though, as we are moving docs out of the app and into an online location (readme.com).
