### ISSUE TITLE
v1.6.0 the lock agent button/functionality is missing

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#553]
This bug prevents the completion of the Introductory training.

**Comment by privateducky** [comment]
@makk94 can you check which flag this is and adjust it/get it into production?

**Comment by makk94** [comment]
Looks like @bartimus-primed  removed this flag in https://github.com/preludeorg/community/commit/13c15678de6aea8b2252d7e45f36f9d45649e896
