### ISSUE TITLE
Resources missing in Training section

### ISSUE THREAD

**Issue by solocommand** [preludeorg/operator-support#56]
On Operator 0.9.12.56 on MacOS, the resources menu is empty within the training section. The [training video](https://youtu.be/uF1hpNbPoUA?t=97) clearly shows that they should be there, and seem to contain information needed to complete the training.

![image](https://user-images.githubusercontent.com/1778222/104769281-b0240a80-5734-11eb-87b5-0b713b5afc85.png)

**Comment by privateducky** [comment]
I'm glad you noted this- it had fallen off of our immediate roadmap. 

The resources contain hot links to supplemental data on external websites. We pulled these out last month, as we have configured Operator to not need/require any internet resources (aside from the authentication server at login.prelude.org). However, our plan was to re-add the resources later on and proxy the connection through the auth server to ensure Operator continues requiring nothing else online.

I'm going to mark this as a bug & see if we can work this in soon.

**Comment by privateducky** [comment]
One more note for clarification: you don't need the resources to complete the Introduction program - but the resources do include great supplemental resources for further reading on related topics.

**Comment by privateducky** [comment]
Thinking aloud on this one. I wonder if we can download resources (html, files, etc) into a workspace/resources directory and open them from here. This would keep everything piping through GateKeeper and not the open internet.

**Comment by privateducky** [comment]
OK, I patched the resource links so they'll show up once again. As I did this, I bucketed the code internally into an "internet" module so we can clearly track which parts of Operator are allowed to talk to the internet. Currently, aside from GateKeeper, Operator only needs internet access for:

- Training resources (links or videos)
- TTP import of a GitHub repo
