### ISSUE TITLE
Emulate UI hangs when large datasets are return from a command execution

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#57]
Seems to only affect HTTP and GRPC with pneuma:

When large data is returned by an agent, the emulate UI chokes while processing the data.

Repro:
1. Create adversary with `ps aux`
2. Run adversary

**Comment by privateducky** [comment]
Is this one still out there? I saw you and @lzimm chatting about it the other night.

**Comment by khyberspache** [comment]
Yes this bug still exists, it on this specific reducer during fact calculations:
```
const facts = persisting.filter(link => (link.Response && link.Status === 0)).reduce((acc, link) =>
            Object.keys(PARSERS).reduce((acc, key) => {
                const finalKey = `${key}.${ATTACK[link.ttp].technique.id}`
                return PARSERS[key].regex.reduce((acc, pattern) =>
                    (link.Response.match(new RegExp(pattern, 'gim')) || [])
                        .reduce((acc, match) => {
                            let fact = new Fact(beacon.Name, finalKey, match, link.ID, link.ttp)
                            return acc.concat([fact.flush().then(() => {
                                self.facts = {
                                    ...self.facts,
                                    [link.ID]: (self.facts[link.ID] || []).concat([fact])
                                }
                            })])
                        }, acc), acc)
            }, acc), [])
```

which can take sometimes up to 7 seconds to finish given large inputs:
![image](https://user-images.githubusercontent.com/43142871/105068857-5df22a80-5a4f-11eb-977c-953ef1b7bfb5.png)


We need to move the entire process to a worker thread (probably).

**Comment by lzimm** [comment]
this should be a lot better in 0.9.14
