### ISSUE TITLE
Percent completion calculating as NAN%

### ISSUE THREAD

**Issue by xenoscr** [preludeorg/operator-support#6]
This afternoon the tutorial completion percentage is showing NAN%. I closed and re-opened the operator.exe process and rebooted, it did not resolve the issue.

![image](https://user-images.githubusercontent.com/2199813/97812420-3f01aa80-1c4f-11eb-8bb2-537db2014f04.png)

**Comment by privateducky** [comment]
This is a good find. It's due to me updating our training flag structure on the backend. We'll fix this tomorrow through dropping a 0.9.1 release, and see how that process works.

We'll also need to ensure our backend server is versioned, similar to Operator, so these things can stay in sync.

**Comment by privateducky** [comment]
Training has been updated. We have cleared out prior training, as we have updated the flow to make it more intuitive. Note: you'll want to install version 0.9.1 from the downloads page.
