### ISSUE TITLE
(Unhandled Exception) after supplying token during login

### ISSUE THREAD

**Issue by CicadaMikoto** [preludeorg/operator-support#60]
<img width="1397" alt="Screen Shot 2021-01-19 at 11 28 44" src="https://user-images.githubusercontent.com/6219274/104980302-942cab80-5a49-11eb-8703-4416dcba652c.png">
Not sure what the issue is, but was told to do this.

First time attempting to login. Entered email and successfully got a token. After clicking Authenticate, I got a notification that 210 modules had been downloaded, but then this error message appeared and I can go no further.

**Comment by privateducky** [comment]
Hi @CicadaMikoto we've seen this bug pop up when someone used an older version of Operator (pre version 0.9.9), after they upgrade. Clearing out your workspace manually should fix it. One sec and I'll grab the directory to delete.

**Comment by CicadaMikoto** [comment]
Hey, this was actually my very first login after a fresh download.

**Comment by privateducky** [comment]
Oh that's strange then.. what operating system are you on? 

For whichever, can you try manually deleting the directory specified here and re-authenticating? Hoping the same fix does the trick.

![image](https://user-images.githubusercontent.com/49954156/104982361-7e32d280-59d8-11eb-881e-af1441aba656.jpeg)

**Comment by CicadaMikoto** [comment]
MacOS 10.14.6.  I'll give that a shot now and see how it goes.

Update: After sitting for 20+ minutes at the main screen, the loading icon has no disappeared and I am unable to login.

![image](https://user-images.githubusercontent.com/6219274/104984266-bde9d080-5a51-11eb-917d-1ce2d93beb98.png)

**Comment by CicadaMikoto** [comment]
Update again: Just closed the program and reopened it, then it logged me in without authentication.

**Comment by privateducky** [comment]
Perfect! Thanks for reporting this; our hunch on the issue being an upgrade bug was incorrect so we'll root cause it today to see why it's so tough to replicate.

**Comment by privateducky** [comment]
@CicadaMikoto I'm going to re-open this bug so others will see it while we root-cause & get a fix in before the 0.9.13 release.
