### ISSUE TITLE
Redirector tunnels will sometimes not accept beacons on the first connection and require the tunnel to be restarted

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#61]
There is an intermittent bug where new redirector tunnels will not accept inbound connections on the first connection. If the tunnel is restarted the connections will be established.

Temporary fix: Restart your tunnel.

**Comment by khyberspache** [comment]
My initial fix doesn't seem to have resolved this, so I'm going to keep digging.

**Comment by privateducky** [comment]
@khyberspache bumping. We'll want this in for the 1.0 release.
