### ISSUE TITLE
Authentication issues for specific platforms - Drop a note here if you are having AUTH issues on a specific platform

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#62]
We are intermittent reports of authentication issues on specific OS distributions (particularly linux).  We only really test on Kali Linux, but if you have an issue, drop a note here and I will deploy and test on that distro/platform.

**Comment by privateducky** [comment]
OS: Linux Mint
Issue: Login page does not render properly

**Comment by privateducky** [comment]
OS: Linux Parrot
Issue: Authentication token not working

**Comment by Anon-Artist** [comment]
Yeah @privateducky is right i had experienced issues on parrot OS ie, Auth token is not accepting

**Comment by khyberspache** [comment]
I'm downloading ParrotOS Security OVA right now to check

**Comment by khyberspache** [comment]
@Anon-Artist I just tried with `0.9.13` on the latest ParrotOS Security distro and was able to log in:

![image](https://user-images.githubusercontent.com/43142871/105231702-44c3a980-5b35-11eb-9d59-f1d207bc883d.png)

Can you provide repro instructions?

**Comment by Anon-Artist** [comment]
Iam using Parrot GNU/Linux 4.10

**Comment by privateducky** [comment]
closing. this issue is likely to get long forgotten, so let's handle 'em one at a time.
