### ISSUE TITLE
Plugins "unhandled exception error" AgentLibrary 0.9.13

### ISSUE THREAD

**Issue by EstesIO** [preludeorg/operator-support#64]

**Comment by EstesIO** [comment]
When selecting Plugins on OSX operator version   0.9.13 I received this error. Closing and refreshing did not resolve the 
<img width="1414" alt="Screen Shot 2021-01-20 at 2 27 13 PM" src="https://user-images.githubusercontent.com/15512797/105231149-0c6b9d80-5b2c-11eb-9fc0-94c26e2d0059.png">
issue.

**Comment by khyberspache** [comment]
@EstesIO You might still have an old version of the plugin because you were part of the old Beta program. Can you try running this command:

`rm -rf ~/Library/Application\ Support/Operator/workspace/plugins/`

**Comment by khyberspache** [comment]
I'm labeling this as a bug for now until we solve it. Also labeling it enhancement as I think we could gracefully handle these errors and offer an option to delete the plugin
