### ISSUE TITLE
Update training to indicate that Editor supports Drag n Drop of TTP Yml files

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#68]

**Comment by lzimm** [comment]
I'm not sure training is the best spot for this one but I've updated the badging on the editor to include a note that you can drag and drop (as well as other UX enhancements so it will now take you directly to the TTPs that you just dropped in)

![image](https://user-images.githubusercontent.com/139388/106647257-8bf16780-6543-11eb-8eb4-4993cdb127d3.png)
