### ISSUE TITLE
Looks like a typo in Procedures #1

### ISSUE THREAD

**Issue by xenoscr** [preludeorg/operator-support#7]
Should "A thread have 3 state" be "A thread can have" or "A thread has"?

![image](https://user-images.githubusercontent.com/2199813/97812683-fe0a9580-1c50-11eb-86cc-b2856db777df.png)

**Comment by privateducky** [comment]
Good eye. Will address before next release.

**Comment by privateducky** [comment]
Fixed the typo. You should see this if you restart your app in > 30 min from now.
