### ISSUE TITLE
Unhandled exception when importing atomic red team TTPs "split"

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#71]
![image](https://user-images.githubusercontent.com/22311332/106375065-19676880-6346-11eb-838a-0ec862d677bd.png)

**Comment by clr2of8** [comment]
I suspect that my accidental use of the "git@" ssh URL caused the issue. When I tried with HTTPS it worked. However, handling this gracefully would be ideal. Thanks

**Comment by khyberspache** [comment]
I'll take a look. I specifically design that import to handle both cases so something isn't right

**Comment by privateducky** [comment]
I've only used the https:// version of this but seems logical that both should work.

**Comment by lzimm** [comment]
I've patched this so it fails more gracefully. Should be fixed in 0.9.14
