### ISSUE TITLE
Lot of windows are open after a click on "export log"

### ISSUE THREAD

**Issue by c14dd49h** [preludeorg/operator-support#72]
My host is a VM of kali linux.
I'm in the reports part and I would like to export my log.
I have 0 log... and I put the 01/02/2021 17:00 as start time and 01/02/2021 17:05:03 as end time:
![image](https://user-images.githubusercontent.com/47661120/106486195-ae3aa500-64b1-11eb-825d-a6b4220287fa.png)
Then, I click on "export log" and at least 20 windows are open:
![image](https://user-images.githubusercontent.com/47661120/106486139-9ebb5c00-64b1-11eb-9b0d-405f066a4cd9.png)
On each windows, if I click on cancel, I get this error message: "Failed to write results: ENOENT: no such file or directory, open":
![image](https://user-images.githubusercontent.com/47661120/106486164-a549d380-64b1-11eb-91e0-41c544bca964.png)

**Comment by privateducky** [comment]
We saw this recently as well. Look for a fix shortly.

**Comment by privateducky** [comment]
for clarity: team decided this was due to exporting a report w/empty data and clicking cancel (20 times). We will resolve.

**Comment by privateducky** [comment]
bumping for @lzimm

**Comment by privateducky** [comment]
This appears to work fine on MacOS. Let's get a Windows test on this one.

**Comment by lzimm** [comment]
this should prevent this case from ever appearing by disabling the export button when there's no reports to export: https://github.com/preludeorg/operator/commit/e16ad050b7175b983dfcaf8cd8fca5818bf7f442
