### ISSUE TITLE
Authenticaton Problem on MacOS

### ISSUE THREAD

**Issue by semanurguneysu** [preludeorg/operator-support#74]
<img width="252" alt="Screen Shot 2021-02-02 at 14 46 33" src="https://user-images.githubusercontent.com/31063706/106596418-06cb7a00-6566-11eb-8be7-bf9fe497dc5b.png">

**Comment by privateducky** [comment]
@semanurguneysu thanks for posting! 

we have an open bug on this one, check for the resolution here: https://github.com/preludeorg/operator-support/issues/60

**Comment by semanurguneysu** [comment]
> @semanurguneysu thanks for posting!
> 
> we have an open bug on this one, check for the resolution here: #60

Thank you :)  It's worked.Sorry for the dublication.

**Comment by privateducky** [comment]
no problem, glad we could solve!
