### ISSUE TITLE
Feature Request: Filter TTPs to Community (or Non-Pro) only

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#76]
As a community user, I would like to be able to filter TTPs while searching so that I only see the ones available for me to use (not the "Pro" ones, for example)

**Comment by lzimm** [comment]
just landed it into master, should be ready for you in our next release :)

![image](https://user-images.githubusercontent.com/139388/106646948-23a28600-6543-11eb-9e72-6d2f78f9ac28.png)
