### ISSUE TITLE
Agent self clean-up/delete

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#77]
- Kill processes and delete executables

**Comment by khyberspache** [comment]
https://github.com/preludeorg/pneuma/pull/41/files

**Comment by khyberspache** [comment]
https://github.com/preludeorg/pneuma/pull/42/files

Supporting agent exit w/ a keyword exit

**Comment by khyberspache** [comment]
https://github.com/preludeorg/community/pull/41

**Comment by privateducky** [comment]
@khyberspache i know we've got most of this in now... let me know if I've got it:

- You can stop the agent process by executing a TTP (community repo) which leverages a keyword
- There is a current PR outstanding (Pneuma) to clean the agent file itself up (does this work cross-platform?)

If this is accurate, I think we'll want to:

1. Get in the file deletion 
2. Auto queue the agent delete TTP when you click the trashcan.
