### ISSUE TITLE
Pneuma agent beacons will io/timeout if DNS resolution fails

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#78]
- we can probably figure out a way around this

**Comment by khyberspache** [comment]
https://github.com/preludeorg/pneuma/compare/dns-bypass

**Comment by khyberspache** [comment]
This apparently had nothing to do with DNS, but we have this now 🤷‍♂️

**Comment by bfuzzy1** [comment]
🤣 it's my fault
