### ISSUE TITLE
Default to last deploy in reports tab

### ISSUE THREAD

**Issue by Eric-Tyrrell22** [preludeorg/operator-support#8]
Kind of annoying to have to fill out the date range every time I open the tab. Alternatively, it could just save the last time range used, so you don't have to redo it each time you want to look at your reports.

![Screen Shot 2020-11-01 at 6 32 01 PM](https://user-images.githubusercontent.com/58529434/97818618-68333280-1c71-11eb-8376-8dfc50a1fd83.png)

**Comment by privateducky** [comment]
Yep, this could get annoying. We'll roll this into one of the next minor versions.
