### ISSUE TITLE
File upload to operator (via curl TTP) doesn't produce any file artifacts on windows

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#84]
User reported:

![image](https://user-images.githubusercontent.com/43142871/106822948-1625f280-664e-11eb-97c2-6c6ccf49d20a.png)

This should have uploaded the file, but no artifacts were created.

I THINK this might be related to the permissions issue that we already squashed

**Comment by lzimm** [comment]
is there no file in the `/workspace/prelude/Mac1/artifacts` folder inside the users' app directory?

**Comment by khyberspache** [comment]
No there is not

**Comment by khyberspache** [comment]
![image](https://user-images.githubusercontent.com/43142871/106928700-73b74f00-66e1-11eb-8598-a9e27927d44c.png)

**Comment by khyberspache** [comment]
https://github.com/preludeorg/operator/pull/878

think it is fixed in that PR.


![](https://user-images.githubusercontent.com/43142871/106946604-4f666d00-66f7-11eb-9a69-06267c9f4922.png)
