### ISSUE TITLE
Allow multi-line commands for cmd executor

### ISSUE THREAD

**Issue by clr2of8** [preludeorg/operator-support#85]
Allowing a TTP to be defined using multiple lines makes the commands more readable and easy to understand, for example:

```
ipconfig /all
whoami /all
nslookup -type=any #{domainname}
```

verses: 

```
ipconfig /all & whoami /all & nslookup -type=any #{domainname}
```

This would also make the importing of Atomic Red Team tests more useful and many of those TTPs are defined as multi-line commands.

**Comment by privateducky** [comment]
@lzimm what do you think about assigning a delimiter to each executor and swapping out /n chars with it before saving?

This would open us up to things like (python):
```
x = 'hello';
;
y='world';
```
Which we could handle (if the line only contains a /n) or we could just accept it. thoughts overall?

**Comment by lzimm** [comment]
yeah that sounds like a reasonable strategy actually.
