### ISSUE TITLE
Selecting save and quit displays error

### ISSUE THREAD

**Issue by Eric-Tyrrell22** [preludeorg/operator-support#9]
Just quitting seems to work. 
Maybe it's happening because I'm using cloud storage?
![Screen Shot 2020-11-02 at 8 27 09 PM](https://user-images.githubusercontent.com/58529434/97936544-d77c5580-1d49-11eb-9494-eecdf41eb6c2.png)
![Screen Shot 2020-11-02 at 8 26 39 PM](https://user-images.githubusercontent.com/58529434/97936552-d9deaf80-1d49-11eb-81a5-c33603de5461.png)

**Comment by Eric-Tyrrell22** [comment]
Force quitting and starting the app got rid of the error

**Comment by privateducky** [comment]
We have updated this process to auto-save, therefore sidestepping any of these tricky IPC save/not save issues. If you install version 0.9.1, you will get this updated version with this solved.
