### ISSUE TITLE
Feature: Add a way to cancel commands in flight to the agent

### ISSUE THREAD

**Issue by bfuzzy1** [preludeorg/operator-support#90]
Current way is to clear queue if the sleep value is high enough. If the sleep value is low however the user will have to be fast in clearing the queue, which does not work for say a sleep value of 1. 

There should be an alternative way to cancel commands on their way to the agent.

**Comment by privateducky** [comment]
This came up yesterday, in a different context, with someone else. They were requesting we add the caldera feature we'd created to (optionally) require the user to accept/deny every command before it was added to an agent's queue. 

It seems like this would be good in your case as well, yeah?

**Comment by bfuzzy1** [comment]
Yea that could work!

**Comment by privateducky** [comment]
bumping for @lzimm
