### ISSUE TITLE
Unhanded exception while trying to import a TTP

### ISSUE THREAD

**Issue by KINGxMONT** [preludeorg/operator-support#91]
![Editor Error](https://user-images.githubusercontent.com/78564198/106947828-e67ff480-66f8-11eb-8295-73ff2366a29a.PNG)

**Comment by privateducky** [comment]
hi @KINGxMONT for TTP import of a GIT repository, you'll want to put the git address itself, such as: https://github.com/redcanaryco/atomic-red-team.git

This will import all TTPs under that repo.

**Comment by lzimm** [comment]
i believe this was actually fixed in 0.9.14

**Comment by privateducky** [comment]
@lzimm to clarify: we throw a more explicit error in the upcoming 0.9.14 version, we don't handle single TTP import via the screenshot, correct?

**Comment by lzimm** [comment]
@privateducky my bad, correct :)
