### ISSUE TITLE
Cloud Plugin: Need to be able to submit more granular cloud configurations

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#94]
- AWS region specification

**Comment by khyberspache** [comment]
* Offer option to terminate an instance when a redirector is deleted from operator

**Comment by privateducky** [comment]
Agree on both fronts. Going to mark this as a new feature however so it'll come > v1.0 unless we can squeeze it in.

**Comment by privateducky** [comment]
Re-marking this as an enhancement to do by our 1.0 release. This will require updates to the cloud plugin.

**Comment by privateducky** [comment]
We de-scoped this to be only delete.
