### ISSUE TITLE
Blackout remnant hides bottom of screen info while in Light Mode, Win 10

### ISSUE THREAD

**Issue by kalimax69** [preludeorg/operator-support#98]
![image](https://user-images.githubusercontent.com/76034874/107318351-6e476500-6a51-11eb-959f-20a706082492.png)

**Comment by khyberspache** [comment]
Whoa

**Comment by khyberspache** [comment]
![CleanShot 2021-02-09 at 16 22 39](https://user-images.githubusercontent.com/43142871/107430376-119c8680-6af3-11eb-8f58-1453bce22b86.png)
fixed in 0.9.15
