### ISSUE TITLE
Bug: Operator Reports timestamps invalid

### ISSUE THREAD

**Issue by khyberspache** [preludeorg/operator-support#99]
![image](https://user-images.githubusercontent.com/43142871/107406285-46e6ab80-6ad6-11eb-95a0-89bc116d09ed.png)

![image](https://user-images.githubusercontent.com/43142871/107406303-4c43f600-6ad6-11eb-87f4-22dbb5479b41.png)

**Comment by privateducky** [comment]
I think this will catch most (maybe all?) of the issues.
https://github.com/preludeorg/operator/commit/e800273d5c146965e2c51ab40a0b2992b40e83d0

**Comment by privateducky** [comment]
Closing. I haven't seen any negative timestamps in testing last 2 days... fingers crossed... re-open if you find one.
